### ISSUE TITLE
Rules for Office365 audit-logs

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#8681]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Modulesd | Manager/Agent | Packages/Sources | All |

It is necessary to develop a new Wazuh module to collect all Office365 logs.

The main goal of this issue is to create some rules for the Office365 logs, which are in JSON format.

As part of this issue, it is also necessary to verify that alerts are generated when these events reach the manager.

In addition, unit tests has to be created for all new rules.

Activities:
- [x] Rules for each RecordType (this will cover every kind of log)
- [x] List a top 10 detections to be covered (nice-to-have)
- [x] Map those detections to a Mitre technique
- [x] Make a list of important operations and cover them (MUST operation list)
- [x] Add rules with more security-value and related to previous detections

**Comment by NicoGuini** [comment]
# Approach Proposal:

1.  Vectra Top 10 Threat Detections for Office 365 [Report](https://content.vectra.ai/rs/748-MCE-447/images/IndustryResearch_SpotlightReportTop10Detections.pdf)
2. Cover Mitre matrix techniques for Office 365 [Matrix](https://attack.mitre.org/matrices/enterprise/cloud/office365/)

## Vectra perspective
![image.png](https://images.zenhubusercontent.com/60ad850e89e8275215d8de44/3fcfe709-fcb0-4fa5-8e1b-2d7276a0aad1)
![image.png](https://images.zenhubusercontent.com/60ad850e89e8275215d8de44/626cd828-635c-4240-be3c-5b9454e9a1d2)

## Mitre perspective
![image.png](https://images.zenhubusercontent.com/60ad850e89e8275215d8de44/017413da-98d0-4ca2-9b36-18c0e9fcf101)


# Log Analysis
Log Reference: https://wazuh-team.slack.com/files/UPBJ7R33N/F022YAV06JD/office365-logs_txt.txt

Operation types
```
  Audit.General
    "Get-ComplianceSearch"
    "Get-ComplianceSearchAction"
    "Get-ComplianceTag"
    "Get-DlpSensitiveInformationType"
    "Get-RetentionCompliancePolicy"
    "Get-SupervisoryReviewOverallProgressReport"
    "Get-SupervisoryReviewPolicyV2"
    "Get-SupervisoryReviewReport"
    "Get-SupervisoryReviewTopCasesReport"
    "SearchAlert"
    "SearchAlertAggregate"
    "SearchDataInsightsSubscription"
    "ValidaterbacAccessCheck"
  Audit.AzureActiveDirectory
    "Add service principal."
    "Change user license."
    "Update user."
    "UserLoggedIn"
  Audit.SharePoint
    "AddedToGroup"
    "ClientViewSignaled"
    "FileAccessed"
    "FileAccessedExtended"
    "FileCheckedOut"
    "FileModified"
    "ListUpdated"
    "ListViewed"
    "PagePrefetched"
    "PageViewed"
    "PageViewedExtended"
    "SharingPolicyChanged"
    "SiteCollectionAdminAdded"
    "SiteCollectionAdminRemoved"
    "SiteCollectionCreated"
    "SiteDeleted"
  Audit.Exchange
    "Create"
    "ModifyFolderPermissions"
    "Remove-UnifiedGroup"
    "Set-Mailbox"
    "Set-UnifiedGroup"
    "Set-User"
```

Using jq tool for this [jq](https://stedolan.github.io/jq/download/)
  $> cat .\tmp.json | .\jq.exe '.[] .Operation' (Operation Types)
  $> cat .\tmp.json | .\jq.exe '.[] | keys' (Get Json keys for each JSON)

**Comment by NicoGuini** [comment]
# Next Steps proposal

1. Map Vectra detections to Mitre. Could be considered as 1 Vectra detection to N Mitre techniques. (This will help to standardize detections)
2. Collect information of each technique (ways to reproduce, data sources, logs, blogs, reports, examples)
3. Generate rules (verify the approach by RecordTypes or use Operations instead) (we will need a sync meeting for this)
4. Generate testing by adding UT/ini files

**Comment by NicoGuini** [comment]
# O365 Risky Exchange Operation

## Description
Abnormal Exchange operations have been detected that may indicate an attacker is manipulating Exchange to gain access to specific data or further attack progression.

## Mitre technique
https://attack.mitre.org/techniques/T1098/002/
Account Manipulation: Exchange Email Delegate Permissions

**Comment by NicoGuini** [comment]
# Azure AD Suspicious Operation
## Description
Abnormal Azure AD operations have been detected that may indicate attackers are escalating privileges and performing admin-level operations after regular account takeover.

## Mitre technique
https://attack.mitre.org/techniques/T1078/ (Azure AD matrix)
Valid Accounts

**Comment by NicoGuini** [comment]
# O365 Suspicious Download Activity
## Description
An account was seen downloading an unusual number of objects which may indicate an attacker is using SharePoint or OneDrive download functions to exfiltrate data.

## Mitre technique
https://attack.mitre.org/techniques/T1213/002/
Data from Information Repositories: Sharepoint

**Comment by NicoGuini** [comment]
# O365 Suspicious Sharing Activity
## Description
An account was seen sharing files and/or folders at a volume that is higher than normal which may indicate an attacker is utilizing SharePoint to exfiltrate data or maintain access after initial access has been remediated.

## Mitre technique
https://attack.mitre.org/techniques/T1213/002/
Data from Information Repositories: Sharepoint

**Comment by NicoGuini** [comment]
# Azure AD Redundant Access Creation
## Description
Administrative privileges have been assigned to an entity which may indicate redundant access is being created by the attacker to guard against remediation.

## Mitre technique
https://attack.mitre.org/techniques/T1098/001/ (Azure AD matrix)
Account Manipulation: Additional Cloud Credentials

**Comment by NicoGuini** [comment]
# O365 Suspicious Power Automate Flow Creation
## Description
An abnormal Power Automate Flow creation has been observed which may indicate an attacker is configuring a persistence mechanism.

## Mitre technique
(Potential new technique). Tactic: Persistence
Could fit into: https://attack.mitre.org/techniques/T1137/006/
Office Application Startup: Add-ins

**Comment by NicoGuini** [comment]
# O365 Suspicious Mail Forwarding
## Description
Mail forwarding which may be used as a collection or exfiltration channel without the need to maintain persistence.

## Mitre technique
https://attack.mitre.org/techniques/T1114/003/
Email Collection: Email Forwarding Rule

**Comment by NicoGuini** [comment]
# O365 Unusual eDiscovery Search
## Description
A user is creating or updating an eDiscovery search which may indicate an attacker has gained access to eDiscovery capabilities and is now performing reconnaissance.

## Mitre technique
(Potential new technique). Tactic: Discovery
Could fit into: https://attack.mitre.org/techniques/T1526/
Cloud Service Discovery

**Comment by NicoGuini** [comment]
# O365 Suspicious Sharepoint Operation
## Description
Abnormal administrative SharePoint operations that may be associated with malicious activities.

## Mitre technique
(Too wide)
Could fit into: https://attack.mitre.org/techniques/T1213/002/
Data from Information Repositories: Sharepoint

**Comment by NicoGuini** [comment]
Adding a list of operations that we MUST distinguish from the rest, and also a list of operations that are useful or insteresting to track:

<details>

```
Operations that we MUST cover: (Important or useful for a detection)
  File and page activities (SharePoint and OneDrive):
    FileMalwareDetected
    DocumentSensitivityMismatchDetected
    FileDownloaded
  Sharing and access request activities (SharePoint and OneDrive):
    PermissionLevelAdded
    SharingInvitationBlocked
  Exchange mailbox activities:
    Add-MailboxPermission
    AddFolderPermissions
    Send
    SendAs
    SendOnBehalf
  User administration activities
    Add user.
  Azure AD group administration activities
    Add group.
    Add member to group.
  Application administration activities (Azure AD)
    Add service principal
    Add service principal credentials.
  Role administration activities (Azure Ad)
    Add member to role.
  eDiscovery activities
    CaseAdminUpdated
    CaseAdminAdded
    CaseAdded
    SearchCreated
  Quarantine activities:
    QuarantineDelete
    QuarantineExport
    QuarantinePreview
    QuarantineRelease
    QuarantineViewHeader


Interesting to track:
  File and page activities (SharePoint and OneDrive):
    FileAccessed
    FileCopied
    FileDeleted
    FileMoved
    FileUploaded
  Folder activities (SharePoint and OneDrive):
    FolderCopied
    FolderCreated
    FolderDeleted
    FolderMoved
  Sharing and access request activities (SharePoint and OneDrive):
    AccessRequestCreated
    AnonymousLinkCreated
    SharingInvitationCreated
    AnonymousLinkUpdated
    AnonymousLinkUsed
  Site permissions activities (Sharepoint):
    SiteCollectionAdminAdded
    AddedToGroup
    GroupAdded
    GroupRemoved
    PermissionLevelModified
    SitePermissionsModified
    SiteCollectionAdminRemoved
    RemovedFromGroup
    GroupUpdated
  Site administration activities (Sharepoint):
    AllowedDataLocationAdded
    GeoAdminAdded
    AllowGroupCreationSet
    SharingPolicyChanged
    DeviceAccessPolicyChanged
  Exchange mailbox activities
    SoftDelete
    HardDelete
    Move
    UpdateFolderPermissions
  User administration activities
    Change user license.
    Change user password.
    Delete user.
    Reset user password.
    Set license properties.
    Update user.
  Azure AD group administration activities
    Delete group.
    Remove member from group.
    Update group.
  Application administration activities (Azure AD)
    Remove service principal.
    Remove service principal credentials.
  Role administration activities (Azure Ad)
    Remove member from role.
  Directory administration activities
    Add domain to company.
    Add partner to company.
    Set domain authentication.
    Remove domain from company.
    Remove partner from company.
    Set domain authentication.
  eDiscovery activities
    SearchPermissionCreated
    CaseAdminRemoved
    CaseRemoved
  Teams activities:
    ChannelAdded
    ConnectorAdded
    MemberAdded
    MemberRoleChanged
    AppInstalled
    TeamSettingChanged
    ChannelDeleted
    ConnectorRemoved
    MemberRemoved
    AppUninstalled
  Sensitivity label activities
    SensitivityLabelApplied
    SensitivityLabelRemoved
    FileSensitivityLabelApplied
    FileSensitivityLabelRemoved
    FileSensitivityLabelChanged
  Retention policy and retention label activities
    NewRetentionComplianceRule
    NewRetentionCompliancePolicy
    RemoveRetentionComplianceRule
    RemoveRetentionCompliancePolicy
```

</details>

**Comment by 72nomada** [comment]
## Interesting to track:
###  File and page activities (SharePoint and OneDrive):
- [ ]    FileAccessed
- [ ]    FileCopied
- [ ]    FileDeleted
- [ ]    FileMoved
- [ ]    FileUploaded
###  Folder activities (SharePoint and OneDrive):
- [ ]    FolderCopied
- [ ]    FolderCreated
- [ ]    FolderDeleted
- [ ]    FolderMoved
###  Sharing and access request activities (SharePoint and OneDrive):
- [ ]    AccessRequestCreated
- [ ]    AnonymousLinkCreated
- [ ]    SharingInvitationCreated
- [ ]    AnonymousLinkUpdated
- [ ]    AnonymousLinkUsed
###  Site permissions activities (Sharepoint):
- [ ]    SiteCollectionAdminAdded
- [ ]    AddedToGroup
- [ ]    GroupAdded
- [ ]    GroupRemoved
- [ ]    PermissionLevelModified
- [ ]    SitePermissionsModified
- [ ]    SiteCollectionAdminRemoved
- [ ]    RemovedFromGroup
- [ ]    GroupUpdated
###  Site administration activities (Sharepoint):
- [ ]    AllowedDataLocationAdded
- [ ]    GeoAdminAdded
- [ ]    AllowGroupCreationSet
- [ ]    SharingPolicyChanged
- [ ]    DeviceAccessPolicyChanged
###  Exchange mailbox activities
- [ ]    SoftDelete
- [ ]    HardDelete
- [ ]    Move
- [ ]    UpdateFolderPermissions
###  User administration activities
- [ ]    Change user license.
- [ ]    Change user password.
- [ ]    Delete user.
- [ ]    Reset user password.
- [ ]    Set license properties.
- [ ]    Update user.
###  Azure AD group administration activities
- [ ]    Delete group.
- [ ]    Remove member from group.
- [ ]    Update group.
###  Application administration activities (Azure AD)
- [ ]    Remove service principal.
- [ ]    Remove service principal credentials.
###  Role administration activities (Azure Ad)
- [ ]    Remove member from role.
###  Directory administration activities
- [ ]    Add domain to company.
- [ ]    Add partner to company.
- [ ]    Set domain authentication.
- [ ]    Remove domain from company.
- [ ]    Remove partner from company.
- [ ]    Set domain authentication.
###  eDiscovery activities
- [ ]    SearchPermissionCreated
- [ ]    CaseAdminRemoved
- [ ]    CaseRemoved
### Teams activities:
- [ ]    ChannelAdded
- [ ]    ConnectorAdded
- [ ]    MemberAdded
- [ ]    MemberRoleChanged
- [ ]    AppInstalled
- [ ]    TeamSettingChanged
- [ ]    ChannelDeleted
- [ ]    ConnectorRemoved
- [ ]    MemberRemoved
- [ ]    AppUninstalled
###  Sensitivity label activities
- [ ]    SensitivityLabelApplied
- [ ]    SensitivityLabelRemoved
- [ ]    FileSensitivityLabelApplied
- [ ]    FileSensitivityLabelRemoved
- [ ]    FileSensitivityLabelChanged
###  Retention policy and retention label activities
- [ ]    NewRetentionComplianceRule
- [ ]    NewRetentionCompliancePolicy
- [ ]    RemoveRetentionComplianceRule
- [ ]    RemoveRetentionCompliancePolicy
