### ISSUE TITLE
Improving the vulnerability detector retry mechanism in case of a syscollector scan in progress

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#8686]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | Vulnerability Detector | Manager | Packages/Sources | - |

### Description

Now that vulnerability detector has a retry mechanism in case the agent's database is busy, it could happen that the first synchronization takes more time than expected and the defined attempts aren't enough for this process to be completed.

This is the log printed

```
2021/05/14 19:19:59 wazuh-modulesd:vulnerability-detector: WARNING: (5507): The software of the agent '000' could not be obtained after 5 attempts. Skipping agent until the next scan.
```

An enhancement could be implemented, like a sleep time after every attempt.

**Comment by DProvinciani** [comment]
Closing the issue as this was fixed by https://github.com/wazuh/wazuh/issues/8701.
