### ISSUE TITLE
Missing fields in Windows 10 - Syscollector

### ISSUE THREAD

**Issue by pablomarga** [wazuh/wazuh#8691]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Wazuh component | Agent | Packages | Windows 10|

## Os build is incomplete

Hello team, 

I have checked that currently, we are not getting the full Os build from an agent, the last 3 numbers are missing which are the `Update Build Revision`. Should we show this information by adding another field? 

![Screenshot_20210517_123429](https://user-images.githubusercontent.com/46006326/118475207-3fa1f000-b70c-11eb-83c1-0033f56dac88.png)

![Screenshot_20210517_121330](https://user-images.githubusercontent.com/46006326/118475094-1da86d80-b70c-11eb-81c7-35517676a587.png)
![Screenshot_20210517_121254](https://user-images.githubusercontent.com/46006326/118475096-1e410400-b70c-11eb-9e0b-bd50ef8e2a1c.png)

Expected values:
build: 16299.192
version: 10.0.16299.192

## DoD
- [x] Append build and version field with the UBR registry value. !!!Don't affect the release field!!!! - data_provider
- [x] Append build and version field with the UBR registry value. !!!Don't affect the release field!!!! - Global DB
- [x] Modify/Add unit tests.
- [x] Test windows version >= Windows XP.
- [x] Test vulnerability detection feature.

**Comment by Dwordcito** [comment]
Hi @chemamartinez 

to clarify the doubt and not to lose compatibility of vulnerability detector.

Should the build look like this? 16299.192

And the version like that? 10.0.16299.192

**Comment by chemamartinez** [comment]
> Hi @chemamartinez
> 
> to clarify the doubt and not to lose compatibility of vulnerability detector.
> 
> Should the build look like this? 16299.192
> 
> And the version like that? 10.0.16299.192

Hi @Dwordcito,

Actually, Vulnerability Detector is not worried about this field. It only takes care of the release ID, which is 1709 in the example of the description. Sorry for the mistake with the labeling.

This is just a request of having this revision in the OS inventory so your suggestion is good. Another option would be to include a new field called `update build revision` or `revision` for this new data.
