### ISSUE TITLE
Setting the agent's database as synced after a checksum calculation during a vulnerability detector scan 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#8694]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.3 | Vulnerability Detector - Wazuh-DB | Manager | Packages/Sources | - |

### Description

As part of the epic #8529, a mechanism to get all the packages installed on an endpoint in an atomic way is implemented.
The vulnerability detector modules checks the synchronization status of the database before making a package/hotfix request. It could happen that: 
- The data is synced and ready to use
- The data is not ready because the checksum verification wasn't positive (synchronization is process)
- The checksum verification was positive and synchronization ended but it wasn't marked as ready yet

It would be necessary to set the database as synced after a successful checksum verification to avoid calculating it again.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8706 was merged.
