### ISSUE TITLE
Separate agent from manager

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8695]
## Description

This epic aims to make in fact the explicit separation of the project, and the installation of process.

Part of the requirements is not yet defined. But first of all, we must define what is conceptually an agent and is not shared as support for the project.

As part of this epic, it is necessary to redefine the construction of the project. By doing the detachment, it's a good opportunity to switch to using CMake as the project builder and use its advantages.

Then we must consider the option of creating a new binary specific to agent modules and another specific to manager modules, and that this as such has an explicit separation at the code level.

Another of the points affected by this time is to modify the IPC selectors when the installation is a manager (unix/tcp-udp sockets), in favor of tcp-udp, regardless of whether an agent is installed in the same environment. This is to generalize the protocols. And so that the agents install exactly the same binaries and processes regardless of whether or not the manager is installed.

## Non functional requirements.
- TBD

**Comment by vikman90** [comment]
Superseded by https://github.com/wazuh/wazuh-agent/issues/7.
