### ISSUE TITLE
OSSEC logrotate configuration in package is a bit noisy

### ISSUE THREAD

**Issue by ffleming** [wazuh/wazuh#87]
Originally reported in #52, but I think the reporter misunderstood what was happening.  The problem is that restarting `ossec` produces a ton of output, so the cron job that runs `logrotate` captures that output and emails it.

This issue is particularly with the package that Wazuh maintains that is installed by the `ossec-puppet` module, not with the source code of HIDS itself.  I was unsure *where* exactly to put this, since I couldn't find a place in your repositories that defined the logrotate configuration file.  If you'd like me to re-open this issue somewhere else, I'm happy to do so 😃 

`/etc/logrotate/ossec-hids` currently reads

```
# Log rotation for Ossec HIDS
/var/ossec/logs/*.log {
    create 640 ossec ossec
    rotate 31
    compress
    missingok
    notifempty
    olddir /var/ossec/logs/archives/
    sharedscripts
    postrotate
       /var/ossec/bin/ossec-control restart
    endscript
}
```

As such, every night the cronjob mails us `stdout` and `stderr`:

```
Killing ossec-monitord ..
Killing ossec-logcollector ..
Killing ossec-remoted ..
Killing ossec-syscheckd ..
Killing ossec-analysisd ..
ossec-maild not running ..
Killing ossec-execd ..
OSSEC HIDS v2.8.3 Stopped
Starting OSSEC HIDS v2.8.3 (by Trend Micro Inc.)...
2017/03/13 17:24:41 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-remoted...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.
```

Instead, it'd be great if the default logrotate file included could read
```
...
    postrotate
       /var/ossec/bin/ossec-control restart 2> /dev/null > /dev/null
    endscript
```

If only `stdout` is redirected to `/dev/null`, you still get `INFO` messages, e.g.:
```
2017/03/13 17:27:29 ossec-maild: INFO: E-Mail notification disabled. Clean Exit
```

There is a bit of a problem with the above, in that it won't output  (and therefore won't email) even if there is an actual problem with the logrotate postrotate command.  I'm not quite sure how to solve that bit.

Currently, I'm managing `/etc/logrotate.d/ossec-hids` as a workaround but it'd be nice if it were a bit less chatty by default (even if only `stdout` were redirected to `/dev/null`; I totally get why redirecting `stderr` might not be a default that you want).

Also, thank you for maintaining all these packages, modules, repos, etc!  Y'all are the best :heart:

**Comment by jlruizmlg** [comment]
Hi @ffleming you are right, we just create a issue to include the logs rotation in the ossec system #88. Meanwhile i will test this our labs and apply in the packages.
 
Thanks for your feedback.

**Comment by jlruizmlg** [comment]
Hi @ffleming the logrotate file included in Wazuh 2.0 includes your fix, also we are working in the new packages for OSSEC-HIDS 2.9.x and this packages will include this fix as well.

**Comment by ffleming** [comment]
Awesome! Thanks for the heads up!

**Comment by knzudgt** [comment]
Hi @jlruizmlg, I beg your pardon if I joined this discussion. Since I wanted a `local` installation of OSSEC-HIDS, I had (because I though I had no other choice) to install it from source and there is no logrotate configuration for `/var/ossec/logs/ossec.log`. Is it possible to have a look at the logrotate file for Ubuntu packages 2.9.x and know if it can work for source as well, or are you still working on it?

**Comment by jlruizmlg** [comment]
HI @ffleming yes, we still working in that, wazuh by default is include in the core system the rotation, in OSSEC-HIDS we need to include in logrotate, meanwhile you can use the code provided by @ffleming in your logrotate configuration.

**Comment by jlruizmlg** [comment]
and apologizes for the delay in the packages!!

**Comment by Zenidd** [comment]
Hi @ffleming,

Thank you for contributing to the wazuh project. This has been fixed on https://github.com/wazuh/wazuh/pull/318. 
I'm closing this ticket. If your problems persist do not hesitate to contact us.
<br></br>
Greetings,

Juan Pablo Sáez
