### ISSUE TITLE
Add a customizable delay to vul-det scans retry logic

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8701]
### Description

As part of the epic #8529, a retry logic was implemented to rescan the agents that weren´t ready to be scanned. The main reason for this is when the agent DataBase is being updated by **syscollector**. Now the agents are attempted to be scanned 5 times, without a minimal delay between scans.

During the epic exploratory testing ([link](https://github.com/wazuh/wazuh/issues/8573#issuecomment-841511508)) it was found that a **syscollector** scan can last as much as 90 seconds to complete, and the scan of an agent that has every package set as triaged lasts less than a second to complete. This leads to completing the 5 attempts of an agent before the **syscollector** update ends.

It´s now required to add a minimum delay between retries to guarantee that a minimum time will occur, bringing the possibility to **syscollector** to end the update. A new configurable setting must be added to **ossec.conf**  in **vulnerability detector** section.

### Requirements

- The name of the new setting should be `retry_scan`.
- This setting must be `30` seconds and hidden by default.
- This **retry_scan** must act as a minimum time between retries, which means that if other agents last some seconds to be scanned, the time to sleep until trying to scan again should be the difference of `retry_scan` minus the time used scanning.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8702 was merged.
