### ISSUE TITLE
CIS Benchmark for Windows 10 Enterprise (Release 1803)  - Xbox Live Networking Service (XboxNetApiSvc) - Wrong check

### ISSUE THREAD

**Issue by iostack** [wazuh/wazuh#8729]
|Wazuh version| Component | Action type |
| 4.1 | SCA | Error |

## Description
Wrong registry key check 
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\XboxNetApiSvce
should be
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\XboxNetApiSvc

**Comment by vikman90** [comment]
Hi @iostack,

You're absolutely right, there is a typo in the rule. I've sent #10375 to fix that.

Thank you very much for reporting this issue.
Best regards.
