### ISSUE TITLE
Secondary JSON decoder Issue

### ISSUE THREAD

**Issue by Ramsiyahassan2021** [wazuh/wazuh#8733]
Hi Team,

We need to decode the Bitdefender JSON format logs in Wazuh-manager. To accomplish this, we need to create a secondary JSON decoder to parse all the fields. Bitdefender logs are given below;

`{
"jsonrpc":"2.0",
"method":"addEvents",
"params":{
"events":[
{
"computer_name":"FC-WIN7-X64-01",
"computer_fqdn":"fc-win7-x64-01",
"computer_ip":"10.17.46.196",
"computer_id":"59a1604e60369e06733f8abb",
"product_installed":"BEST",
"malware_type":"file",
"malware_name":"EICAR-Test-File (not a virus)",
"file_path":"C:\\eicar0000001.txt",
"hash":"8b3f191819931d1f2cef7289239b5f77c00b079847b9c2636e56854d1e5eff71",
"final_status":"deleted",
"timestamp":"2017-09-08T12:01:36.000Z",
"companyId":"5ed47b5a73574847db2b305d",
"module":"av",
"_testEvent_":true
}
]
},
"id":1621422603719`

The expected result is to decode the contents inside the "events" and create the rules against the value "module" we have created one decoder which has a parent that is JSON and it's worked. But, other logs related to the JSON decoders are not working. (such as office 365, azure).

Please help me if you have any ideas.

**Comment by jnasselle** [comment]
Hi @Ramsiyahassan2021,

Unfortunately there's no dedicated and specific functionality to achieve this, and workarounds (i.e use integratord to re-ingest alerts, tricky decoders) will lead to others new problems and is not recommended.

There's an already opened issue #2013 as feature request. You can follow the process there.

I am very sorry for the inconvenience and hope you understand.
Regards,
Nico
