### ISSUE TITLE
Add new fields to vulnerabilities inventory database 

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#8735]
### Description

As part of epic #8727,  the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. Having said that, the vulnerabilities inventory database should store additional information about the vulnerabilities found in the system.

### Requirements

-  **severity**, **score**, and **detection time** should be added to the `vuln_cves` table.
- Consider that there are two versions for the **score** (cvss2 and cvss3) and the values may be **null**.
- The upgrade schema should be adapted for these changes.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8736 was merged.
