### ISSUE TITLE
Windows agent does not show error messages in `ossec.log` when applying invalid internal Wazuh configuration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#8746]
#### Version
```
Wazuh 4.2.0
```
While testing `logcollector` and `agentd` options, we found out that the Windows agent wasn't showing the error messages expected when an invalid internal option is selected. This problem doesn't occur always, we managed to get the log once of each ten attempts. 

## Step to reproduce

On a windows wazuh agent, set invalid internal options like the next ones:

  #### local_internal_options
  `logcollector.state_interval=-2`
  `agent.state_interval=86401`

Now, take a look at `ossec.log`, we are expecting a `CRITICAL` error message. It appears randomly.

#### Expected log
![expected_log](https://user-images.githubusercontent.com/80041853/126654500-9c9d20f8-aadb-413a-93cd-17ed9ba122d3.png)
#### Usual log
![image](https://user-images.githubusercontent.com/80041853/118965432-fac6c500-b968-11eb-91be-ec527e1561b1.png)

**Comment by chemamartinez** [comment]
The box where the bug was replicated is `gusztavvargadr/windows-server-standard`.

**Comment by MarcelKemp** [comment]
Done #10381
