### ISSUE TITLE
Investigation why macOS Sierra is not handling some expected logs from log stream

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#8770]
Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| - | wazuh-logcollector | Agent | - | macOS Sierra|

## Description
Hi Team!

Doing #8484 we found that some logs were missing when collecting macOS ULS using a predicate in macOS Sierra.

## Steps to reproduce
1. Install manager (any OS) from #8632 
2. Install macOS agent from #8632 and link with the manager of step 1.
3. In the macOS agent of step 2, set the next `localfile` and restart it.
```xml
  <localfile>
    <log_format>macos</log_format>
    <location>macos</location>
    <query>process == "sshd" or messageType == error</query>
    <only-future-events>no</only-future-events>
  </localfile>
```
4. Execute: `log stream --style syslog --predicate 'process == "sshd" or messageType == error'`
5. Try some invalid login via SSH

## Expected result
Logs shown in log stream (related with the predicate) were handled by the agent and sent to manager.

## Current result
Only some logs (specially `sshd` logs) shown in log stream were handled by the agent and sent to manager. 

Regards,
Nico

**Comment by jnasselle** [comment]
## Update
This scenario was reproduced in macOS Sierra, High Sierra, Mojave, Catalina and BigSur, only failing on Sierra.
Apparently is related to STDOUT buffer size and the flush policy.

Regards,
Nico

**Comment by nmkoremblum** [comment]
Some of the alternatives that have worked so far are the following:

1 - Upgrade `expect` tool and call the `unbuffer` command prior to using `log stream ...` as its arguments as follows:
```bash
# unbuffer /usr/bin/log stream ...
```
2 - Do not upgrade `expect` tool and call the `unbuffer.sh` script prior to using `log stream ...` as its arguments as follows:
```bash
# ./unbuffer.sh /usr/bin/log stream ...
```
3 - Use `script` tool command with "-q /dev/null" options prior to using `log stream ...` as its arguments as follows:
```bash
# script -q /dev/null /usr/bin/log stream ...
```

The team is still analyzing how using these tools may affect the normal functioning of **Logcollector** and **Wazuh**.

Some concerns we have about `expect` are that on option **1** it is mandatory to upgrade the `expect` package that comes installed on macOS Sierra and in option **2** as a script is needed it might be modified by a malicious user.

We are also analyzing how these tools respond to bash/shell injections.

**Comment by nmkoremblum** [comment]
Doing further research we've realized that `script` and `expect` (`unbuffer`) solve the problem in a similar way, by working with PTYs and grouping the data streams. After analyzing both cases we've realized the following:

**`script`:**
- Pros
  - Cleaner & more specific Code
  - No dynamic memory allocation
  - No need package upgrade
  - No "unsafe" scripts
  - No need of linking Libraries
- Cons
  -  Messages come with a `'\r'` character on every end of line
  
**`expect`**
- Pros
  - Very open / flexible license
  - It might be possible to use its C functions to make use of it without having to use the scripts (couldn't make it work yet)
-  Cons
   - Complex Code
   - Uses various dynamic memory allocations
   - Libraries must be linked (if using its C functions)

**Comment by nmkoremblum** [comment]
Last tests have shown that, when using the `script` way, `log` process continues running even after killing its parent processes. This does not happen with the `expect` way.

A stranger situation occurs when killing the `log` parent process (`script`) from a different TTY. In this case, `log` does indeed cease its execution.

We haven't found a workaround yet to solve this issue.

**Comment by jnasselle** [comment]
By bad. Closing it again.
