### ISSUE TITLE
Modify the insert/update WDB command to add more information to vuln_cves inventory.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#8772]
### Description

As part of epic #8727, the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. Now, the insert/update WDB command should be able to manage the new required information. 

### Requirements

- Modify the insert/update WDB command to receive **severity**, **cssv2** and **cssv3**
- Modify the sqlite3 query to insert/update those fields in the database
- For the insert command only, an additional field **detection_time** should be inserted. Define the best way to implement the query for that purpose. 

### Testing requirements
- Adapt old UTs and create new ones if needed.
- Manual testing against WDB socket for insert/update

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8774 was merged.
