### ISSUE TITLE
Adequate vulnerability detector calls and insert/update helper method to add new information to vuln_cves

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#8773]
### Description

As part of epic #8727, the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. Now, the vulnerability detector module should be able to obtain the new information and pass it to WDB to be inserted in the vuln_cves inventory. 

### Requirements
- Modify vulnerability detector calls to pass the new information to the WDB helper method.
- Modify the insert/update helper method to receive the parameters: **severity**, **cvss2** and  **cvss3**.

### Testing requirements
- List UTs that need revision and UTs that must be implemented for the mentioned changes.
- Manual testing of vulnerability detector scans.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8848 was merged.
