### ISSUE TITLE
Unable to open wazuh-archives indices

### ISSUE THREAD

**Issue by Alex989898** [wazuh/wazuh#8776]
Hello Team!

I have created the wazuh-archives-* index pattern.
I see this indices in the list of indices.

But it is unable to choose this pattern in app.

Can you help me?

![image](https://user-images.githubusercontent.com/76589387/119321238-18f03600-bc85-11eb-9490-98992c1b08c8.png)

![image](https://user-images.githubusercontent.com/76589387/119321467-594fb400-bc85-11eb-90f4-0c0fce8f4f4d.png)

![image](https://user-images.githubusercontent.com/76589387/119321525-69679380-bc85-11eb-977f-cffd46a5f3c2.png)

![image](https://user-images.githubusercontent.com/76589387/119321626-82704480-bc85-11eb-8c04-e7bbebad4d3f.png)

--
Alex

**Comment by JcabreraC** [comment]
Hello @Alex989898 ,

In the last image, I see that you can select the index pattern in the app. However, you don't see it in the "change index pattern" menu.

The menu that does not have the index, is in the events tab?

Currently, you have to change the index pattern in the app to see it in the events tab of any module. Even if you have several index patterns, in this tab you can only select the one you set in the app.

Regards

**Comment by Alex989898** [comment]
Hello @JcabreraC

When I choose the pattern "wazuh-archives-*" (see last image) - nothing happens.
When I open this menu next time - it is again the "wazuh-alerts-*" item is chosen . App is ingoring my choice :)

**Comment by JcabreraC** [comment]
Hello @Alex989898 ,


To change the index pattern in the modules, you first have to change the index pattern in the app. Once changed in the app, you can select that index pattern in the `Event` tab of any module.

Regards !

**Comment by Alex989898** [comment]
Hello @JcabreraC ,

The problem is that **I can not to change the index pattern in the app**. It looks like App is ignoring my choice.

I change it to "wazuh-archives-", but nothing happens and App changes it to "wazuh-alerts-" again.

![image](https://user-images.githubusercontent.com/76589387/120200120-a656fb80-c22c-11eb-99e5-6b1414ad1ddc.png)

**Comment by JcabreraC** [comment]
There was a bug in old versions related to this. 

What version of Wazuh are you using?

**Comment by Alex989898** [comment]
Hello @JcabreraC ,

Wazuh manager ver. 4.1.5

![image](https://user-images.githubusercontent.com/76589387/120594198-44271200-c449-11eb-8d9c-aa9b15acb537.png)

**Comment by JcabreraC** [comment]
After testing, there is a bug in 4.1.5 as you wrote.

We have opened a PR and we will fix it as soon as possible.

Thank you very much for your contribution, greetings,
Juan Cabrera

**Comment by JcabreraC** [comment]
Hello @Alex989898,

This bug has already been fixed for version 4.1.5 and later. Thank you very much for your feedback, it has been very helpful to fix the bug.

Regards,
Juan Cabrera
