### ISSUE TITLE
Review spec.yaml examples for all endpoints

### ISSUE THREAD

**Issue by Espectro123** [wazuh/wazuh#8801]
|Wazuh version|Component|
|---|---|
| 4.3 | API |

## Description

Hello team,

We should check all the api examples in the spec.yaml file to see which ones are not working properly.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Espectro123** [comment]
## Issue update

### Revised endpoints

```
/active-response
/agents
/agents/{agent_id}/config/{component}/{configuration}
/agents/{agent_id}/group
```

### Affected endpoints

```
/active-response  
DELETE /agents 
GET /agents
PUT /agents
/agents/{agent_id}/config/{component}/{configuration}:

```

**Comment by Espectro123** [comment]
## Issue update

### Reviewed endpoints

```
/active-response
/agents
/agents/{agent_id}/config/{component}/{configuration}
/agents/{agent_id}/group
/agents/{agent_id}/group/is_sync
/agents/{agent_id}/group/{group_id}
/agents/{agent_id}/key
/agents/{agent_id}/restart
/agents/{agent_id}/stats/{component}
/agents/group
/agents/group/{group_id}/restart
/groups
/groups/{group_id}/agents
/groups/{group_id}/configuration
/groups/{group_id}/files
/groups/{group_id}/files/{file_name}/json
/groups/{group_id}/files/{file_name}/xml
/agents/insert
/agents/insert/quick
/agents/no_group
/agents/node/{node_id}/restart
/agents/outdated
/agents/reconnect
/agents/restart
/agents/stats/distinct
/agents/summary/os
/agents/summary/status
/ciscat/{agent_id}/results
/cluster/local/info
/cluster/nodes
/cluster/healthcheck
/cluster/status
/cluster/local/config
/cluster/api/config
/cluster/{node_id}/status
/cluster/{node_id}/info
/cluster/{node_id}/configuration

```

**Comment by Espectro123** [comment]
## Issue update

### Reviewed endpoints

```
/active-response
/agents
/agents/{agent_id}/config/{component}/{configuration}
/agents/{agent_id}/group
/agents/{agent_id}/group/is_sync
/agents/{agent_id}/group/{group_id}
/agents/{agent_id}/key
/agents/{agent_id}/restart
/agents/{agent_id}/stats/{component}
/agents/group
/agents/group/{group_id}/restart
/groups
/groups/{group_id}/agents
/groups/{group_id}/configuration
/groups/{group_id}/files
/groups/{group_id}/files/{file_name}/json
/groups/{group_id}/files/{file_name}/xml
/agents/insert
/agents/insert/quick
/agents/no_group
/agents/node/{node_id}/restart
/agents/outdated
/agents/reconnect
/agents/restart
/agents/stats/distinct
/agents/summary/os
/agents/summary/status
/ciscat/{agent_id}/results
/cluster/local/info
/cluster/nodes
/cluster/healthcheck
/cluster/status
/cluster/local/config
/cluster/api/config
/cluster/{node_id}/status
/cluster/{node_id}/info
/cluster/{node_id}/configuration
/cluster/{node_id}/stats
/cluster/{node_id}/stats/hourly
/cluster/{node_id}/stats/weekly
/cluster/{node_id}/stats/analysisd
/cluster/{node_id}/stats/remoted
/cluster/{node_id}/logs
/cluster/{node_id}/logs/summary
/cluster/restart
/cluster/configuration/validation
/lists
/lists/files/{filename}
/lists/files
/logtest
/logtest/sessions/{token}
/manager/status
/manager/info
/manager/configuration
/manager/configuration/{component}/{configuration}
/mitre/groups
/mitre/metadata
/mitre/mitigations
/mitre/references
/mitre/software
/mitre/tactics
/mitre/techniques
/rootcheck
/rootcheck/{agent_id}
/rootcheck/{agent_id}/last_scan
/rules
/rules/groups
/rules/requirement/{requirement}
/rules/files
/rules/files/{filename}
/sca/{agent_id}
/syscheck
/syscheck/{agent_id}
/syscheck/{agent_id}/last_scan
/decoders
/decoders/files
```

### Endpoints skipped

These endpoints will be reviewed after reviewing all other endpoints.

```
/groups/{group_id}/configuration
/groups/{group_id}/files/{file_name}/json
/groups/{group_id}/files/{file_name}/xml
PUT /cluster/{node_id}/configuration
/cluster/{node_id}/configuration/{component}/{configuration}
PUT /lists/files/{filename}
/sca/{agent_id}/checks/{policy_id}
```

**Comment by mcarmona99** [comment]
## Issue update


I have reviewed the rest of tests and added minor changes to the ones that were already reviewed.

I have also updated the json bodies examples and schemas by adding `type: object`. With `type: object`, some test cases in `test_agent_POST_endpoints.tavern.yaml` have been changed as the responses for requests without bodies return now a `400` code instead of a content-type error (`406` and `6002`)

Regards,
Manuel.
