### ISSUE TITLE
Exploratory deltas e2e analisysd decoder

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh#8805]
## Description
Check the current state of the deltas, based on the changes that occurred after turning off the feature in 4.2

## DoD
- [x] Test windows
- [x] Test macOS
- [x] Test linux

**Comment by konangc87** [comment]
Exploratory consisted on connecting three agents running on Windows, MacOS sierra and Ubuntu 20.04 and checking the correct synchronization of syscollector data bases between agents and server.
Inventory was manually check using kibana app Inventory Data dashboard and errors on agents and server logs were checked grepping the files with -i -E "warn|error".
