### ISSUE TITLE
Socket explanation in wazuh agent data forward 

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#882]
Hi all!
I have severa question about wazuh documentation. In wazuh documentation, in Architecture section. there is a paragraph said:

> On Unix-based operating systems, the agent runs multiple processes which communicate with each other through a local Unix domain **socket**. One of those processes is in charge of the communication and data sending to the Wazuh server. On Windows systems, there is only one agent process running multiple tasks using mutexes.

i wonder on this context, what does the "socket" word mean. And i looked at "How it works: data flow" flowchart:

https://documentation.wazuh.com/current/_images/data_flow_2048x7941.png

There is a "Socket queue" in agent flowchart. I wonder what it does mean. What kind of application that queue all of the data log to the agent daemon, is there a specific app ? or it's came from wazuh ?

And how much time did it spend for wazuh agent to forward the data collection to wazuh server ? Is there time-range ? or will it forward the data log for every certain seconds ? 

Regards

**Comment by chemamartinez** [comment]
Hi @gagantous ,

Processes that run the different components on Wazuh use Unix sockets to communicate between them, those Unix sockets are also called inter-process communication sockets (IPC socket) and as its name says, are used on Unix-based systems to send data between different processes on the same machine.

In the Unix agents case, it means that the agent daemon (the process in charge to receive the data from the different collector components and forward it to the manager) opens a read socket that receives datagrams from the rest of components, that is the described "socket queue" on the data flowchart.

Using Unix domain sockets are a standard component of POSIX, so it is not needed any specific application for their use.

In addition, the data forwarding to the manager is in real-time. When a certain event is read in the agent internal socket, it is automatically forwarded to a [leaky bucket queue](https://documentation.wazuh.com/current/user-manual/capabilities/antiflooding.html) to avoid flooding the manager and after that, to the manager.

If you have any further questions don't hesitate to ask us.

Best regards,
Chema.

**Comment by gagantous** [comment]
Hi @chemamartinez
Thanks for the reply and explanation really apreciate it!
I have another question. Sometimes when the log on certain wazuh agent produce log too fast like 1 seconds per 100 logs, the wazuh manager were late to process tge data log on that agent. Maybe it took about 1-4 minutes to catch all of the agents log. Is it what you mean by "flooding" ?

**Comment by chemamartinez** [comment]
Hi @gagantous ,

That behavior could be normal depending on numerous factors. For example, the network bandwidth, the number of events the manager is processing from other agents simultaneously and the fact that for every event received, it has to match it with every defined rule.

Anyway, the manager is designed for ingesting data in real-time. For now, it includes a receiver buffer which discards events when it is full.

In addition, new awesome features as the multithreading for the remote daemon and the analysis engine will be included in the manager in a near future, that would improve the performance of the log processing notably.

**Comment by gagantous** [comment]
Hi @chemamartinez 
Thank you for your explanation, really helpful for me
