### ISSUE TITLE
Agent duplicated when changing the IP address

### ISSUE THREAD

**Issue by djehutyy** [wazuh/wazuh#8829]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | ossec-authd | Manager/Agent | Packages | CentOS-7 |

Whenever a Client connects in VPN, or switch from wired network to WiFi (3 different VLAN's) (so the ip of the agent changes), Wazuh client changes the authentication file and so the ID of the client.

>2021/05/27 14:11:05 ossec-authd: INFO: New connection from 10.212.xx.xx
>2021/05/27 14:11:05 ossec-authd: INFO: Received request for a new agent (ITK-LP-12) from: 10.212.xx.xx
>2021/05/27 14:11:05 ossec-authd: INFO: Duplicated name 'ITK-LP-xx' (321). Removing old agent.
>2021/05/27 14:11:05 ossec-authd: INFO: Agent key generated for 'ITK-LP-12' (requested by any)
>2021/05/27 14:11:12 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
>2021/05/27 14:11:12 ossec-remoted: INFO: (1410): Reading authentication keys file.

> 2021/05/27 02:22:08 ossec-authd: INFO: New connection from 10.0.yyy.yyy
> 2021/05/27 02:22:08 ossec-authd: INFO: Received request for a new agent (itk-lp-yy) from: 10.0.yyy.yyy
> 2021/05/27 02:22:08 ossec-authd: INFO: Duplicated name 'itk-lp-yy' (356). Removing old agent.
> 2021/05/27 02:22:08 ossec-authd: INFO: Agent key generated for 'itk-lp-yy' (requested by any)
> 2021/05/27 02:22:16 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
> 2021/05/27 02:22:16 ossec-remoted: INFO: (1410): Reading authentication keys file.

This is my authd configuration in ossec.conf:

```
 <auth>
   <disabled>no</disabled>
   <port>1515</port>
   <use_source_ip>no</use_source_ip>
   <force_insert>yes</force_insert>
   <force_time>0</force_time>
   <purge>yes</purge>
   <use_password>no</use_password>
   <limit_maxagents>no</limit_maxagents>
   <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
   <!-- <ssl_agent_ca></ssl_agent_ca> -->
   <ssl_verify_host>no</ssl_verify_host>
   <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
   <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
   <ssl_auto_negotiate>no</ssl_auto_negotiate>
 </auth>
```

**Comment by pereyra-m** [comment]
Hi @djehutyy !

Your agent has the [auto-enrollment](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#enrollment) feature activated: it will request a new key to the manager if it is not already registered. 

If the IP has changed it will be considered as a new agent. But a duplicated name is found, so the previous agent is removed and a new ID is assigned to the new (in this case, the same) host.

If you check the [client.keys](https://documentation.wazuh.com/4.1/development/client-keys.html) file in the manager, you can see the IP used for every agent in the registration process. What we need is to have an "any" To avoid this situation, check the [use_source_ip](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#use-source-ip) option

**Comment by pereyra-m** [comment]
Hi @djehutyy !

Your agent has the [auto-enrollment](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#enrollment) feature activated: it will request a new key to the manager if it is not already registered. 

If the IP has changed, it will be considered as a new agent. But a duplicate name is found, so the previous agent is removed and a new ID is assigned to the new (in this case, the same) host.

If you check the [client.keys](https://documentation.wazuh.com/4.1/development/client-keys.html) file in the manager, you can see the IP used for every agent in the registration process. What we need to have is an **"any"** next to the agent's name, as you can see in this example

```
001 server1 any bb8a28997c6c3964eacb3d32308072f6661f567a41105b2b0b09f1a82331b937
```

First, check the [use_source_ip](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/client.html#use-source-ip) option in the `<client> <enrollment> `section of the agent and disable it. Then, after another successful registration, the agent will be able to communicate with the manager from any IP.

If you still have any trouble with this process, please let me know.
Regards.

**Comment by djehutyy** [comment]
Hi @pereyra-m ,
As i said, the use_source_ip is already set on NO, but hte agents still request new registration whenever they change the IP.
I checked client.keys on the manager and all agent have "any".
It looks like a bug, here a piece of client.keys:

> 173 itk-dk-07 any 2a5cc86a836c3b2a9325d1d96147f0200772f650766a8fb960d2b6ceb0bd7704
> 018 ITK-LP-02 any b21452859596f80be9b2d318e5f9acf2b1e2ba815728b0ebf3901dc1da5245f3
> 199 itk-dk-05 any 6eb0223c8a5c1a9d06b79ff706c308a11b1e3eff18e893e876513c87e55dee18
> 035 itk-dk-10 any f50478ac28e36c7ae74cfbc45881a42544143c9a3fc3260c5fbd4e3e5f1cecad
> 302 ITC-LP-01 any a8efff2902b4149be12e5cac6d719d05fb2173fd8d8874769e31b0dd73ab2e2b
> 024 itk-lp-22 any d4fe83615c503e673e9c14de599570a30cde4d21e8e5e8f322d26af7c7a0dacf
> 344 mlb-lp-02 any e5f5a227467899dd9aaf6b8a61154ccd8a80ae259f170da2d4363aee09ef3d83
> 052 itk-lp-34 any eceb8f777b4e35437da8eeccb9fadbed1e335271614bc01bc71d455ef25683a1
> 332 ITK-LP-16 any e1a41b4b7ac864422f8d4a5d5f86a29e5f69bae3eb923455fe31c5649ac751ea
> 201 itk-lp-33 any 3d0275eb8adf912f133f5c61392d9d052bf92a66cb6b6c5f652c31d616531ca6
> 300 nxt-lp-01 any f0a24f6d94bbfe47b970d0a4069c698db7cc6569ea81489e4b68a1a2a6da5d97
> 030 ITK-LP-20 any 9a8ecf09d15244ebe67a0661c8b03430f87037e1db1bc2a2c3b992736fb15be1
> 259 ITK-LP-48 any f0f01476c5fc79a4c4cc5b60b2d32f12e352240a1f96e91ca35c238b7528d133
> 284 ITK-LP-06 any dd148f65261dbef99f27ed188f86eae8f1b69b2d13e11cd8303562198937521c
> 225 ITK-LP-38 any ce1b85520b006bb3ef0cdce34b788d8d0400ed44040a942b03390df256ec9d0d
> 205 itk-dk-11 any 4f379f6b69441ffcd3f6e5bafdd0457919622e411b87ce0cbe3d423c46333c03
> 204 ITK-LP-28 any 9b8492222f9b4c4865bf22519b25b07848afc7f86978ef0fda7b64b456d5ff1e
> 350 ITK-LP-04 any 8af7b384b2b5dd73a33e3597a78a27ec6352e3d7e7aeecf938971a177c22e604
> 301 ITK-LP-26 any d2a5be5b489e1ba1b3b5043e3179ffd9e14eead7e06b400e3c15c1994c837b1d
> 352 itk-lp-13 any 77ba3b5270552e481b84a776f651fc427280c5e80adf690ca66da6852cdcabec
> 202 ITK-LP-43 any 7c8e110f611875d44abc00b0176093e7e3ac003fdfe85877845e55cf25283698
> 044 ITK-LP-30 any 5ecd6859bd7e68daafc13b8500aa2c112a33e11efa461da247cec4bcca560f64
> 196 mrf-lp-02 any 74e05810abce0dc556cbe798035e3685670cdd53db04d0f99904c799b312f659
> 351 ITC-LP-03 any 842ea250bab429f5c94992ac36bea2d23b11d9e25490bb15ec430a1c8652f4f9
> 200 ITK-LP-01 any f0d7f77465284ec842bdffc89e0cabc9ec227256196804390e99c9ed29c1a8cf
> 329 itk-lp-31 any c0a3700c93b6d3c8e09775d8c5ddda91a1bea4e7c5ac45461f6177e24c462d68
> 294 itc-lp-04 any df218395ecb7c0f9342402def8dd3381153e91bb9f97a5dda52426978fd4c1a7
> 354 ITK-LP-11 any e30f48a628b88c41fe4b14f3549d18e1566758662c97d698999054db87e57ddd

For test purposes i've already restarted clients agents and also manager without success..

**Comment by pereyra-m** [comment]
Hello again @djehutyy !

You are right, you showed the **use_source_option** in your `<auth>` section in the manager.
But I was mentioning the same option in the agent, under `<client> <enrollment>`.

Anyway, your **client.keys** shows that all agents are registered without a fixed IP (the content of this file is really sensitive information, please do not share your agents' keys).

So I think it may be a connectivity issue, or a key's file corruption: the manager has two different open ports, one of them is for communication and the other one for registration. If your agents are unable to communicate with the manager or they have an invalid key, they will request a new one, regardless they were already registered.

If this is the case, we could find in the **ossec.log** file of the agent messages similar to these ones

```
2021/05/28 14:10:05 ossec-agentd: INFO: Closing connection to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:05 ossec-agentd: INFO: Trying to connect to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:15 ossec-agentd: INFO: Closing connection to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:15 ossec-agentd: INFO: Trying to connect to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:25 ossec-agentd: INFO: Closing connection to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:25 ossec-agentd: INFO: Trying to connect to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:35 ossec-agentd: INFO: Closing connection to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:35 ossec-agentd: INFO: Trying to connect to server (192.168.0.10:1514/tcp).
2021/05/28 14:10:35 ossec-agentd: INFO: Requesting a key from server: 192.168.0.10
2021/05/28 14:10:35 ossec-agentd: INFO: No authentication password provided
2021/05/28 14:10:35 ossec-agentd: INFO: Using agent name as: ubuntu2010.localdomain
2021/05/28 14:10:35 ossec-agentd: INFO: Waiting for server reply
2021/05/28 14:10:35 ossec-agentd: INFO: Valid key received
2021/05/28 14:10:35 ossec-agentd: INFO: Waiting 20 seconds before server connection
```

Could you please provide the **ossec.log** file of the manager and agent?
Regards.

**Comment by pereyra-m** [comment]
Hi @djehutyy !

Thank you very much for the logs provided.
The manager has some important messages that are not related to this issue. For example:

```
wazuh-modulesd:vulnerability-detector: WARNING: (5575): Unavailable vulnerability data for the agent '000' OS. Skipping it.
```

This means you have to enable more feeds in your **ossec.conf** file to find vulnerabilities for all your agents.

But the next one is important, your manager sometimes fails to download the vulnerabilities database

```
2021/05/29 10:53:59 wazuh-modulesd:vulnerability-detector: WARNING: (5522): There was no valid response to 'https://nvd.nist.gov/feeds/json/cve/1.1/nvdcve-1.1-2010.meta' after '3' attempts.
2021/05/29 10:53:59 wazuh-modulesd:vulnerability-detector: WARNING: (5500): The 'National Vulnerability Database' database could not be fetched.
```

Also, the agents regularly fails to connect to the manager

```
2021/05/29 09:24:07 ossec-agent: ERROR: Connection socket: Connessione in corso interrotta forzatamente dall'host remoto. (10054)

2021/05/29 09:26:37 ossec-agent: WARNING: (1218): Unable to send message to 'server': Connessione interrotta dal software del computer host.

2021/05/29 09:27:23 ossec-agent: ERROR: Connection socket: Connessione interrotta dal software del computer host. (10053)

```

So, a connectivity issue in your environment seems to be the most reazonable cause.
Can you give me more information about the Wazuh version, the installation and registration process, and the general set up of your environment?

Here you have the meaning of the error codes we are seeing ([source](https://docs.microsoft.com/en-us/windows/win32/winsock/windows-sockets-error-codes-2)):
- **10053** WSAECONNABORTED: Software caused connection abort.
An established connection was aborted by the software in your host computer, possibly due to a data transmission time-out or protocol error.
- **10054** WSAECONNRESET: Connection reset by peer.
An existing connection was forcibly closed by the remote host. This normally results if the peer application on the remote host is suddenly stopped, the host is rebooted, the host or remote network interface is disabled, or the remote host uses a hard close (see setsockopt for more information on the SO_LINGER option on the remote socket). This error may also result if a connection was broken due to keep-alive activity detecting a failure while one or more operations are in progress. Operations that were in progress fail with WSAENETRESET. Subsequent operations fail with WSAECONNRESET.

Also, does this happen with all your agents? Or only a subset of them? Do the failing agents share something, like the same router, OS, or similar?

Regards.

**Comment by djehutyy** [comment]
Hi @pereyra-m !

So, first of all i've enabled vulnerabilities for RedHat, as the server is Centos 7. (now seems to be ok)

Second, the NVD sometimes is just not reacheable..

The OS is Centos 7 with Wazuh v4.1.5 installed from packages. 
We have different isolated subnets, but the traffic for port 1514 is enabled for and from the server everywhere.

Oten the clients are out of our network and sometimes they connect in VPN (this would explain the connectivity issues to the server). And sometimes user switch between wired and wireless connection, they are different subnets bt with the same rules.

We register the agents with the Wazuh's App command
```
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.1.5-1.msi -OutFile wazuh-agent.msi; ./wazuh-agent.msi /q WAZUH_MANAGER='serverfqdn' WAZUH_REGISTRATION_SERVER='serverfqdn' WAZUH_AGENT_GROUP='default' 
```

I am attaching you the list of registered agents and the log for agent who whom always duplicated frequently:

[agent_readded.txt](https://github.com/wazuh/wazuh/files/6575696/agent_readded.txt)
[agents.txt](https://github.com/wazuh/wazuh/files/6575697/agents.txt)
[agents_readded.log](https://github.com/wazuh/wazuh/files/6575698/agents_readded.log)

**Comment by pereyra-m** [comment]
Hello @djehutyy !

Good news about the vulnerability detector module.

Now, related to the issue, we'd like to be sure we aren't in presence of this situation: #8227. 
Basically, when the agent is unable to communicate with the server after some attempts, it checks the state of the manager before requesting a new key. But there is small time frame when the manager fails to connect but can reply anyway, and this makes the agent think it hasn't a valid key.

To be sure about this, we need the complete logs of the agent and manager, maybe of one or two days. 
You already shared a pair, but we need to check them side by side to analyze the requests and the answers. For example: your manager's log has a new key request at `01:10:57` but the agent hasn't got any information near that time.

In the meantime, if your environment has regular network changes or intermittent connections, you could disable the auto-enrollment feature by setting **enabled** to **no** in the client's [enrollment section](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/client.html?highlight=enrollment#enabled). The agent will not request a new key by it self, but you'll still receive a disconnection alert if it has been inactive for too long.

Regards.

**Comment by djehutyy** [comment]
Hi @pereyra-m !

Im currently checking if we encountered the #8227  issue as you described.

I've enabled the debug logs for the authd module. Also i will proceed to disable client enrollment.

By the way, here are some more logs. Thankyou.

[client_logs.zip](https://github.com/wazuh/wazuh/files/6590659/client_logs.zip)
[server_logs.zip](https://github.com/wazuh/wazuh/files/6590660/server_logs.zip)

**Comment by pereyra-m** [comment]
Hello again @djehutyy !

Thank you very much for the detailed information you have provided.

We can say that this environment is a bit noisy, and the connection problems are frequent. This increases the chance to fall in the mentioned small time window. We apologize for that inconvenient, and the team is already working to fix this issue. 
In the meantime, if you don't need the auto-enrollment feature, you can leave it disabled.

On the other hand, we have noticed some unusual time jumps while we were analyzing the logs. 
For example, here you can see that after a successful registration, the agent should wait 20 seconds to read the keys file, but we have 5 minutes

```
2021/06/02 18:20:51 ossec-agent: INFO: Valid key received
2021/06/02 18:20:51 ossec-agent: INFO: Waiting 20 seconds before server connection
2021/06/02 18:25:51 ossec-agent: INFO: (1410): Reading authentication keys file.
2021/06/02 18:25:51 ossec-agent: INFO: Closing connection to server (wazuh.group-itk.it/10.0.80.46:1514/tcp).
2021/06/02 18:25:51 ossec-agent: INFO: Trying to connect to server (wazuh.group-itk.it/10.0.80.46:1514/tcp).
2021/06/02 18:25:51 ossec-agent: INFO: (4102): Connected to the server (wazuh.group-itk.it/10.0.80.46:1514/tcp).
2021/06/02 18:25:51 ossec-agent: INFO: Server responded. Releasing lock.
```

Have you changed the host time/date maybe?

Regards.

**Comment by djehutyy** [comment]
Hi @pereyra-m !

The time is always the same on the Client and Server and wasn't changed.

I dont know why that noisy, if i ping the server from different subnets i never lose a packet.

I will continue monitoring the logs to see if i find something else.

Thankyou.

**Comment by pereyra-m** [comment]
Thanks to you.

Please, if you have more information, don't hesitate in write us again so we can find out what is happening in your environment.
I'll close this issue, because we already have another one related to the auto-enrollment problem.

Regards.
