### ISSUE TITLE
Wazuh manager breaks if local_rules.xml is empty

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#883]
Hello team,

If you fully clear the content from `/var/ossec/etc/rules/local_rules.xml`, this means the file exists but it is empty, then your Wazuh manager cannot start properly.

This behaviour doesn't make sense. The manager must work without the sample rule included by default under `/var/ossec/etc/rules/local_rules.xml`.

Also the error shown is weird: `OSSEC analysisd: Testing rules failed. Configuration error. Exiting.`

Thanks in advance,
Jesús

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh/pull/887 solves the issue
