### ISSUE TITLE
`/experimental/syscollector` API integration tests sometimes fail 

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#8840]
|Wazuh version|Component|
|---|---|
| >4.2.0 | API integration tests |

Hello team!

There are a few API integration tests that seem to randomly fail. They are always related to `GET /experimental/syscollector/~`. We need to assure that these tests will not fail, no matter the environment state. Logs and report from the last failed run will be attached below:

- [Report](https://github.com/wazuh/wazuh/files/6559701/Test_integration_endpoints_B830_test_experimental_endpoints.zip)
- [Logs](https://github.com/wazuh/wazuh/files/6559700/Test_integration_endpoints_B830_test_experimental_endpoints_logs.zip)

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor Fernández

**Comment by mcarmona99** [comment]
This issue is going to be closed as this same error has been reported in a more recent issue: https://github.com/wazuh/wazuh/issues/10654
