### ISSUE TITLE
Implement the unit test cases required to cover the changes in the vulnerability inventory.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#8849]
## Description

As part of epic #8727, the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. 
As a consequence of the changes introduced to address these issues:

- [Add new fields to vulnerabilities inventory database](https://github.com/wazuh/wazuh/issues/8735)
- [Modify the insert/update WDB command to add more information to vuln_cves inventory](https://github.com/wazuh/wazuh/issues/8772)
- [Adequate vulnerability detector calls and insert/update helper method to add new information to vuln_cves](https://github.com/wazuh/wazuh/issues/8773)

The following unit test cases need revision:

- `test_wdb_insert_vuln_cves_error_json`
- `test_wdb_insert_vuln_cves_error_sql_execution`
- `test_wdb_insert_vuln_cves_success`
- `test_wm_vuldet_process_agent_vulnerabilities_fill_report_nvd_cve_info_error`
- `test_wm_vuldet_process_agent_vulnerabilities_fill_report_nvd_references_error`
- `test_wm_vuldet_process_agent_vulnerabilities_fill_report_nvd_scoring_error`
- `test_wm_vuldet_process_agent_vulnerabilities_fill_report_oval_error`
- `test_wm_vuldet_process_agent_vulnerabilities_vuln_cves_insert_error`
- `test_wm_vuldet_process_agent_vulnerabilities_send_cve_report_error`
- `test_wm_vuldet_process_agent_vulnerabilities_send_cve_report_negative_version`
- `test_wm_vuldet_process_agent_vulnerabilities_send_cve_report_adding_data_from_OVAL_error`
- `test_wm_vuldet_process_agent_vulnerabilities_send_cve_report_without_errors_OVAL`
- `test_wm_vuldet_process_agent_vulnerabilities_send_cve_report_without_errors_NVD`
- `test_wm_vuldet_find_agent_vulnerabilities_agent_linux_send_agent_report_error`

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8881 was merged.
