### ISSUE TITLE
Improve DELETE /rootcheck API  request

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8852]
## Environment settings
- Agents: 10000
- Workers: 5

## Description

Hi team,

Currently, we are running performance tests on the API endpoints (the results can be seen here: https://github.com/wazuh/wazuh/issues/8325). In this issue, we will improve the DELETE /rootcheck endpoint as much as possible since this endpoint suffers some scalability problems as can be seen in the following comment: https://github.com/wazuh/wazuh/issues/8325#issuecomment-850283199.

In our tests, this endpoint results in a Timeout error. This is the API log for the request:

```
2021/05/27 10:45:50 INFO: wazuh 172.31.0.228 "PUT /syscheck" with parameters {} and body {} done in 3.045s: 200
2021/05/27 10:46:01 INFO: wazuh 172.31.0.228 "DELETE /rootcheck" with parameters {} and body {} done in 10.409s: 500
2021/05/27 10:46:01 INFO: wazuh 172.31.0.228 "POST /groups" with parameters {} and body {"group_id": "new_test_group"} done in 0.011s: 200
```

And this is the response:

```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B146_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B146_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue update

The PR related to this issue will change the `DELETE /rootcheck` endpoint to `DELETE /experimental/rootcheck`. 
This way, we won't be able to clear agents' rootcheck databases with an endpoint in the **Rootcheck** section. Due to this fact, the issue https://github.com/wazuh/wazuh/issues/8946 was opened. 

We finally decided to close that issue as the new endpoint must be added in this issue.

We must create the `DELETE /rootcheck/{agent_id}` endpoint to delete an agent's rootcheck database. This way, we will be consistent with the **Syscheck** endpoints. For syscheck, we have `DELETE /experimental/syscheck` for a list of agents and `DELETE /syscheck/{agent_id}` for an agent. Same endpoints must exist for rootcheck.

We will need to update the rootcheck RBAC and no RBAC API integration tests.

**Comment by mcarmona99** [comment]
## Issue update

After adding the endpoint to Experimental, I have seen we were using `get_agents_info()` in each loop iteration. This part can be improved as we can use `get_agents_info` just once.

```
    wdb_conn = WazuhDBConnection()
    system_agents = get_agents_info()
    for agent_id in agent_list:
        if agent_id not in system_agents:
            result.add_failed_item(id_=agent_id, error=WazuhResourceNotFound(1701))
        else:
            try:
                wdb_conn.execute(f"agent {agent_id} rootcheck delete", delete=True)
                result.affected_items.append(agent_id)
            except WazuhError as e:
                result.add_failed_item(id_=agent_id, error=e)
    --------------------------> time spent in function = 14.580518007278442 s
```

As we can see, there is a real improvement. In last build, the whole function took `time in loop + time in WazuhDBConnection = 21 s`. When using `get_agents_info` just once, we spend **6.5 seconds less**.

Despite this improvement, I will leave this endpoint in experimental, as we are testing this in an environment which is not really big (2000 agents, 1 worker) so it will be difficult for this endpoint to vertically scale. Leaving it in experimental, we are also consistent with `Syscheck`.

Regards,
Manuel.
