### ISSUE TITLE
Improve DELETE /agents API request

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8853]
## Environment settings
- Agents: 10000
- Workers: 5

## Description

Hi team,

According to the following comment https://github.com/wazuh/wazuh/issues/8325#issuecomment-850283199, the `DELETE /agents` endpoint suffers some scalability problems. This issue aims to optimize this endpoint as much as possible.

api.log:
```
2021/05/27 10:48:00 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 253, in execute_local_request
    data = await asyncio.wait_for(task, timeout=timeout)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.2.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 255, in execute_local_request
    raise exception.WazuhInternalError(3021)
wazuh.core.exception.WazuhInternalError: Error 3021 - Timeout executing API request
2021/05/27 10:48:00 INFO: wazuh 172.31.0.228 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.042s: 500
2021/05/27 10:48:10 ERROR: Timeout executing API request
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError
```

Response:

```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "master": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/api.log"
    }
  },
  "error": 3021
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

After a new revision to this endpoint, we improved its performance by a lot. In addition to the inconveniences that having all agents iterating over a loop have, the main flow broke down as follows:

- **Check agent status**

https://github.com/wazuh/wazuh/blob/f54e8e37ee03296c5bc5d323d85a1293caf10db0/framework/wazuh/agent.py#L364

We load all the agent information from DB here and then once again within the main `remove` function.

- **Check if `authd` is running**

https://github.com/wazuh/wazuh/blob/f54e8e37ee03296c5bc5d323d85a1293caf10db0/framework/wazuh/core/agent.py#L497-L498

This function reads a bunch of files to see the current status of each daemon. This was done for every agent.

- **Remove the agent using `authd`**

https://github.com/wazuh/wazuh/blob/f54e8e37ee03296c5bc5d323d85a1293caf10db0/framework/wazuh/core/agent.py#L515-L526

To remove an agent using `authd`, it is necessary to connect to the `authd` socket, send a message and close connection. 

As we can see in the following image, these steps are consuming time when they are not necessary/could be improved:

![image](https://user-images.githubusercontent.com/37274979/121930664-eb0d8700-cd42-11eb-87c7-d281d23a22f2.png)

Two main changes were done:

- Remove the outer agent status check 
- Cache the manager status

Unfortunately, there is nothing we can do to improve the part where we connect-send message-close connection with the `authd` socket, as the socket itself closes all connections after receiving one message. As it was pointed out in the comment above, we need a rework from the core team.

After these changes, we can see how the times were drastically reduced:

![image](https://user-images.githubusercontent.com/37274979/121931085-6e2edd00-cd43-11eb-9eb8-1930887e462d.png)

Regards,
Víctor
