### ISSUE TITLE
wazuh-modulesd segfault error 6

### ISSUE THREAD

**Issue by tuthan** [wazuh/wazuh#8854]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13.3 | Wazuh component | Agent | Packages | CentOS 7.9 |

There are some of our servers (20 out of 140 instances) crashed, I'm trying to investifate but log doesn't give me much info. 

Ossec log
`
2021/05/24 14:25:09 ossec-logcollector: INFO: Started (pid: 4536).
2021/05/24 14:25:10 wazuh-modulesd: INFO: Process started.
2021/05/24 14:25:10 wazuh-modulesd:syscollector: INFO: Module started.
2021/05/24 14:25:10 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2021/05/24 14:25:10 sca: INFO: Module started.
2021/05/24 14:25:10 sca: INFO: Policy '/var/ossec/ruleset/sca/cis_rhel7_linux.yml' disabled by configuration.
2021/05/24 14:25:10 sca: INFO: Loaded policy '/var/ossec/etc/shared/up-pci-dss.yml'
2021/05/24 14:25:10 wazuh-modulesd:control: INFO: Starting control thread.
2021/05/24 14:25:11 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/05/24 14:27:19 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2021/05/24 14:27:19 ossec-syscheckd: INFO: (6012): Real-time file integrity monitoring started.
2021/05/24 14:28:24 rootcheck: INFO: Ending rootcheck scan.
2021/05/24 14:33:42 ossec-logcollector: INFO: (1904): File not available, ignoring it: '/var/log/httpd/error_log'.
`
Kernel:
`
2021-05-24T14:25:25.888869+00:00 kernel: wazuh-modulesd[4727]: segfault at 7fe7ce21da3c ip 000000000040904f sp 00007fe7ce21da20 error 6 in wazuh-modulesd[400000+82000]
`

**Comment by chemamartinez** [comment]
Hi @tuthan,

Thank you for reporting this issue.

It would be very helpful for us to discover the cause of these crashes if you provide us the following information.

- All the agents you have detected that crashed are the same OS? Which is the exact OS? could you run the command `uname -a` in one of them?

- Were they working fine until they crashed? If so, do they belong to the same group? and for that group, have you applied any shared configuration that could change the operation of them at the same time? for example, I see they are running a custom SCA policy (`/var/ossec/etc/shared/up-pci-dss.yml`).

- Focusing on one of the agents to simplify the debugging process, is the issue 100% reproducible? In other words, if you restart one of the crashed agents, is it falling down again?

- In one of the issued agents, could you follow these steps?

1. Turn on the debug mode for `wazuh-modulesd`
```
# echo "wazuh_modules.debug=2" >> /var/ossec/etc/local_internal_options.conf
```
2. Restart the agent
```
# /var/ossec/bin/ossec-control restart
```
3. Send us the logs written at the `ossec.log` file to track down the component behavior.
```
# cat /var/ossec/logs/ossec.log | grep "wazuh-modulesd" >> crash_log.txt
```

Thank you again for your help! Looking forward to hearing from you.

Best regards,
Chema.

**Comment by tuthan** [comment]
Thanks for prompt answer and sorry for delay. 
- uname -a: Linux 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- They are crash when wazuh-agent started and only affect wazuh-modulesd. The other component of wazuh-agent still running.
`
wazuh-agent.service - Wazuh agent
   Loaded: loaded (/etc/systemd/system/wazuh-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since T2 2021-05-24 14:24:25 UTC; 1 weeks 1 days ago
   CGroup: /system.slice/wazuh-agent.service
           ├─4042 /var/ossec/bin/ossec-execd
           ├─4223 /var/ossec/bin/ossec-agentd
           ├─4404 /var/ossec/bin/ossec-syscheckd
           └─4536 /var/ossec/bin/ossec-logcollector
--> Missing wazuh-modulesd as it crashed
`
- Will try to arrange to see if it reproducible and turn on debug mode for more info and get back

**Comment by chemamartinez** [comment]
In addition, could you run the following command to ensure the `wazuh-modulesd` you have installed in the issued agent is the same as mine?

```
# shasum /var/ossec/bin/wazuh-modulesd
df17df9c29bb85da5dc2853774756cffe2eed4fc  /var/ossec/bin/wazuh-modulesd
```

Thanks!

**Comment by tuthan** [comment]
(sorry for delay -  I'm not having permission to change config will causing some delay)
- I was picked a test node with agent 3.13.1 to debug and matched your shasum. After set <processes>no</processes> we can confirm that wazuh-modulesd can start without issue
- We going to rebuild and redeploy this node with latest agent.
- Issue still persist with other nodes with 3.13.3 agents

**Comment by chemamartinez** [comment]
Hi @tuthan,

It could be very useful for us to find out the problem if you follow these steps to debug the error in one of your issued agents:

```
# 1. Install dependencies
yum install gdb gcc make git libtool automake autoconf curl

# 2. Checkout and build Wazuh from sources
git clone https://github.com/wazuh/wazuh<http://github.com/wazuh/wazuh> -b v3.13.3 --depth 1
cd wazuh/src
make deps
make TARGET=agent DEBUG=yes -j2

# 3. Run the newly built Modulesd
pkill wazuh-modulesd
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/lib
./wazuh-modulesd
sleep 1

# 4. Set traps with GDB and save coredump
nohup gdb -p $(pidof wazuh-modulesd) -batch \
-ex 'handle SIGPIPE nostop' \
-ex continue \
-ex 'generate-core-file wazuh-modulesd.coredump' \
-ex 'info thread' \
-ex 'bt' &
```

After that, the GDB program is in background waiting for any unexpected exit of the `wazuh-modulesd` process. If that happens, in the directory where you called GDB the following two files are generated:
- `nohup.out`
- `wazuh-modulesd.coredump`

It could be great if you follow that process and send us the generated files.

Thank you again!

**Comment by tuthan** [comment]
Hi @chemamartinez, Thanks for all the support. We finally found the issue. It was a memory limit set in wazuh-agent.service set to 100mb and causing wazuh-modulesd exit since its not enough memroy to start. We since then increase the litmit and everything working now.
