### ISSUE TITLE
Improve PUT /syscheck API request

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#8867]
## Environment settings
- Agents: 50000
- Workers: 5

## Description

Hi team,

Continuing with the tests of the issue https://github.com/wazuh/wazuh/issues/8325, we have detected a scalability problem with the `PUT /syscheck` endpoint. 

As in the case of PUT /rootcheck, the problem has occurred with 50000 agents. We have verified that with 10000 and 25000 agents this problem does not arise, so this endpoint returns a valid response in less than 10 seconds in these cases.

The goal of this issue is to improve as much as possible this endpoint. Here we can see the api.log file for this request and its response:

#### api.log
```
2021/05/31 16:01:50 INFO: wazuh 172.31.80.61 "PUT /rootcheck" with parameters {} and body {} done in 15.291s: 500
2021/05/31 16:02:08 INFO: wazuh 172.31.80.61 "PUT /syscheck" with parameters {} and body {} done in 18.297s: 500
2021/05/31 16:02:08 INFO: wazuh 172.31.80.61 "POST /groups" with parameters {} and body {"group_id": "new_test_group"} done in 0.009s: 200
```

#### Response
```
{
  "title": "Wazuh Internal Error",
  "detail": "Timeout executing API request",
  "dapi_errors": {
    "Test_cluster_performance_B162_manager_2": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_1": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_5": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_4": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    },
    "Test_cluster_performance_B162_manager_3": {
      "error": "Timeout executing API request",
      "logfile": "WAZUH_HOME/logs/cluster.log"
    }
  },
  "error": 3021
}
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by mcarmona99** [comment]
## Issue status

As Adri said here: https://github.com/wazuh/wazuh/issues/8865#issuecomment-860608909, the slowest part of our code is  the generation of the Agent object and the extraction of its information from the database.

**Comment by mcarmona99** [comment]
## Issue status

We have added more improvements to this code and the rootcheck related framework code to avoid using `load_info_from_db` as it is the slowest part of our code.

Now we are using a WazuhDBQuery to get agents with `status!= active` and add them to the `failed_items`, before entering the for loop.
