### ISSUE TITLE
Make RAM usage customizable in the `api.yaml`

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#8868]
|Wazuh version|Component|
|---|---|
| master | API/Framework |

## Description

Hello team,

In a similar way to the API timeout configuration proposed in #8799, and according to the conclusions that come out of the investigation in #8876, a configuration should be implemented to allow setting a maximum amount of RAM that the API process can use. 

The idea is that the user can set an amount of RAM (eg 10MB) for the API process. If any response to a request makes the API exceeds this amount, an error message should be returned as happens when the default timeout is exceeded. The request should be canceled and the memory released too. 

This way, it could be combined (or not) with the timeout so that requests are canceled when certain conditions are given: 
- **Timeout + Max RAM:** Request is canceled when either of these two things happens before (timeout or exceeded RAM usage)
- **Only timeout:** Current behavior. The request is canceled only if the timeout is exceeded.
- **Only max RAM:** Request is canceled if the response exceeds the maximum size allowed, regardless of the time required for it. 

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)
- [ ] **New integration tests** without failures for API configuration (`/wazuh-qa/tests/integration/test_api/test_config/`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Selu.

**Comment by davidjiglesias** [comment]
To be done in #9055
