### ISSUE TITLE
MITRE endpoints can't sort by `references.external_id`

### ISSUE THREAD

**Issue by frankeros** [wazuh/wazuh#8879]
|Wazuh version|Component|
|---|---|
| 4.3.x | API |

| Related to | #7819 |
|---|---|

**Description**

The Wazuh Kibana App needs to sort the MITRE endpoints by the `external_id` field that is included in the references.
This field that is important for the users is the `public` ID for the MITRE resources.
Maybe it should be included in the main object.

![image](https://user-images.githubusercontent.com/26828184/120344371-e7ecb280-c2cf-11eb-9c2e-b79229219122.png)
![image](https://user-images.githubusercontent.com/26828184/120343600-3cdbf900-c2cf-11eb-81e7-953e0e63ca34.png)

**Comment by davidjiglesias** [comment]
We have decided to move `source`, `url` and `external_id` to the exterior level of the response for all MITRE endpoints.

**Comment by mcarmona99** [comment]
## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
