### ISSUE TITLE
Addition of detection timestamp, severity, and score to the CVEs alerts inventory - Exploratory testing

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#8882]
As part of epic #8727, the CVEs alerts inventory of the Vulnerability Detector module should be enhanced by adding more information that would be relevant for the users. Having said that, exploratory testing should be done over the full implementation of the epic.

This issue will be closed with a report of each of the participants of the exploratory testing, giving details of the findings as well as the fixes implemented if necessary

**Comment by MiguelazoDS** [comment]
### Exploratory testing results
#### Environment 
- Manager: Centos8
- Agent 1: Ubuntu Bionic
- Agent 2: Windows Server 2019
![2021-06-02_14-23](https://user-images.githubusercontent.com/13010397/120539125-adf9da00-c3bd-11eb-8b6d-024554ad08d8.png)


#### Steps
- Installing Wazuh 4.3 (dev-8727-cves-inventory-improvements) on Centos8
- Enabling Vulnerability detector with interval = 1m for RedHat 
- Checking the vulnerabilities inventory we can see the fields `detection_time`, `severity`, `cvss2_score` and `cvss3_score`:
![2021-06-02_13-57](https://user-images.githubusercontent.com/13010397/120539063-9d496400-c3bd-11eb-99cf-189e0ecdb9d9.png)
- Registering an Ubuntu agent with Wazuh 4.1.5 (Package installation)
![2021-06-02_14-21](https://user-images.githubusercontent.com/13010397/120539215-c9fd7b80-c3bd-11eb-93d3-a5e312e7dc6a.png)
- Registering a new Windows agent with Wazuh 4.1.5 (Package installation)
![2021-06-02_14-26](https://user-images.githubusercontent.com/13010397/120539513-092bcc80-c3be-11eb-9722-3af93e91d2fc.png)

#### Issues
- As a result of the changes introduced related to this epic, there was missing information about the new parameters.
- We found that in case of a package update the status is not sent back and that would cause an error since the vulnerability detector module expects to receive the status information.
- As a consequence of the previous finding, the UTs were revised and both changes are including here https://github.com/wazuh/wazuh/pull/8889
- A revision should be performed as well for [#1407](https://github.com/wazuh/wazuh-qa/pull/1407)

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8889 was merged.
