### ISSUE TITLE
Auditd decoder not picking up file/directory changes

### ISSUE THREAD

**Issue by jamesspi** [wazuh/wazuh#89]
Hi,

I'm trying to utilize the auditd ruleset, primarily to detect file/directory modifications. For some reason, these events are not being alerted on.

Audit configuration changes seem to be working as expected.

Example audit log entry:

type=PATH msg=audit(1489663026.877:669510): item=1 name="secretfile.txt" inode=871286 dev=fd:01 mode=0100775 ouid=1003 ogid=1003 rdev=00:00 obj=unconfined_u:object_r:user_home_t:s0 objtype=DELETE

Thanks,
James

**Comment by snaow** [comment]
Hi @jamesspi,

Thanks for your feedback, let me try to help here.

What Wazuh version are you running?
Next Wazuh 2.0 release will include a new out-of-the-box way to monitor file system calls using Auditd, we created a new "localfile" type to group same Auditd ID events, analyzing if there is a file change.

You could check the documentation we are currently creating about it:
> https://documentation-dev.wazuh.com/user-manual/system-calls-monitoring/index.html

The agent configuration will look like:
 
```
<localfile>
 <log_format>audit</log_format>
  <location>/var/log/audit/audit.log</location>
</localfile>
```

An example of Auditd event (using dynamic fields, for extracting EVERY field!):

```
** Alert 1487891161.28457: - audit,audit_watch_write,audit_watch_create,
2017 Feb 23 15:06:01 localhost->/var/log/audit/audit.log
Rule: 80790 (level 3) -> 'Audit: Created: /home/malware.py'
type=SYSCALL msg=audit(1487891161.190:2942): arch=c000003e syscall=2 success=yes exit=3 a0=7ffce677b7b7
a1=941 a2=1b6 a3=7ffce6779690 items=2 ppid=60621 pid=60761 auid=1000 uid=0 gid=0 euid=0 suid=0
fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=346 comm="touch" exe="/usr/bin/touch"
subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="audit-wazuh-w" type=CWD
msg=audit(1487891161.190:2942):  cwd="/" type=PATH msg=audit(1487891161.190:2942): item=0
name="/home/" inode=16777403 dev=fd:00 mode=040755 ouid=0 ogid=0 rdev=00:00
obj=system_u:object_r:home_root_t:s0 objtype=PARENT type=PATH msg=audit(1487891161.190:2942):item=1
name="/home/malware.py" inode=18369115 dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00
obj=unconfined_u:object_r:home_root_t:s0 objtype=CREATE
audit.type: SYSCALL
audit.id: 2942
audit.syscall: 2
audit.success: yes
audit.exit: 3
audit.ppid: 60621
audit.pid: 60761
audit.auid: 1000
audit.uid: 0
audit.gid: 0
audit.euid: 0
audit.suid: 0
audit.fsuid: 0
audit.egid: 0
audit.sgid: 0
audit.fsgid: 0
audit.tty: pts0
audit.session: 346
audit.command: touch
audit.exe: /usr/bin/touch
audit.key: audit-wazuh-w
audit.cwd: /
audit.directory.name: /home/
audit.directory.inode: 16777403
audit.directory.mode: 040755
audit.file.name: /home/malware.py
audit.file.inode: 18369115
audit.file.mode: 0100644
```

If you are using Wazuh version 1.1.1, there is no valid decoders/rules for "type=PATH" events, still you could increase level of the only rule that could match:

https://github.com/wazuh/wazuh-ruleset/blob/v1.09/rules-decoders/ossec/rules/auditd_rules.xml#L224-L230

Hope it helps, regards,
Pedro 'snaow' Sanchez.

**Comment by jamesspi** [comment]
Hi @Pedro

I am indeed using version 2.0. Some audit fields are being extracted, but not all, as you have listed below. 

Thanks,
James

**Comment by snaow** [comment]
Great! If you are already on Wazuh 2.0, please take a look into the documentation link I sent you.
I can not see on your log sample any records of "audit-wazuh-w" key, which is used by the decoders and rules for generating the alerts.

You will need to configure audit-keys on your agents host:

```
auditctl -w /home -p w -k audit-wazuh-w
auditctl -w /home -p a -k audit-wazuh-a
auditctl -w /home -p r -k audit-wazuh-r
auditctl -w /home -p x -k audit-wazuh-x
```

An example of Auditd file change on my environment:
```
type=SYSCALL msg=audit(1489668229.813:38024): arch=c000003e syscall=2 success=yes exit=3 a0=11da730 a1=241 a2=1a4 a3=0 items=2 ppid=23887 pid=23907 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=3140 comm="vi" exe="/usr/bin/vi" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key="audit-wazuh-w"
type=CWD msg=audit(1489668229.813:38024):  cwd="/opt/ossec_test"
type=PATH msg=audit(1489668229.813:38024): item=0 name="/opt/ossec_test" inode=20971640 dev=ca:02 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:usr_t:s0 objtype=PARENT
type=PATH msg=audit(1489668229.813:38024): item=1 name="file_james" inode=20971641 dev=ca:02 mode=0100644 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:usr_t:s0 objtype=CREATE
```

How it looks once its grouped on OSSEC:
`type=SYSCALL msg=audit(1489668229.813:38024): arch=c000003e syscall=2 success=yes exit=3 a0=11da730 a1=241 a2=1a4 a3=0 items=2 ppid=23887 pid=23907 auid=0 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=3140 comm=\"vi\" exe=\"/usr/bin/vi\" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=\"audit-wazuh-w\" type=CWD msg=audit(1489668229.813:38024):  cwd=\"/opt/ossec_test\" type=PATH msg=audit(1489668229.813:38024): item=0 name=\"/opt/ossec_test\" inode=20971640 dev=ca:02 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:usr_t:s0 objtype=PARENT type=PATH msg=audit(1489668229.813:38024): item=1 name=\"file_james\" inode=20971641 dev=ca:02 mode=0100644 ouid=0 ogid=0 rdev=00:00 obj=unconfined_u:object_r:usr_t:s0 objtype=CREATE"`

In JSON output:

```
{
  "timestamp": "2017-03-16T05:43:33-0700",
  "rule": {
    "level": 3,
    "description": "Audit: Created: file_james",
.
.
.
  "audit": {
    "type": "SYSCALL",
    "id": "38024",
    "syscall": "2",
    "success": "yes",
    "exit": "3",
    "ppid": "23887",
    "pid": "23907",
    "auid": "0",
    "uid": "0",
    "gid": "0",
    "euid": "0",
    "suid": "0",
    "fsuid": "0",
    "egid": "0",
    "sgid": "0",
    "fsgid": "0",
    "tty": "pts0",
    "session": "3140",
    "command": "vi",
    "exe": "/usr/bin/vi",
    "key": "audit-wazuh-w",
    "cwd": "/opt/ossec_test",
    "directory": {
      "name": "/opt/ossec_test",
      "inode": "20971640",
      "mode": "040755"
    },
    "file": {
      "name": "file_james",
      "inode": "20971641",
      "mode": "0100644"
.
.
.
}
```

Keep in mind we are still improving everything, I am aware there are some cases (different OS's/environments) where Auditd is not sending the full "file name" on "Write access" events, it is only sending the CWD.

Please come back with any more doubts if you need it, I would love to see this functionality working on your environment.

Regards,
Pedro.

**Comment by jamesspi** [comment]
Ah ok, I wasn't using wazuh keys in my rules!

Thanks for this,
James
