### ISSUE TITLE
The CA store for WPK only accepts the first stanza

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#890]
This is a valid configuration for multiple CA stores to verify WPK packages:

```xml
<active-response>
  <disabled>no</disabled>
  <ca_store>/var/ossec/etc/my_ca_root.pem</ca_store>
  <ca_store>/var/ossec/etc/wpk_root.pem</ca_store>
</active-response>
```

However, only the first stanza applies in the configuration.

**Comment by branchnetconsulting** [comment]
Victor, thanks for opening this issue for me.  Definitely only the first reference to <ca_store> is getting honored.  If I make my personal pem file the first in the list, I can only push my own custom wpk packages to the agent and cannot push stock Wazuh WPKs.  If I put wpk_root first in the list I can push stock Wazuh WPKs but cannot push my custom WPKs.  In both cases when it fails the error reported is: "Error 1716: Error upgrading agent: Could not verify signature"

Kevin

**Comment by chemamartinez** [comment]
Done at #927
