### ISSUE TITLE
Wazuh AWS Module - No Results found

### ISSUE THREAD

**Issue by muddiwaller** [wazuh/wazuh#8925]
Hello,

I have integrated AWS Cloudtrail bucket with using AWS s3 bucket woodle.

I am getting all the logs related to IAM and EC2 but not able to populate visualizations of "accounts" and "Regions" 
in the default dashboard of Wazuh's AWS module.

![n7](https://user-images.githubusercontent.com/85558203/121178231-b8ade680-c877-11eb-9300-69130f4ff8c3.JPG)

Any suggestions to resolve this.

Regards
Muddi.

**Comment by CarlosRS9** [comment]
Hello,

Sorry for the late response. I'm afraid this is a known issue we have. We are still working on it.

However, it is possible to apply a workaround to avoid this issue and populate these fields. The solution would be to normalise the fields you mentioned in your Wazuh manager using Filebeat. Here are the steps you need to follow in case you want to apply this workaround:

1. Backup the following files:
```
/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json
/usr/share/filebeat/module/wazuh/archives/ingest/pipeline.json
```

2. Locate the line `{ "json" : { "field" : "message", "add_to_root": true } },` at the beginning of the file `/usr/share/filebeat/module/wazuh/alerts/ingest/pipeline.json` and add the following lines below it:

```
    {
      "set": {
        "field": "data.aws.region",
        "value": "{{data.aws.awsRegion}}",
        "override": false,
        "ignore_failure": true
      }
    },
    {
      "set": {
        "field": "data.aws.accountId",
        "value": "{{data.aws.aws_account_id}}",
        "override": false,
        "ignore_failure": true
      }
    },
```

The result should look like this:
```
{
  "description": "Wazuh alerts pipeline",
  "processors": [
    { "json" : { "field" : "message", "add_to_root": true } },
    {
      "set": {
        "field": "data.aws.region",
        "value": "{{data.aws.awsRegion}}",
        "override": false,
        "ignore_failure": true
      }
    },
    {
      "set": {
        "field": "data.aws.accountId",
        "value": "{{data.aws.aws_account_id}}",
        "override": false,
        "ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.srcip",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }

```

3. Repeat the operation, this time for the `/usr/share/filebeat/module/wazuh/archives/ingest/pipeline.json` file. It should look something like this:

```
{
  "description": "Wazuh events pipeline",
  "processors": [
    { "json" : { "field" : "message", "add_to_root": true } },
    {
      "set": {
        "field": "data.aws.region",
        "value": "{{data.aws.awsRegion}}",
        "override": false,
        "ignore_failure": true
      }
    },
    {
      "set": {
        "field": "data.aws.accountId",
        "value": "{{data.aws.aws_account_id}}",
        "override": false,
        "ignore_failure": true
      }
    },
    {
      "geoip": {
        "field": "data.srcip",
        "target_field": "GeoLocation",
        "properties": ["city_name", "country_name", "region_name", "location"],
        "ignore_missing": true,
        "ignore_failure": true
      }

```

4. Run the following command:

```
filebeat setup --pipelines
```



From now on the alerts should correctly populate the region and accountID fields.

I hope this helps and sorry for the inconvenience.

Regards.

**Comment by muddiwaller** [comment]
@CarlosRS9 Thanks a million.

It worked like a charm.

Thank you.
