### ISSUE TITLE
What is agent limit of per wazuh manager

### ISSUE THREAD

**Issue by gyanprakashsahu** [wazuh/wazuh#893]
Hi,

Any limit of adding Wazuh agent ?
I have added 516 agent only where i am using cluster.

**I am using simple method for adding result.**
### Example:

 you can create a self-signed certificate:

(Manager)

# openssl req -x509 -batch -nodes -days 365 -newkey rsa:2048 -keyout /var/ossec/etc/sslmanager.key -out /var/ossec/etc/sslmanager.cert

(Manager)

# /var/ossec/bin/ossec-authd
Run the auth client on the agent. You must enter the authd server’s IP address, like this:

# /var/ossec/bin/agent-auth -m 192.168.1.2

**It was working but suddenly stop adding agent and giving below error --**

[root@in-web-v3-2 ~]# /var/ossec/bin/agent-auth -m 192.168.1.2
2018/07/04 12:18:40 agent-auth: INFO: Started (pid: 26406).
INFO: Using password specified on file: /var/ossec/etc/authd.pass
INFO: Connected to 192.168.1.2:1515
INFO: Using agent name as: xyz.com
INFO: Send request to manager. Waiting for reply.
ERROR: Unable to create key. Either wrong password or connection not accepted by the manager.
INFO: Connection closed.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

The agent limit in Wazuh 3.2 is 14000 per manager. You can change this limit if you compile wazuh from the sources like this:
`#make TARGET=server MAXAGENTS=YOUR_VALUE`

Now as for the problem that you have: 
`INFO: Using password specified on file: /var/ossec/etc/authd.pass`

You need to specify the password when you register the agent:
` /var/ossec/bin/agent-auth -m 192.168.1.2 -P YOUR_PASSWORD`

And the agent will be registered.

Best regards.

**Comment by gyanprakashsahu** [comment]
Hi @TJOSERAFAEL ,

**Still same error**..

But i have able to add new agents yesterday but suddenly stop working.

**Comment by TJOSERAFAEL** [comment]
Hi @gyanprakashsahu,

can you please run the following commands on the **manager**:
`#pkill -f authd`
And :
`#/var/ossec/bin/ossec-authd`

Then on the **agent**:
`#/var/ossec/bin/agent-auth -m 192.168.1.2`

If it does not work, please tell me what operating system are you using for both, _agents and manager_.

Best regards.

**Comment by TJOSERAFAEL** [comment]
Lets close this issue, if you have any problems you can re-open it.
