### ISSUE TITLE
Two agents with the same name or IP remove each other the keys using enrollment

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#8940]
|Wazuh version|Component|Install type|
|---|---|---|
| 4.0.0 | Enrollment | Agent | 

The force option of Authd is enabled for every agent by default (**force_insert=yes**  and **force_time=0**)
This makes that if an agent having the same name or IP of a previously registered agent requests a key, Authd will eliminate the old agent to register the new one.
With enrollment, the key request is automatic, and an agent that is removed from the manager (and fails on communicating) will finally request a new key. This lead to remove the last added agent. Having both agents enrollment enabled leads to a loop where each agent removes the other.

**Comment by palaciosjeremias** [comment]
### **Fix proposals:**
- Modify the default  value of the **force** option:
Changing **force_time** to a value greater than the **notify_time** of the agent makes no key request to remove an agent active in the manager. It will only remove disconnected agents.
**Note:** Since the agent's connection status is saved in **global.db**, this force option could be improved to not work with the antiquity of the agent and a time, it can work using the connection status of the agent agents that is more clear.
This is a very small change without error risk. But it only works if the manager and the agents are actively running and communicating.
It can lead to problems during the restart of a manager.
- Add a type to the registration command
Authd can be improved to handle a new flag to the command, by default, if no flag is configured, Authd will work like **normal**, accepting the registration attempt. But, two options can be specified to this flag:
**no_key_enrollment** used when the agent starts without keys and request a new one using enrollment
**communication_error_enrollment** used when the agent has keys but the communication fails and asks for new ones.
Authd can identify these three different scenarios and be configured to reject or accept the key request only for desired types of registration.
This is a middle-small change, with low error risk.gen de error.

**Comment by DProvinciani** [comment]
Having implemented and merged the next epics:

- https://github.com/wazuh/wazuh/issues/9549
- https://github.com/wazuh/wazuh/issues/9550

This is fixed and we close this issue.
