### ISSUE TITLE
Remove CloudWatchLogs log stream limit

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh#8960]
|Component|
|---|
| AWS-S3 module |

Hello team,

Currently our AWS module is compatible with `CloudWatchLogs`. However, it has one limitation regarding the log streams. If a user has more than 50 log streams within a single log group our module will extract logs from the first 50 log streams only, ignoring the rest. This is due to the limit imposed by the `describe_log_streams` function of the AWS API that we use to access the log streams.

We should update our integration with CloudWatchLogs to ensure get every log streams available for each log group, even if there are more than 50 log streams available.

**Comment by venkat330** [comment]
https://github.com/jorgebastida/awslogs/blob/0886184d72acb57dfde6020fad41ec908a32806e/awslogs/core.py#L54

**Comment by mcarmona99** [comment]
## Issue update

The solution should be implemented using the `nextToken` parameter of the function `describe_log_streams`.

With the following line:

```
response = self.client.describe_log_streams(logGroupName=log_group)
```

The response obtained has the following structure:

```
{
    'logStreams': [
        {
            'logStreamName': 'string',
            'creationTime': 123,
            'firstEventTimestamp': 123,
            'lastEventTimestamp': 123,
            'lastIngestionTime': 123,
            'uploadSequenceToken': 'string',
            'arn': 'string',
            'storedBytes': 123
        },
    ],
    'nextToken': 'string'
}
```

The `nextToken` key indicates the token for the next set of items to return. The token expires after 24 hours.

We should implement the following:

```
- Take the logStreams with the describe_log_streams function (without indicating a token) and save them in a list L. Save nextToken.
- While nextToken is not None
  - Take the logStreams with parameter nextToken equal to nextToken.
  - Extend the list L with the logStreams obtained in the new response.
  - Update nextToken with the new token obtained.
```

### Reference:

`describe_log_streams(**kwargs)`

**Request Syntax**

```
response = client.describe_log_streams(
    logGroupName='string',
    logStreamNamePrefix='string',
    orderBy='LogStreamName'|'LastEventTime',
    descending=True|False,
    nextToken='string',
    limit=123
)
```

**Parameters**

- `logGroupName` (string) -- [REQUIRED] The name of the log group.

- ...

- `nextToken` (string) -- The token for the next set of items to return. (You received this token from a previous call.)
