### ISSUE TITLE
Change `agent_list` parameter to positional in controller functions using `all` keyword

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#8962]
|Wazuh version|Component|
|---|---|
| master | API |

Hi team,

Right now, we are defining functions in the API controllers with all the parameters as non-positional. For example, the `delete_agents` funcion in `agent_controller.py`:

https://github.com/wazuh/wazuh/blob/7e39b5ff5f977d870301a253d9ab47fa8a767851/api/api/controllers/agent_controller.py#L27-L100

We must check the `agent_list` parameter and change it to positional when we are using the `agents_list_all` parameter in the spec. It needs to be positional as this parameter is used when the `all` keyword must be specified to do the corresponding action for all resources, in other words, it is a required parameter (it can't be `None`).

For instance, in `delete_agents`, `agents_list` will never be `None` as there will be an error with the spec (required param).

Also check API integration tests.

The functions we need to check are the following:
- `agent_controller.delete_agents`
- `agent_controller.delete_multiple_agent_single_group`
- `experimental_controller.clear_syscheck_database`
- `experimental_controller.clear_rootcheck_database` (after merging https://github.com/wazuh/wazuh/pull/8945)

Check typing too.

Regards,
Manuel.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
Finally, this solution is not necessary
