### ISSUE TITLE
Vulnerability detector is not correctly propagating some packages fields through the whole scan

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#8971]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3| Vulnerability Detector | Manager | Packages/Sources | - |

### Description

During the IT stabilization [#1261](https://github.com/wazuh/wazuh-qa/issues/1261) for the epic #7749, it was found that the Arch Linux queries used for the vulnerabilities detector scan where incomplete.
The `REFERENCE` and `TYPE` fields are missing, and also, these null pointers create a segmentation fault during the scan.

These fields and the proper sanity checks should be added.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/8973 was merged.
