### ISSUE TITLE
Debian and RPM packages

### ISSUE THREAD

**Issue by salyh** [wazuh/wazuh#90]
I'd like to build Debian and RPM packages from the master branch (currently for agents only). I found something for Debian (https://github.com/wazuh/wazuh/tree/master/contrib/debian-packages) which seems outdated and nothing for RPM. Can you give me a hint?

**Comment by jlruizmlg** [comment]
Hello Saly

Our plans is release the specs and debian_files next week in our
repositories.

Regards
-----------------------
Jose Luis Ruiz
Wazuh Inc.
jose@wazuh.com

**Comment by gregdurham** [comment]
Hello, is there any update for this ticket? Looking to build an RPM for the latest off master.

**Comment by jlruizmlg** [comment]
Hello @salyh and @gregdurham we have a new repository with the debian files and rpm spec in order create Wazuh packages.

https://github.com/wazuh/wazuh-packages
