### ISSUE TITLE
sca typo in cis_debian10.yml - rule id: 2507

### ISSUE THREAD

**Issue by fraform-tnz** [wazuh/wazuh#9010]
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.1.5-1| SCA | Error |

## Description

In rules cis_debian10.yml - rule id: 2507 (title: "Ensure /tmp is configured") in remediation example section there is a typo:

`"tmpfs  /tmp  tmpfs defaults,rw,nosuid,nodev,noexec,realtime  0 0" `

but it should be 

`
"tmpfs  /tmp  tmpfs defaults,rw,nosuid,nodev,noexec,relatime  0 0" `

(this typo is present also in other disabled file: cis_debian9.yml.disabled - id: 2005, cis_rhel8_linux.yml.disabled - id: 5004, cis_centos8_linux.yml.disabled - id: 6504)

**Comment by chemamartinez** [comment]
Hi @fraform-tnz,

Thank you for reporting it.

I've already merged a pull request to fix the typo in the master branch. https://github.com/wazuh/wazuh/pull/9051

Don't hesitate to contact us with any other concerns.

Best regards.

**Comment by fraform-tnz** [comment]
Thank you all for your work and effort :)
