### ISSUE TITLE
Is there any example active-response/script for linux malware ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#902]
Hi Wazuh!
I would like to know if anyone ever make this active-response with some script that would handle some malware... I would like to learn that, necause i dont know how to make one myself, i need some example, i am not familiar with bash.

Does anyone ever tried this ?

Regards
Fathin

**Comment by crolopez** [comment]
Hi @gagantous,

You can use [Virustotal integration](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/index.html) to detect malware and move it to quarantine or remove it.

Unfortunately, active-response does not currently have the ability to use all alert fields, so it is not possible to interact with malicious files from scripts at this time.

However, we are working on improving active-response and this functionality will be added in a future release. You can see a summary of these improvements here: https://github.com/wazuh/wazuh/issues/1116

Best regards.
