### ISSUE TITLE
report_changes merging disks with same path

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#904]
If we have the same path in different disks on Windows they're merged in the diff folder.

Example:

We have two folders with the option `report_changes="yes"`

`C:\User\my_dir` with only one file named `sample.txt`
`F:\User\my_dir` with only one file named `sample.txt`

This makes the only file reported is the last one defined in the `ossec.conf` file.

**Comment by Molter73** [comment]
Closing this issue since it has already been fixed in version 3.12.
