### ISSUE TITLE
The order of directories tag in the configuration influences the expected behaviour

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh#906]
As said, the order influences the result.

Example:
```
<directories check_all="yes" report_changes="yes">/path/to/parent</directories>
<directories check_all="yes" report_changes="no">/path/to/parent/child</directories>
```
The expected result is to have reported all the content of parent except the `child` folder.

However, this ignore the `report_changes="no"` of the child folder and report it as well.

But if we change the order as seen below, we have the expected behaviour.
```
<directories check_all="yes" report_changes="no">/path/to/parent/child</directories>
<directories check_all="yes" report_changes="yes">/path/to/parent</directories>
```

**Comment by Zenidd** [comment]
Hello,

I'm closing this ticket as this issue has been solved in the PR https://github.com/wazuh/wazuh/pull/3601

Greetings, JP Sáez
