### ISSUE TITLE
Wazuh-modulesd segfault error 4

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#9070]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Modulesd | Manager | Packages | SLES 15|

Hello team,

In a cluster environment (2 managers) with Wazuh version 4.1.5. The following appears when accessing to the Wazuh APP:

![image](https://user-images.githubusercontent.com/73501120/122769035-94d8a080-d27a-11eb-8d1b-16f8dc60303e.png)

By restarting the managers, the problem is solved. But after a period of time it happens again.

Checking one of the manager nodes, it is identified that modulesd crashes:

![image](https://user-images.githubusercontent.com/73501120/122769237-c81b2f80-d27a-11eb-8c88-7423089cdcb3.png)

Checking the logs of this manager, the following segfaults are identified:

![image](https://user-images.githubusercontent.com/73501120/122770080-7b842400-d27b-11eb-9101-c1bc7fd364d7.png)

Taking as a reference one of the segfault, specifically the one at 11:16 at that time, what the ossec.log tells us is that it is performing a VDT scan:
![image](https://user-images.githubusercontent.com/73501120/122770943-55ab4f00-d27c-11eb-8e83-85567d6e20fc.png)

Could you please check this out? 

Best Regards,

Alexander

**Comment by jnasselle** [comment]
Hi @abohorqu ,

THis issue seems to be closely  related to #7935, fixed in 4.2.0 by #8003.

Regards,
Nico
