### ISSUE TITLE
Wazuh API Call  -  Active-Response 404 Error  - Wazuh Api 4.1.5

### ISSUE THREAD

**Issue by Aldrims** [wazuh/wazuh#9080]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Wazuh component | Manager | Packages | Debian 10|

We are working on python file to make Wazuh-Manager execute a script on an agent. We have no problem getting  the token or even to do  a GET request on a lot of endpoint but when working with the Active-Response endpoint we always get a 404 error. 
It seems to be /active-response/{agent-id} but nothing work at all 
Answer : 

![image_github_API](https://user-images.githubusercontent.com/46164298/122773427-a3d64780-d2a8-11eb-8cff-e2a263635fcb.png)
Code 
``` #!/usr/bin/env python3 

import json
import requests
import urllib3
from base64 import b64encode

# Disable insecure https warnings (for self-signed SSL certificates)
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

# Configuration
protocol = 'https'
host = 'X.X.X.X'
port = 55000
user = 'wazuh-wui'
password = 'wazuh-wui'
login_endpoint = 'security/user/authenticate'

login_url = f"{protocol}://{host}:{port}/{login_endpoint}"
basic_auth = f"{user}:{password}".encode()
login_headers = {'Content-Type': 'application/json',
                 'Authorization': f'Basic {b64encode(basic_auth).decode()}'}

print("\nLogin request ...\n")
response = requests.get(login_url, headers=login_headers, verify=False)
token = json.loads(response.content.decode())['data']['token']
print(token)

# New authorization header with the JWT token we got
requests_headers = {'Content-Type': 'application/json',
                    'Authorization': f'Bearer {token}'}

print("\n- API calls with TOKEN environment variable ...\n")

print("Getting API information:")

response = requests.get(f"{protocol}://{host}:{port}/?pretty=true", headers=requests_headers, verify=False)
print(response.text)

print("\nGetting agents status summary:")
#payload = '{"command":"firewall-drop.sh", "arguments": ["-", "X.X.X.X", "1623855056.9258390", "550", "006","var/log/test.log"]}'
#response = requests.put(f"{protocol}://{host}:{port}/active-response?pretty=true", headers=requests_headers, data=payload, verify=False)
#print(response.text)
auth = ("wazuh-wui", "wazuh-wui")
headers = {'Content-Type': 'application/json',
           'Authorization': f'Bearer {token}'}
payload = '{"command":"firewall-drop.sh", "arguments": ["-", "' +  "X.X.X.X" + '", "' + "1623855056.9258390" + '", "' + "550" + '", "' + "006" + '", "var/log/test.log"], "custom": "True"}'
r = requests.put('https://X.X.X.X:55000/active-response/006?', headers=headers, data=payload, verify=False, auth=auth)
print("======================")
print(payload)
print("======================")
print(r.request.body)
print(r.request.headers)
print(r.request.url)
print(r.text)
print("\nEnd of the script.\n")  ```
`

**Comment by AdriiiPRodri** [comment]
Hi @Aldrims,

It seems that the problem is that the endpoint `/active-response/{agent-id}` does not exist. You can find more information about the active-response endpoint here: https://documentation.wazuh.com/current/user-manual/api/reference.html#tag/Active-response

In this case, this line:
```
requests.put('https://192.168.3.2:55000/active-response/006?', headers=headers, data=payload, verify=False, auth=auth)
```

Should be replaced by this one:
```
requests.put('https://192.168.3.2:55000/active-response?agents_list=006', headers=headers, data=payload, verify=False, auth=auth)
```

I hope this answer helps you, if you have any questions feel free to contact us.

Best regards,
Adrián Peña

**Comment by Aldrims** [comment]
![image](https://user-images.githubusercontent.com/46164298/122921502-db092f00-d362-11eb-9b2d-62972f502c97.png)

Another error this time at least  perhaps it's an error in the payload ?

**Comment by AdriiiPRodri** [comment]
Exactly, to execute firewall-drop.sh it is necessary to add the custom parameter to the request:

```
{"command":"firewall-drop.sh", "arguments": ["-", "192.168.2.2", "1623855056.9258390", "550", "006", "var/log/test.log"], "custom": true}
```

Example:

```
curl --request PUT \
  --url 'https://localhost:55000/active-response?agents_list=006' \
  --header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YXp1aCIsImF1ZCI6IldhenVoIEFQSSBSRVNUIiwibmJmIjoxNjI0MzY3OTU5LCJleHAiOjE2MjQzNjg4NTksInN1YiI6IndhenVoIiwicnVuX2FzIjpmYWxzZSwicmJhY19yb2xlcyI6WzFdLCJyYmFjX21vZGUiOiJ3aGl0ZSJ9.qYw7FgzXjn4NiagmqWoVylcjpLrVcJYy0F03ZkFZ7cc' \
  --header 'Content-Type: application/json' \
  --data '{"command":"firewall-drop.sh", "arguments": ["-", "192.168.2.2", "1623855056.9258390", "550", "006", "var/log/test.log"], "custom": true}'

{
  "data": {
    "affected_items": [
      "006"
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "AR command was sent to all agents",
  "error": 0
}
```

**Comment by Aldrims** [comment]
Thx you If we have any other question can we leave this thread open ?

**Comment by AdriiiPRodri** [comment]
Preferably, only one topic should be discussed in each issue. For other questions, you can also use the Slack channel dedicated to the community, where you will receive prompt assistance, or use our mailing list.

You can find all links here: https://wazuh.com/community/

Regards

**Comment by Aldrims** [comment]
@AdriiiPRodri  On the same command , i've got a question  I want to use "delete" instead of "add" but even when using "delete" :
![image](https://user-images.githubusercontent.com/46164298/123655793-9df3df80-d82f-11eb-9799-8149ecf06ae2.png)

**Comment by AdriiiPRodri** [comment]
Hi @Aldrims,

Basically, this happens because the API is not currently ready to send arguments to active-response scripts. What the API actually does is invoke the script and it executes the part of the default parameter which is normally `add`. 

We have plans to improve this, for now, you can find a more detailed explanation in a thread answered by a teammate in our community channel: https://wazuh.slack.com/archives/C0A933R8E/p1624348607171600?thread_ts=1623936240.367200&cid=C0A933R8E

In the next version of Wazuh, new options will be added to the active-response endpoint but for the moment this is the workaround that can be followed to execute the `delete` command.

Regards

**Comment by AdriiiPRodri** [comment]
Closed due to inactivity.
