### ISSUE TITLE
Move Wazuh Manager to different location

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#9082]
Hi,

Wazuh Manager Version - 3.13.2
I faced an issue when logs from agents are growing rapidly and my disk space is shrinking in a fast time.
I would like to move my wazuh-manager to different location and my question is if it is possible?
I tried moving it manually by coping whole /var/ossec to /mylocation and changing `$DIRECTORY` variable  in `/etc/ossec-init.conf` to /mylocation and making changes in systemd for wazuh-api.
After changes I cannot start wazuh-manager due to error:

```
 env[28055]: Started ossec-csyslogd...
 env[28055]: Started ossec-dbd...
 env[28055]: 2021/06/22 13:31:34 ossec-integratord: INFO: Remote integrations not configured. Clean exit.
 env[28055]: Started ossec-integratord...
env[28055]: Started ossec-agentlessd...
env[28055]: ossec-authd did not start correctly.
systemd[1]: wazuh-manager.service: control process exited, code=exited status=1
systemd[1]: Failed to start Wazuh manager.
systemd[1]: Unit wazuh-manager.service entered failed state.
systemd[1]: wazuh-manager.service failed.

```
I tried to chroot to /newlocation in ossecintegrator but it did not work:

```
[root@siem01 bin]# ./ossec-integratord -D /data/ossec
./ossec-integratord: invalid option -- 'D'

Wazuh v3.13.2 - Wazuh Inc. (info@wazuh.com)
http://www.wazuh.com

  ossec-integratord: -[Vhdt] [-u user] [-g group] [-c config] [-D dir]
    -V          Version and license message
    -h          This help message
    -d          Execute in debug mode
    -t          Test configuration
    -f          Run in foreground
    -u <user>   Run as 'user'
    -g <group>  Run as 'group'
    -c <config> Read the 'config' file
    -D <dir>    Chroot to 'dir'

```
Could anyone help me with this issue?

**Comment by jotacarma90** [comment]
Hello @rejszynski,
Changing the location of the manager manually can be quite complex, as the installation takes care of a lot of preparations. The best option would be to reinstall the manager directly, as the script allows you to change the installation path.

Anyway, I will check how hard it could be or if something like this has ever been done before!

Greetings!

**Comment by rejszynski** [comment]
Hi @jotacarma90 

Thank you for your response. I am a little bit afraid of reinstallation of manager, cause it is a production environment and we have hundreds of agents connected. 
Please let me know when you will find out the way to do it :)

Greetings!

**Comment by hitman28594** [comment]
Do you have a single manager or a cluster? 

This can be achieved using a cluster configuration. 

1) Create a new worker node in your new location using your current manager as a master node. 
2) Reconfigure all agents to point to the new worker node. 
3) install your new master node and copy your configs, rules etc. 
4) remove the old master node 
5) configure your new master node 

It’s not a perfect solution, but it should help you achieve what you want in a production environment with “a little bit” less risk.
