### ISSUE TITLE
Add the possibility to use FIPS endpoints on AWS-S3 wodle

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#9087]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Any | AWS-S3 wodle | Manager/Agent | Packages/Sources | Any |

Hello team,

This issue aims to the possibility of adding a flag or argument to use FIPS endpoints on AWS-S3 wodle. This would help Wazuh to become a more FedRamp compliance tool.

[AWS Documentation - FIPS endpoints](https://aws.amazon.com/compliance/fips/)

Regards,
Franco Hielpos

**Comment by noise-kngdm** [comment]
## Issue update
We've been researching how we could support the use of FIPS endpoints when using the AWS integration module and the results of our preliminary research are the following:

The `boto3` API expects any custom endpoint that the client would want to use in the `endpoint_url` parameter passed to the `boto3.session.Session.client()` method. Right now, the module uses that parameter when the user specifies a VPC endpoint. This means that, as of now, the module supports the use of FIPS endpoints, even though the documentation doesn't explicitly mention that.

For example, to use a FIPS endpoint when trying to execute the module to fetch the CloudWatch Logs, the user would have to execute it in the following fashion:
```
$ /var/ossec/framework/python/bin/python3 /var/ossec/wodles/aws/aws-s3.py -access_key XXXXX -secret_key XXXXX -sr cloudwatchlogs -r us-west-2 -se logs-fips.us-west-2.amazonaws.com
```

An example executed on a testing environment.
```
root@532c1a3055f5:/var/ossec/wodles/aws# py ./aws-s3.py -sr cloudwatchlogs -r us-east-1 -se logs-fips.us-east-1.amazonaws.com -g framework-test -d1
DEBUG: +++ Debug mode on - Level: 1
DEBUG: +++ Getting alerts from "us-east-1" region.
DEBUG: only logs: 1632268800000
DEBUG: Getting log streams for "framework-test" log group
DEBUG: Getting data from DB for log stream "test-logstream-1" in log group "framework-test"
DEBUG: Getting CloudWatch logs from log stream "test-logstream-1" in log group "framework-test" using token "None", start_time "1632268800000" and end_time "None"
DEBUG: Saving data for log group "framework-test" and log stream "test-logstream-1".
DEBUG: Purging the BD
DEBUG: Getting log streams for "framework-test" log group
DEBUG: committing changes and closing the DB
```

Then, to completely support the use of FIPS endpoints within the module, it is necessary to reword the documentation and some parts of the module that only mentioned the possibility of using VPC endpoints.
