### ISSUE TITLE
Long term design proposal for Vulnerability Detector

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9089]
### Description

This is a tracking purpose issue to reflect the work done over the long-term design proposal of the Vulnerability Detector module. This design should pursue the next main goals:

- Eliminate the false positive alerts when scanning Windows agents.
- Reduce the possibilities of crashes in the manager due to the parsing and indexing process of the vulnerabilities feeds.
- Improve the scanning performance by migrating from an interval-based model to an event-based model.
- Provide more information to the users rather than only the vulnerabilities alerts.

### Requirements

Here we enumerate some of the requirements on which the design should be based:

- The Wazuh UI should have a section in which the user could navigate over all the vulnerabilities indexed from the vendors' and NVD feeds.
  - Is desirable to have the information of the CVEs provided by the vendors and the NVD delivered in the Wazuh package in order to make it available since the first startup.
  - It should be evaluated the size of this information and how much increase the size of the Wazuh package (no more than 20 MB).
  - It should be evaluated the time that it could take this information to be downloaded.
- The Vulnerability Detector scans shouldn't be performed if the database of CVEs is outdated, but the information should be visible in the Wazuh UI. (**Note:** This requirement must be re-evaluated)
  - Another option is to perform the scan and display a warning message in the Wazuh UI telling the user that the scan was performed with an outdated database.
- The CVEs database should be updated only if the Vulnerability Detector module is enabled, but the information should be visible in the Wazuh UI even when the module is disabled.
  - In case of having a database outdated because of having the Vulnerability Detector module disabled, the Wazuh UI should inform about the disabled status together with the date of the last update.
  - The update of the database should be attempted to be done right before the scan. (**Note:** This requirement must be re-evaluated)
  - The update of the database should be performed only if there is a new version of the database available.
  - The user should have the possibility to configure offline feed.
  - The Wazuh UI should have a button to trigger the database update.
- The Vulnerability Detector scans should be able to be deactivated by OS, by agent ID, and by agent groups.
- The Vulnerability Detector scans should be triggered by events (when new packages, or packages being updated or removed). No more settings of scan frequency.
- The Wazuh UI should have a button to trigger a syscollector packages scan.

**Comment by DProvinciani** [comment]
The next table summarizes the requirements and will be used to link them and have traceability with all the `epics` that will be involved in this long-term desing.

![image](https://user-images.githubusercontent.com/5703274/123486911-57aa4080-d5e3-11eb-97e9-9106f864a1fb.png)

**Comment by palaciosjeremias** [comment]
The following tasks are related and required to the development of the Wazuh Unified Feed.
- Generation of a unique package dictionary. Wazuh Dictionary.
        - Revision of the regex format / Performance.
        - Investigate if every WIndows package must go through the dictionary to be detected in the VulDet scan
        - Size: S
        - Uncertainty: Small

- Normalization/unification of vendor feeds with NVD. 
        - Investigation
        - Python scripts development for parsing and setting up the new feed. (Wazuh Feed Normalizer)
        - Consider the duplication of vulnerabilities between vendors and NVD
        - Consider the particular case of the MSU feed.
        - Automated tests.
        - It can be thought of as a small product.
        - Contemplate providing the user with the Wazuh Feed Normalizer for their own development and testing.
        - Size: L
        - Uncertainty: Big
        
- Making WUF available for download in a repository.
        - CICD support to publish this as a repo.
        - Provide WUF and WUF Metadata.
        - Risks: Large volume of requests. The danger of attacks.
        - Size: Undetermined, CICD ownership
        - Uncertainty: Undetermined, CICD ownership

    - Make VulDet update the WUF
        - Keep updating old feeds.
        - VulDet must maintain the functionality of reading feeds from offline locations and custom URLs.
        - Trigger in WDB the update of the navigable WUF
        - Size: S
        - Uncertainty: Small.

    - Changes in packages so that the unified feed goes with the installer (in case it does not exceed 20 MB).
        - Tentative
        - It involves editing the manager's installers
        - The installer package will always be downloaded with the vulnerabilities
        - The installer package is not configurable to choose whether or not to download it with the vulnerabilities.
        - Size: S
        - Uncertainty: Small.

- Dashboard in the Wazuh UI to show the unified feed
    - Changes in the API so that from the UI you can consult WDB and obtain the information of unified feeds.
- Changes in Wazuh DB to allow queries to the unified feed.
            - Add (if it does not exist) that the API knows the status of VulDet configuration
- UI changes
        - Size: Undetermined, Frontend and Framework ownership
        - Uncertainty: Indeterminate, Frontend, and Framework ownership

    - VulDet adaptation to work with the WUF
        - Reorganization of the badly separated code between "vendor" and NVD
        - Based on the flow of the NVD, see if it has to be supplemented with things from the feed vendor
        - Clean the update of old feeds.
        - Clean up queries and methods from old feeds.
        - This would keep the scan engine. As WUF is based on the NVD format, JOINs, etc. could be reused.
        - Massive testing.
        - Adapt all IT and UT.
        - Size: L
        - Uncertainty: Big

    - Proposal:
        - Provide in addition to the last feed, some deltas, to download just that.

**Comment by palaciosjeremias** [comment]
The below image represents how the Wazuh Unified Feed should be implemented:
![WUF](https://user-images.githubusercontent.com/11434230/123488917-4d8a4100-d5e7-11eb-8b69-7b073fc4e831.png)

**Comment by MiguelazoDS** [comment]
### Proposal syscollector changes.

![syscollector](https://user-images.githubusercontent.com/13010397/123492384-b07fd600-d5ef-11eb-8495-3757063e3fbd.png)

### Description

This diagram represents the components that will be affected by the addition of a button that performs a system inventory scan on demand. This should be done through the API (DevTool, curl) requesting a scan on an agent specified by its ID.
The scan on demand will be implemented along with the already existent interval setting, since from the previous development we faced that a synchronization event in syscollector was not achievable with simple changes.

The main development of this proposal involves the communication between the manager and the agent to perform the scan, and the event design that will be listened to by Vulnerability Detector.

**Comment by pereyra-m** [comment]
### Vulnerability detector buttons

![vuln_det_buttons](https://user-images.githubusercontent.com/65046601/123494558-a1e8ed00-d5f6-11eb-83f4-96e489363d52.png)

This schema represents the new required ways to interact with vulnerability detector:
- Find vulnerability: The user could launch a scan from the UI through an API request. Some extra parameters may be added, like a an agent's list, group/OS filters, etc. It is not necessary to wait for an **interval** time to expire or a manager restart.
- Update feed: The vulnerabilities' database can be updated on demand, it isn't necessary to wait for an  **update** time interval.
- Syscollector event: an update in the packages or OS inventory would automatically trigger a scan
