### ISSUE TITLE
Replace FIM DB implementation with dbsync and rsync

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9103]
|Wazuh version|Component|
|---|---|
| | Wazuh FIM |

### Description

As a step towards unifying DB handling between different processes, we need to integrate dbsync and rsync into FIM and replace the current custom handling of the DB with these more generic libraries. This epic is meant to group together all of the required steps we need to take to accomplish this goal, as well as track our progress.

###  Class diagram

![class_diagram](https://user-images.githubusercontent.com/29475387/182315214-2c16598e-0936-4782-8432-f0900fcc74b9.svg)

###  Sequence diagram

![image](https://user-images.githubusercontent.com/29475387/182315490-96590ac8-f0b0-4705-aa24-7e24e0528441.png)

### E-R diagram

![image](https://user-images.githubusercontent.com/29475387/182315726-25a42bc2-d77a-40e6-915c-69993aadb27e.png)

**Comment by chemamartinez** [comment]
Everything closed! GJ @wazuh/watchdogs! 🚀

**Comment by FrancoRivero** [comment]
Felicitaciones team !!! Por fin, tenemos el nuevo FIMDB.
Saludos
