### ISSUE TITLE
Implement instantiation of dbsync and proper creation of FIM DB

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9106]
|Wazuh version|Component|
|---|---|
| 4.4.0+| Wazuh FIM |

The purpose of this issue is to implement a private instance of `DBSync` inside FIM DB that will be responsible for all interactions between FIM and its underlying DB. The instance of DBSync needs to be visible by all files inside `src/syscheckd/db` but must not be accessible from said directory, creating a global pointer to the instance to be created in `fim_db.c` and adding `extern` definitions to the rest of the files should be enough to keep the required scope. At this point FIM will have an instance of `DBSync` but should also keep the existing implementation of FIM DB in order to keep all functionality working, other issues will be responsible for slowly replacing FIM DBs functionality with dbsync.

- [x] Create an instance of `DBSync` inside `fim_db.c` and have it create the main DB.
- [x] Change FIM DB to simply open a handle to the DB created by `DBSync`. (If this causes issues, we will completely remove FIM DB, but since `DBSync` won't actually do any operations yet, it should be safe).
- [x] Add extern definitions to the `DBSync` instance.

**Comment by antoniomanuelfr** [comment]
Closed by https://github.com/wazuh/wazuh/pull/10020
