### ISSUE TITLE
Adapt file methods in FIM DB to the new integrations

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9107]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/9103 | FIM |

### Description

This issue intends to integrate every function and query in `file.cpp` to the new design of FIM DB. It implies:

- Every particular operation over files should be moved to the `DBItemWrapper` class
- Every function used externally should be included in the `FIMDBWrapper` which acts as the external interface.
- Every query should be replaced with equivalent operations performed by `dbsync`
- Every added method should be accompanied by unit tests.

**Comment by FrancoRivero** [comment]
We are working on this issue in this [branch](https://github.com/wazuh/wazuh/tree/9107-adapt-file-methods-to-new-DB-FIM) starting from [10227-implement-wrappers-to-adapt-new-FIMDB-implementation](https://github.com/wazuh/wazuh/tree/10227-implement-wrappers-to-adapt-new-FIMDB-implementation)
