### ISSUE TITLE
Adapt registry methods in FIM DB to the new integrations

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9108]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/10227 | FIM |

### Description

This issue intends to integrate the registry synchronization algorithm to make use of dbsync transactions:

- [X] Adapt registry key scan algorithm to make use of transactions and adapt the generation of fim registry key events.
- [X] Adapt registry value scan algorithm to make use of transactions and adapt the generation of fim registry value events.

## DoD
- [x] Add C++ implementation
- [ ] RTR OK

**Comment by FrancoRivero** [comment]
We are working on this issue in this [branch](https://github.com/wazuh/wazuh/tree/9108-adapt-registry-methods-to-new-DB-FIM) starting from [10227-implement-wrappers-to-adapt-new-FIMDB-implementation](https://github.com/wazuh/wazuh/tree/10227-implement-wrappers-to-adapt-new-FIMDB-implementation)
