### ISSUE TITLE
Adapt generic DB methods in FIM DB to the new integrations

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh#9114]
|EPIC|Component|
|---|---|
| https://github.com/wazuh/wazuh/issues/10227 | FIM |

### Description

This issue intends to integrate every function and query in `db.cpp` to the new design of FIM DB. It implies:

- Every particular operation over FIM items should be moved to the `DBItemWrapper` class
- Every function used externally should be included in the `FIMDBWrapper` which acts as the external interface.
- Every query should be replaced with equivalent operations performed by `dbsync`
- Every added method should be accompanied by unit tests.

**Comment by antoniomanuelfr** [comment]
Most of the functions mentioned in the previous comment will be removed and the ones that remain will need new queries.

These functions are: 
- `fim_db_init`
- `fim_db_get_count_entries`

As the number of entries in Windows and the rest of the supported OS is different, we will need a specific query for Windows. These queries are:
## Linux
```json
{
    "table": "file_entry",
    "query": {
        "column_list": [
            "count(*) AS count"
        ],
        "row_filter": "",
        "distinct_opt": false,
        "order_by_opt": "",
        "count_opt": 100
    }
}
```
## Windows:
**Registry keys**
```json
{
    "table": "registry_key",
    "query": {
        "column_list": [
            "count(*) AS count"
        ],
        "row_filter": "",
        "distinct_opt": false,
        "order_by_opt": "",
        "count_opt": 100
    }
}
```
**Registry values**
```json
{
    "table": "registry_value",
    "query": {
        "column_list": [
            "count(*) AS count"
        ],
        "row_filter": "",
        "distinct_opt": false,
        "order_by_opt": "",
        "count_opt": 100
    }
}
```
