### ISSUE TITLE
AIX not correct showing OS

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh#9121]
Wazuh 4.1.5 Manager
Wazuh 4.0.4 Agent on AIX 7.2

In the Kibana Wazuh Website the AIX OS is shwing as 0.0.
It seems that the agent on the AIX System delivers wrong values:
Here what ist stored in Wazuh:
One AIX System, one Solaris and one RedHad Linux.

First the output from the RestAPI:

{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "AIX",
          "major": "0",
          "minor": "0",
          "name": "",
          "platform": "",
          "uname": "AIX |aix179 |2 |7 |00F912914C00",
          "version": "0.0"
        },
        "node_name": "wazuh-zkab",
        "status": "active",
        "ip": "any",
        "dateAdd": "2021-03-17T07:46:37Z",
        "registerIP": "any",
        "group": [
          "default"
        ],
        "manager": "wazuh-zkab",
        "name": "aix179",
        "configSum": "4e9a49a8810aced2ed15020c543f4cab",
        "version": "Wazuh v4.1.0",
        "lastKeepAlive": "2021-06-25T08:33:45Z",
        "mergedSum": "55aadb25983ffe91820ae74ec984c971",
        "id": "700"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "x86_64",
          "codename": "Ootpa",
          "major": "8",
          "minor": "3",
          "name": "Red Hat Enterprise Linux",
          "platform": "rhel",
          "uname": "Linux |rrpbawcbrp01 |4.18.0-240.22.1.el8_3.x86_64 |#1 SMP Thu Mar 25 14:36:04 EDT 2021 |x86_64",
          "version": "8.3"
        },
        "node_name": "wazuh-pkab",
        "status": "active",
        "ip": "10.1.96.55",
        "dateAdd": "2021-06-24T08:23:36Z",
        "registerIP": "any",
        "group": [
          "default",
          "fgi_profiles",
          "syscollector"
        ],
        "manager": "wazuh-pkab",
        "name": "rrpbawcbrp01",
        "configSum": "9b0a103506d933894f6288dad97daea5",
        "version": "Wazuh v4.1.2",
        "lastKeepAlive": "2021-06-25T08:33:37Z",
        "mergedSum": "ad7342793de182e978c50e8740e134de",
        "id": "7993"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "i86pc",
          "major": "11",
          "minor": "4",
          "name": "Oracle Solaris",
          "platform": "solaris",
          "uname": "SunOS |admin-p |5.11 |11.4.13.4.0 |i86pc",
          "version": "11.4"
        },
        "node_name": "wazuh-pkab",
        "status": "active",
        "ip": "any",
        "dateAdd": "2021-04-07T10:42:46Z",
        "registerIP": "any",
        "group": [
          "default"
        ],
        "manager": "wazuh-pkab",
        "name": "srv04142-lz-solarisadmin-p",
        "configSum": "4e9a49a8810aced2ed15020c543f4cab",
        "version": "Wazuh v4.0.4",
        "lastKeepAlive": "2021-06-25T08:33:56Z",
        "mergedSum": "55aadb25983ffe91820ae74ec984c971",
        "id": "5556"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}

And the agent_control output:

Wazuh agent_control. Agent information:
   Agent ID:   700
   Agent Name: aix179
   IP address: any/any
   Status:     Active

   Operating system:    AIX |aix179 |2 |7 |00F912914C00
   Client version:      Wazuh v4.1.0
   Configuration hash:  4e9a49a8810aced2ed15020c543f4cab
   Shared file hash:    55aadb25983ffe91820ae74ec984c971
   Last keep alive:     1624610135

   Syscheck last started at:  Unknown
   Syscheck last ended at:    Unknown
   Rootcheck last started at: Unknown

Wazuh agent_control. Agent information:
   Agent ID:   7993
   Agent Name: rrpbawcbrp01
   IP address: any/any
   Status:     Active

   Operating system:    Linux |rrpbawcbrp01 |4.18.0-240.22.1.el8_3.x86_64 |#1 SMP Thu Mar 25 14:36:04 EDT 2021 |x86_64
   Client version:      Wazuh v4.1.2
   Configuration hash:  9b0a103506d933894f6288dad97daea5
   Shared file hash:    ad7342793de182e978c50e8740e134de
   Last keep alive:     1624610136

   Syscheck last started at:  Unknown
   Syscheck last ended at:    Unknown
   Rootcheck last started at: Unknown

Wazuh agent_control. Agent information:
   Agent ID:   5556
   Agent Name: srv04142-lz-solarisadmin-p
   IP address: any/any
   Status:     Active

   Operating system:    SunOS |admin-p |5.11 |11.4.13.4.0 |i86pc
   Client version:      Wazuh v4.0.4
   Configuration hash:  4e9a49a8810aced2ed15020c543f4cab
   Shared file hash:    55aadb25983ffe91820ae74ec984c971
   Last keep alive:     1624610145

   Syscheck last started at:  Unknown
   Syscheck last ended at:    Unknown
   Rootcheck last started at: Unknown

AIX has in the uname part other values.
   Operating system:    AIX |aix179 |2 |7 |00F912914C00

The OS Version ist 7.2.

Is that an agent or wazuh manager problem to interpret these values....

**Comment by pereyra-m** [comment]
Hi @Joeri-MS !

I apologize for this inconvenience.
This issue seems to be the same than #6132, and it was solved in this PR #8381.

It will be released as soon as possible.
Regards.

**Comment by Joeri-MS** [comment]
Wow, thank you.

Sorry that i make an duplicate Issue, i didn't found the old issue.

**Comment by pereyra-m** [comment]
No problem @Joeri-MS!

Write us anytime you need.
I'm closing this issue.

Regards.
