### ISSUE TITLE
Normalize shebangs on wodles scripts

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#9128]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.x | Wodles | Manager/Agent | Packages/Sources | Linux |

Hello team,

This issue is to normalize the shebangs used in the Python scripts of the wodles and to move to `Python3` as default binary.

We can see that some wodles are using:
https://github.com/wazuh/wazuh/blob/e1b9d1673abd5e0bc443e3d7b184454149588757/wodles/docker-listener/DockerListener.py#L1

Whereas others are using the new one:
https://github.com/wazuh/wazuh/blob/e1b9d1673abd5e0bc443e3d7b184454149588757/wodles/gcloud/gcloud.py#L1

In Azure logs we can also see a wrong shebang:
https://github.com/wazuh/wazuh/blob/e1b9d1673abd5e0bc443e3d7b184454149588757/wodles/azure/azure-logs.py#L1

I believe that the best approach would be to use the following one for all the wodles:
```
#!/usr/bin/env python3
```

Regards,
Franco Hielpos

**Comment by davidjiglesias** [comment]
We will update azure shebang in 4.4, as currently for <4.3.0 azure integration is only supported in the manager, and therefore it should use embedded python shebang.
