### ISSUE TITLE
Wazuh agent installation queries

### ISSUE THREAD

**Issue by riteshaduri** [wazuh/wazuh#9137]
Can we install wazuh agent on the wazuh manager?

**Comment by antoniomanuelfr** [comment]
Hello @riteshaduri 

You don't need to install the wazuh agent in the same machine where you installed the manager, as the manager itself has the agent capabilities. The manager will appear with the `000` id.

I recommend you to take a look at the [getting started section](https://documentation.wazuh.com/current/getting-started/index.html) of the documentation.

**Comment by riteshaduri** [comment]
Hello @antoniomanuelfr 

Thanks for help, one more query if you can help.
Can we install wazuh agent on the Elasticsearch and kibana server?

**Comment by antoniomanuelfr** [comment]
Yes, there shouldn't be any problem installing the agent on the elasticsearch/kibana server. 

If you find any problem, don't hesitate to contact us.

**Comment by riteshaduri** [comment]
Thanks @antoniomanuelfr, sure.

**Comment by antoniomanuelfr** [comment]
I'm closing this issue because the original question has been answered.
Have a nice day
