### ISSUE TITLE
Settings. Error. 2008 - Invalid url field

### ISSUE THREAD

**Issue by matt-lucero** [wazuh/wazuh#914]
For whatever reason, I'm unable to use a URL other than an IP address when attempting to add an API via the Wazuh Kibana app. I'm in the process of upgrading from Wazuh 2.2.1 to 3.3.1, using a DNS entry used to work in the previous version. Now I get the "Invalid url field" message when I use anything besides an IP address. I am able to successfully authenticate with the Wazuh API via the FQDN using curl on the Kibana instance. The DNS is valid and resolves fine outside the Wazuh app.

![chrome developer tools - xhr](https://user-images.githubusercontent.com/34253244/42476228-1e1bf6c6-8382-11e8-888f-48698b85328b.png)

Wazuh App version: 3.3.1. Kibana Version: 6.2.4. Wazuh Server version 3.3.1 

Any assistance you can provide would be helpful in troubleshooting this issue, thanks.

**Comment by jesusgn90** [comment]
Hello @matt-lucero , the error code 2008 is related to the url field as you can see. Your DNS is not giving true with the next regex:

```js
const urlRegEx    = new RegExp(/^https?:\/\/[a-zA-Z0-9]{1,300}$/);
const urlRegExIP = new RegExp(/^https?:\/\/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$/);
```
That's a known bug with our validation system and we need to fix it. For now you can fix it by yourself modifying the file under **/usr/share/kibana/plugins/wazuh/server/controllers/wazuh-api-elastic.js**, replace the next line (line ~ 18 depending on your package):

```js
const urlRegEx = new RegExp(/^https?:\/\/[a-zA-Z0-9]{1,300}$/);
```

by this one:

```js
const urlRegEx = new RegExp(/^https?:\/\/[\.\-a-zA-Z0-9]{1,300}$/);
```

Once done, please remove the Kibana bundles and restart Kibana:

```
# rm -rf /usr/share/kibana/optimize/bundles
# systemctl restart kibana
```
Kibana will re-optimize the app so wait few minutes before try again. Track the progress using the next command:

```
# watch -n0 'systemctl status kibana -l'
```

Regards,
Jesús

**Comment by jesusgn90** [comment]
Hello again @matt-lucero , here you can see the fix https://github.com/wazuh/wazuh-kibana-app/pull/690 too.

Regards,
Jesús

**Comment by matt-lucero** [comment]
Thanks, @jesusgn90 the fix is confirmed and working.

**Comment by jesusgn90** [comment]
Ok @matt-lucero then I'm going to close this issue, happy to help.

Regards,
Jesús

**Comment by tomaszsiemienik** [comment]
hi, can we get this fix applied to plugin version which supports ELK version 6.2.4 and wazuh 3.3.0. We are currently on this version of plugin https://packages.wazuh.com/wazuhapp/wazuhapp-3.3.1_6.2.4.zip and registering api by dns still not possible.

thank you.

**Comment by jesusgn90** [comment]
Hi @tomaszsiemienik , I've just replied you at https://github.com/wazuh/wazuh-kibana-app/commit/11ae30ddaaa2a38a4efde93b0e53f6cb81c73b87#commitcomment-31022211
