### ISSUE TITLE
Force configuration push and rootcheck across all agents

### ISSUE THREAD

**Issue by srikwit** [wazuh/wazuh#915]
Hello Team,

I am writing custom rootcheck rules and want to test them against all my agents.

When I modify ossec.conf and restart my servers and agents with the following commands:
```
 /var/ossec/bin/ossec-control restart
 /var/ossec/bin/agent_control  -R  -a
```

my changes are not applied immediately. 

In this case my signatures are located at: 
/var/ossec/etc/rootcheck/win_malware_rcl.txt

I have had to modify the signatures located in the default groups folder(/var/ossec/etc/shared/default/win_malware_rcl.txt) and the agent.conf and restart the manager and client to get my signatures pushed.

My questions are:
1. Why are my changes in agent.conf getting applied immediately with a restart but the case is not the same with ossec.conf?

2. How do I immediately apply my changes in ossec.conf and get the same configuration applied across my clients?

3. I am unable to see a scan_on_start for the rootcheck functionality at:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/rootcheck.html

Because of this, how do I ensure that all my agents perform a rootcheck on a restart with the new frequency interval defined in the agent.conf? My clients currently have different last_scan times and I would like to synchronize them.

**Comment by srikwit** [comment]
Dear Team, I have figured out that you can force a rootcheck scan using agent_control:
        -r -a             Runs the integrity/rootkit checking on all agents now.
        -r -u <id>        Runs the integrity/rootkit checking on one agent now.

Kindly let me know about the ossec.conf behavior.

**Comment by vikman90** [comment]
Hi @srikwit,

Sorry for the late response. Answering your questions:

1. The settings in `ossec.conf` are local to the manager or the agents, the system won't restart itself automatically. When you change the configuration and you are ready to apply it, you can restart the host (agent or manager) manually.

    On the other hand, the `agent.conf` and the rest of the files in the _shared_ folder are intended to be pushed by the manager to the agents. The moment when the manager would push these files to the agents depends on many factors: the file reloading time (manager), the notify frequency (agent), the status of the network (the file may not arrive completely in UDP mode) and whether the agent is connected at this moment. 

    That's why the agent will verify the file _agent.conf_ and restart it automatically if everything is OK. Otherwise, you would have to monitor when the shared file has been successfully pushed and restart the agents manually (locally or remotely). The agent auto-restart feature was introduced in Wazuh 3.0.

2. As I explained above, the file `ossec.conf` is intended for local configuration. If you want to apply a shared configuration, I suggest you put it in the file `agent.conf`, so the `ossec.conf` would only contain the settings to connect to the manager (the `<client>` section).

3. This is a misfeature. Two problems here: Rootcheck misses a `<scan_on_start>` option, and currently, the Rootcheck scan will always start after the first full scan of Syscheck. If you need to scan Rootcheck just when the agent gets started, you can disable `<scan_on_start>` in Syscheck, so Rootcheck will start immediately.

   We plan to change this issue as soon as possible: we will separate Syscheck and Rootcheck so they will work independently. This will allow performing both Syscheck and Rootcheck scans at the same time.

Hope this helps you. Please let me know if I have not clarified something.

Thank you for your feedback!
Best regards.

**Comment by srikwit** [comment]
Thanks @vikman90 your explanation is very useful and clears all of my queries. Thanks again for taking the time to provide your answer in such a detailed manner.
