### ISSUE TITLE
SUSE support: Insert SUSE package dependencies into the vulnerability database

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9155]
### Description

Once the dependencies are stored from the OVAL parser, they have to be inserted into the vulnerability database in order to use them when detecting vulnerabilities for SUSE agents.

This step assumes that https://github.com/wazuh/wazuh/issues/9154 inserts all the needed information in a structure, so the goal for this issue are:

- Insert the information parsed in the vulnerability database
- Modify the database schema to relate the dependencies to each affected package for a CVE

**Comment by MarcelKemp** [comment]
Devel branch: https://github.com/wazuh/wazuh/tree/9155-insert-suse-deps
