### ISSUE TITLE
SUSE support: OVAL pre-scan to resolve package dependencies

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9156]
### Description

To avoid the evaluation of every dependency for each scanned package, we are introducing a pre-scan step where dependencies are evaluated.

The result for this pre-scan is stored so it is available when evaluating the vulnerable packages in the scan stage.

**Comment by alromeros** [comment]
**Devel branch:** https://github.com/wazuh/wazuh/tree/9156-SUSE-deps-prescan
