### ISSUE TITLE
Any plans on integrating Vulnerability Management?

### ISSUE THREAD

**Issue by reno777** [wazuh/wazuh#918]
I am new to using Wazuh, just switching from OSSIM. I was just wondering if there are any plans to integrate some form of Vulnerability management similar to how OSSIM has openvas baked in. If something like this is already there and I have missed it, my apologies

**Comment by TJOSERAFAEL** [comment]
Hi @reno777 

Wazuh has a custom module called Vulnerability Dectector that compares the software packages installed on your machines with the  CVEs depending on your operating system. You can find more information here: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection.html

Also Wazuh offers **rootkit detection**, **malware detection**, file integrity monitoring  and collecting information of your machine such as open ports, disk usage etc.As it is a very configurable platform you can monitor everything you want with **logcollector**.

All the information gathered can be visualized with the Kibana App included.

Here you have some useful resources:
https://documentation.wazuh.com/current/user-manual/capabilities/index.html
https://documentation.wazuh.com/current/getting-started/use-cases.html


Best regards.

**Comment by reno777** [comment]
Awesome! Looks like that covers most of what I need. Thanks xD Closing issue.
