### ISSUE TITLE
Vulnerability Detector performance during the scan

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#9188]
## Description

The goal of this issue is to evaluate the performance of the Vulnerability Detector during the scan of the agents in terms of speed. We have detected that the module can take so much time to analyze agents' vulnerabilities so we attempt to shed light on the main cause. 

Apart from the results of this evaluation, we have to take into account the following facts when talking about the module performance.

- The Vulnerability Detector is not multithread so each agent is scanned sequentially.
- The agent's OS influences the scan time as each one is treated in a different way.
- The number of packages installed in the target agent.
- The status of the machine during the scan will affect the performance.

## Tests results

A manual test has been done to obtain the first conclusions. 

**Measures:**
- Real scan time
- CPU usage

**Targets:**
- Agent 000 (Ubuntu 20.04)
- Agent 001 (RHEL 7)
- Agent 002 (Windows Server 2016)

**Versions:**
- Wazuh v4.1.5
- Wazuh v4.2.0

**Manager information:**
- Ubuntu 20.04 2 cores 2GB RAM

The following table shows the time in seconds that the Vulnerability Detector spent in scanning every agent, including each scan stage:

**4.1.5**

|             	| Ubuntu 20 	| RHEL7 	| Win Server 2016 	|
|-------------	|-----------	|-------	|-----------------	|
| **OVAL scan**   	| 46        	| 147   	| N/A             	|
| **NVD scan**    	| 2         	| 1     	| 2               	|
| **Correlation** 	| 35        	| 252   	| N/A             	|
| **Report**      	| 6         	| 70    	| 17              	|
| **Total**       	| 90        	| 471   	| 19              	|

**4.2.0**

|             	| Ubuntu 20 	| RHEL7 	| Win Server 2016 	|
|-------------	|-----------	|-------	|-----------------	|
| **OVAL scan**   	| 21        	| 52    	| N/A             	|
| **NVD scan**    	| 0         	| 0     	| 2               	|
| **Correlation** 	| 30        	| 164   	| N/A             	|
| **Report**      	| 6         	| 54    	| 16              	|
| **Total**       	| 57        	| 270   	| 18              	|

Here the CPU usage during the scan of the three agents:

![image](https://user-images.githubusercontent.com/29475387/124287136-f557bf80-db4f-11eb-8f46-bd2b37c92909.png)

Conclusions that we obtain from this first evaluation:
- The scan in the same conditions is faster for 4.2.0 for every agent, decreasing the CPU usage as well.
- RHEL and CentOS agents are the slowest to be scanned, unlike Windows agents which are very efficient (they do the NVD scan only).
- The correlation stage is the heaviest. It consists of crossing the data obtained in each scan with the information from the other feeds to obtain a double-check avoiding false positives.

It is important to analyze the scan process for Redhat agents in order to determine the cause of that slowness with respect to the other Linux agents.

## Pending tests

Apart from the manual tests, it would be interesting to run automated tests with the following features:

- Run the test in AWS instances where the resources are more homogeneous
- Create a script to monitor all the interesting resources such as the CPU time, R/W ops, and other measures for each agent and stage, including the parsing and indexing for every feed, as well as the communication with Wazuh DB.
*See content of `/proc/<pid>/io`.*
-  Stress the module with different compatible agents OS.

The result of these extra tests will help us to know which is the weak piece of the process and how to remediate it.

**Comment by DProvinciani** [comment]
Based on the first analysis made in the description, we decided to go deeper into each of the stages of a Vulnerability Detector scan. To do so, we divided all the stages depending on whether or not they make use of databases.

## Stages with database access

The stages involved in this section are:

1. The query to Wazuh DB to get all the agents to be scanned and their OS information.
2. For each agent:
    1. The packages data transfer from the agent database to the `cve.db` database.
    2. The OVAL scan.
    3. Te NVD scan.

Having said that, we took measures of each stage in a Wazuh 2.4 installation.

| | Debian 10 | Ubuntu 20 | Centos 8 | Windows 7 |
|-|-|-|-|-|
| **Data transfer**   | 0        	| 0        	| 0    	| 0             	|
| **OVAL scan**   	| 20        	| 23        	| 56    	| N/A             	|
| **NVD scan**    	| 0         	| 0         	| 0     	| 2               	|

With these numbers, we identified that mani time is spent in the OVAL scan. This scan, depending on the OS, involves the next set of queries.

```c
[VU_JOIN_QUERY] = "SELECT CVEID, (CASE WHEN VALUE IS NOT NULL THEN VALUE ELSE PACKAGE_NAME END), SOURCE, VERSION, ARCH, OPERATION, OPERATION_VALUE, SRC_VERSION, VENDOR \
                   FROM VULNERABILITIES LEFT JOIN VARIABLES ON VARIABLES.VID = VULNERABILITIES.PACKAGE AND VARIABLES.TARGET = VULNERABILITIES.TARGET \
                   INNER JOIN AGENTS ON PACKAGE_NAME = (CASE WHEN VALUE IS NOT NULL THEN VALUE ELSE PACKAGE END) \
                   WHERE IGNORE = 0 AND VULNERABILITIES.TARGET = ? AND AGENT_ID = ? \
                   ORDER BY CVEID, PACKAGE_NAME, VERSION, ARCH;",
[VU_JOIN_RH_QUERY] = "SELECT DISTINCT CVEID, PACKAGE_NAME, SOURCE, VERSION, ARCH, OPERATION, OPERATION_VALUE, SRC_VERSION, VENDOR \
                      FROM VULNERABILITIES LEFT JOIN ARCHITECTURES ON (ARCHITECTURES.ID = VULNERABILITIES.ARCH_ID AND ARCHITECTURES.TARGET = VULNERABILITIES.TARGET) \
                      INNER JOIN AGENTS ON (AGENTS.ARCH = 'noarch' OR VULNERABILITIES.ARCH_ID = 0 OR AGENTS.ARCH = ARCHITECTURES.ARCHITECTURE) AND PACKAGE = PACKAGE_NAME WHERE IGNORE = 0 \
                      AND (VULNERABILITIES.TARGET = TARGET_MAJOR OR VULNERABILITIES.TARGET IS NULL OR (TARGET_MAJOR IS NULL AND VULNERABILITIES.TARGET = ?)) \
                      AND AGENT_ID = ? ORDER BY CVEID, PACKAGE_NAME, VERSION, ARCH;",
[VU_JOIN_DEBIAN_QUERY] = "SELECT CVEID, PACKAGE_NAME, SOURCE, VERSION, ARCH, OPERATION, OPERATION_VALUE, SRC_VERSION, VENDOR \
                          FROM VULNERABILITIES INNER JOIN AGENTS ON PACKAGE = (CASE WHEN SOURCE IS NOT NULL THEN SOURCE ELSE PACKAGE_NAME END) \
                          WHERE IGNORE = 0 AND VULNERABILITIES.TARGET = ? AND AGENT_ID = ? \
                          ORDER BY CVEID, PACKAGE_NAME, VERSION, ARCH;",
```

After evaluating the queries using [DB Browser for SQLite](https://sqlitebrowser.org/), we identified that with this tool, the queries returned the results immediately. This made us think about the possibility of an issue with the SQLite version used in Wazuh. The version used in Wazuh is `3.19`, so we tried using `3.36`. And we got the next results:

| | Debian 10 | Ubuntu 20 | Centos 8 | Windows 7 |
|-|-|-|-|-|
| **Data transfer**   | 0        	| 0        	| 0    	| 0             	|
| **OVAL scan**   	| 1        	| 2        	| 0    	| N/A             	|
| **NVD scan**    	| 0         	| 0         	| 0     	| 2               	|

This demonstrates that the SQLite version really improves the queries performance.
