### ISSUE TITLE
Daily Reports Stopped Working

### ISSUE THREAD

**Issue by neubauek** [wazuh/wazuh#9189]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | ossec-reportd | Manager | Packages | RHEL7 |

My daily reports stopped working some time recently. I have done some troubleshooting and have found out that ossec-reportd does not seem to work.

If I do a simple test like the following I get zero alerts post-filter. I have many thousands of events at level 10.
sudo cat /var/ossec/logs/alerts/alerts.log | /var/ossec/bin/ossec-reportd -f level 10
2021/06/21 09:28:03 ossec-reportd: INFO: Started (pid: 22466).
2021/06/21 09:28:08 ossec-reportd: INFO: Report completed and zero alerts post-filter.

I have also tried the following with no filter and get zero results.
sudo cat /var/ossec/logs/alerts/alerts.log | /var/ossec/bin/ossec-reportd
2021/06/21 09:30:17 ossec-reportd: INFO: Started (pid: 22550).
2021/06/21 09:30:23 ossec-reportd: INFO: Report completed and zero alerts post-filter.

I'm not sure if the ossec-reportd daemon is supposed to be continuously running. When I check its status via the API, it shows as stopped.
curl -k -X GET "https://127.0.0.1:55000/manager/status?pretty" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": [{"ossec-agentlessd": "stopped", "ossec-analysisd": "running", "ossec-authd": "running", "ossec-csyslogd": "stopped", "ossec-dbd": "stopped", "ossec-monitord": "running", "ossec-execd": "running", "ossec-integratord": "stopped", "ossec-logcollector": "running", "ossec-maild": "running", "ossec-remoted": "running", "ossec-reportd": "stopped", "ossec-syscheckd": "running", "wazuh-clusterd": "stopped", "wazuh-modulesd": "running", "wazuh-db": "running", "wazuh-apid": "running"}], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Processes status was successfully read", "error": 0}

I have tried restarting services by "systemctl restart wazuh-manager".

**Comment by jnasselle** [comment]
Hi @neubauek!

Thank you for creating this issue! This problem was also reported in #8282, so i will close this one in order to avoid duplicated issues.

By other hand, `ossec-reportd` is more like a tool than a daemon that is running continuously (despite the 'd' of daemon in his name), allowing to use the reports feature triggered by other custom mechanism (i.e cron job), task that Wazuh does indirectly by `ossec-monitord`.

Regards,
Nico
