### ISSUE TITLE
Potential typo in agentless script

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#9200]
Hello team,

I'm opening this ticket because we observed a potential typo in the agentless script: https://github.com/wazuh/wazuh/blob/master/src/agentlessd/scripts/ssh_integrity_check_linux#L29

The following line should be as follows:
```
send "unset HISTFILE; echo \"INFO: Starting.\"
```
Although it is working perfectly, we think we should review it and test if it will cause any impacts.

**_Reported by Johannes Segitz of SUSE_**

Regards,

Miguel Casares

**Comment by TomasTurina** [comment]
This issue applies for `ssh_integrity_check_linux` agentless script.

Impact:
- Low, it only produce these error messages:
```
bash: unset: `"INFO:': not a valid identifier
bash: unset: `Starting."': not a valid identifier
```

Probability:
- High, it happens in each scan where this script is used.

Cost to fix it:
- The proposed solution in the description of this issue works and error messages disappear. Instead, it logs the expected message:
```
"INFO: Starting."
```
