### ISSUE TITLE
Potential integer underflow in remote code

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#9201]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Latest | Remoted| Manager/Agent | Packages/Sources | OS version |

Hello team,

After checking the remote code, we observed something that should be reviewed because it could incur an integer underflow. Specifically here: https://github.com/wazuh/wazuh/blob/master/src/remoted/secure.c#L77

After defining the size, and depending on the input value, the following can have a lower value: https://github.com/wazuh/wazuh/blob/master/src/remoted/secure.c#L477 For instance, with a buffer of  `!1234!`

**_Reported by Johannes Segitz of SUSE_**

Regards,

Miguel Casares

**Comment by cborla** [comment]
This issue applies only for TCP messages.

Impact:
> Low, It could try to process an invalid message. 

Probability
> Low, It depends on the message size, limit is OS_SIZE_65536. 

Cost to fix it:
> First case could be fixed changeing the variable type, from ssize_t to int (as nb_recv function returns). Exist a PR to test it (https://github.com/wazuh/wazuh/pull/9285)
> Second case should be extensively tested.
