### ISSUE TITLE
Adapt vulnerability detector and syscollector to allow on demand scans - Analysis

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#9219]
# Description

To improve the usability of Wazuh modules, it is required to allow the user a manual trigger of the following actions

- Vulnerability detector scan
- Vulnerability detector feed update
- Syscollector scan

# Requirements

Some general requirements are listed to begin the analysis:
- The user can request these actions from the API and the UI
- The user can select which agents will be scanned according to some filters
- The normal flow of these components will not be affected, and both mechanism will be available

At the end of this issue, a detailed list of tasks for these three goals has to be defined.

**Comment by palaciosjeremias** [comment]
### Button in the Wazuh UI to trigger a Vulnerability Detector scan

**Requirements**:
Implement a socket for vulnerability detector (probably owned by modulesd to allow in the future send message to any sub-module of modulesd).
Implement a way to wake up the scanning thread when a scan event comes from the socket.
Bear in mind that probably we will need to modify some Wazuh DB command to get the agents to be scanned (correlating the list of agents to be scanned received from the socket and the ones that should be scanned based on the Wazuh DB information). - What happens if an agent is not active? And what happens if we don't have the feed?
Design a set of return codes for the API.
Vulnerability Detector should receive a list with the agents' ids that have to be scanned. The Wazuh UI should provide a mechanism to create this list based on OS or groups.


**Tasks**
Below is a list of tasks that should be implemented to achieve this feature. The tasks are separated in the owner team of the tasks (Frontend, Framework and Core)

**FrontEnd**
-> Implement a dashboard of "actions" of VulDet.
-> Add a scan button, a stop button, and a status button.
-> Pressing the scan button will open a window (or new dashboard where you can build a list of agent IDs, check "full" or "baseline" and confirm the action.
-> Pressing stop or status will update the status in the GUI.
-> This list of agents will be sent together with the command
-> Implement filters so that the user gets a list of agent IDs using Groups, OS, Node, Agent Status, some regex.
-> This last screen will show the result of the command sent to VulDet
-> Documentation

**FrameWork**
-> Implement queries to send the following commands to queue/sockets/wmodules:
        run_task vulnerability-detector {"task":"scan", "status":"in_progress"}
        run_task vulnerability-detector {"task":"scan", "status":"in_progress", "unscanned_agents"::["001"]}
        run_task vulnerability-detector {"task":"scan", "status":"finished", "scanned_agents":["000","001","002"]}
        run_task vulnerability-detector {"task":"scan", "status":"busy", "reason":"scan in progress"}
        run_task vulnerability-detector {"task":"scan", "status":"busy", "reason":"update in progress"}
        run_task vulnerability-detector {"task":"scan", "status":"error", "reason":"invalid syntax"}
        run_task vulnerability-detector {"task":"scan", "status":"stoped"}
        run_task vulnerability-detector {"task":"update", "status":"in_progress"}
        run_task vulnerability-detector {"task":"update", "status":"finished"}
        run_task vulnerability-detector {"task":"update", "status":"stoped"}

**Core**
**T1-> Interface design:**
    - Define the format of the command, it should be something like
        run_task MODULE_NAME PAYLOAD
                            {"task": "scan", "type": "full", "agents": ["001", "002", "003"]}
                            {"task": "scan", "type": "partial", "agents": ["001", "002", "003"]}
                            {"task": "scan", "type": "stop"}
                            {"task": "scan", "type": "status"}
                            {"task": "update", "type": "start"}
                            {"task": "update", "type": "stop"}
                            {"task": "update", "type": "status"}

    - The method must be of type cJSON * (* event) (cJSON *);
    - Define the type of response to return to the API. Something like
        {"task": "scan", "status": "in_progress"}
        {"task": "scan", "status": "in_progress", "unscanned_agents" :: ["001"]}
        {"task": "scan", "status": "finished", "scanned_agents": ["000", "001", "002"]}
        {"task": "scan", "status": "busy", "reason": "scan in progress"}
        {"task": "scan", "status": "busy", "reason": "update in progress"}
        {"task": "scan", "status": "error", "reason": "invalid syntax"}
        {"task": "scan", "status": "stoped"}
        {"task": "update", "status": "in_progress"}
        {"task": "update", "status": "finished"}
        {"task": "update", "status": "stoped"}
    - Consider creating new files to fragment VulDet

**T2-> Create a new action in wmdules.c :: wmcom_dispatch () to handle Tasks and the method itself.**
    - Modify wm_context struct so that all modules have a run_task method to handle this action.
    - Modules that do not yet have an "event" method must be initialized to NULL.
    - The method has to parse the target module name and forward the payload to the appropriate module.
    - This task must be represented with a DEBUG log that reports the arrival of the command
    - Manual tests to validate the processing with the logs.

**T3-> Implement the body of the Task method that will be in charge of receiving the call from modulesd and parsing its payload.**
    - The method must be of type cJSON * (* event) (cJSON *);
    - It must handle the below actions:
        scan full
        partial scan
        scan stop
        scan status
        update
        update stop
        update status

    - This method will do a sanity check of the payload that has just arrived (valid event, with sub payload check if required)
    - This method should take an "update_scan"  mutex and launch the thread
    - This method should call the scan with a list of IDs obtained from the command
    - This method will return if it could process the task with the Task 1 codes
    - This method will use the structure with the result of the last scan to answer the commands that demand it.


**T4-> Implement a new thread, which is in charge of checking the VulDet time and launches the scan thread**
    - This method should take an "update_scan"  mutex and launch the thread
    - This thread will keep the timing logic of the current VulDet and will sleep until it hits the next event.
    - This method should obtain the list of agent IDs according to their connection status before launching the scan.


**T5-> Restructure wm_vuldet_run_scan so that there is an intermediate method that already has the list of agents before** collecting the rest of the info and starting the scan
    - Currently, wm_vuldet_collect_agents_to_scan searches for active agents and gets additional information on these agents in a single method.
    - Now wm_vuldet_collect_agents_to_scan should be renamed to wm_vuldet_collect_agents_info. It will do the same as before but it won't call wdb_get_agents_by_connection_status ()
    - wdb_get_agents_by_connection_status will be outside of wm_vuldet_collect_agents_info (if necessary, wrapped in another method) and will be executed only from the time method
    - The logic of filling scan_ctx must be moved to a point where the type of scan can be defined from the command received.


**T6-> Create a scan method, which is executed with a new thread worker.**
    - Before launching the thread, an update_scan mutex will be taken.
    - This thread will be launched from the method created to process event requests.
    - This thread is going to be launched from the method created to analyze the time.
    - This thread will return a status to the thread that executed it, saying the result of the scan (the report seems a lot to me)

**T7-> Implement a clean stop mechanism for the scan thread.**
    - Refactor to leave the cleans of the tables in a separate method. Callable at the stop of the thread.

**T8-> Create and manage a structure with the result of the last scan (Subject to analysis)**
    - This structure should have the status of the scan
        running, stopped, finished, error

**T9-> Pre-processing method of the agents to be scanned (Subject to analysis)**
    -Refactor wm_vuldet_collect_agents_info (ex wm_vuldet_collect_agents_to_scan) to validate if there is feed for that agent
    -Eliminate from the list those agents that cannot be scanned
    -Respond to the scan Task with unscanned_agents if necessary.

**T10-> UT**
    - Unitary test of the entire development
    - This implies reordering the UTs in new files.

**T11-> Integration test**
    - Do a set of tests for the commands that arrive at queue/sockets/wmodules

**T12-> Documentation**
    - Document the use of the buttons and the UI
    - Depends on FrontEnd development
 
 **Sequence Diagram**   
Below there is a sequence diagram of the communication between Wazuh API and WazuhModules when sending the run_task command that will trigger a scan on demand.
![Scan Button UI](https://user-images.githubusercontent.com/11434230/124678846-bd2ae680-de99-11eb-9f4f-f5de895a5216.png)

**Comment by MiguelazoDS** [comment]
## Description

As part of the new Syscollector feature that will allow executing scans on demand a description of what we consider is needed to achieve the final result is detailed below. \
This will be an additional feature to the actual behavior the module has, Syscollector as it is now will remain without changes other than the strictly necessary ones.

Starting from #9223 a set of issues, that are open to discussion, are listed below as part of the current proposal. These tasks involve the efforts of the Frontend, Framework, Core, Documentation, and QA team.

This new feature aims to perform a scan from the UI without the possibility to stop it, or perform the scan by OS. Also, a status request from the UI/API is not going to be considered. All the information about the status of the scan will be only possible to know by checking the agent's logs.

### Tasks

- #### Frontend

Implement a new section/tab with a selector button in the Wazuh UI to perform a system inventory scan through the API. The place where is best to put this new section will be decided by the Frontend team.

The implementation should take into account the following options:

- Scan specific agent or agents
- Scan agents per group
- Scan agents per node
- Scan agents

To easily select the agents that the user wants to scan, a filter should be implemented capable to skip those agents that are not wanted to be scanned.

This task should define how this information is sent to the API to better fit the already implemented infrastructure.

---

- #### Framework

Starting to the point that it should be possible to do a scan on all agents, a specific set of agents, all agents per node, or all agents per group. \
Implement the endpoint or set of endpoints that would be capable to do the task. \
The property "action" should be parametrized in case new actions would be needed in the future besides a "scan".

According to the Frontend requirements, the API should be able to perform a:

Scan on specific agents \
i.e. PUT /agents/{agent_id}/syscollector/{action}

Scan on agents in specific group \
i.e. PUT /agents/group/{group_id}/syscollector/{action}

Scan on agents in specific node \
i.e. PUT /agents/node/{node_id}/syscollector/{action}

Scan on all agents \
i.e. PUT /agents/syscollector/{action}

Also, a response about whether the scan was successfully launched or not should be visualized through the UI.

Complete the documentation about this new implementation in the Restful API section.

---

- #### Documentation

An additional description should be added in the Syscollector tab in the capabilities section about the new feature that performs scans on demand. \
A good approach would be to create another subsection in the link below. \

https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html

It should describe how to proceed to trigger the scan and the rationale. \
It would be desirable to complement the description with a typical use case of this new feature.

---

- #### Core (Agentd)

Implement a function that parses that incoming message from the manager (remoted), to properly format a message that will be sent to the wm_com (wazuh modules socket). \
Take into account that this socket is used by several modules that are part of Wazuh modules. \
There is an already Syscollector conditional needed for the synchronization between the manager and the agent that could be used for this purpose.

---

- #### Core (Wazuh-modules)

The message from the receiver sent to the socket of the Wazuh modules is captured by a function (wmcom_dispatch) available for all Wazuh modules. \
Similar to the tasks related to the vulnerability detector, a new action should be implemented in wmcom_dispatch.

---

- #### Core (Syscollector)

The actual thread, which is in charge of checking the time interval should be now split to have another thread that performs the scan itself. \
The actual thread should take a "update_scan" mutex before launch the scan thread. \
The mutex should be implemented as part of this task. \
The actual thread will keep the timing logic of the current system inventory scan and will sleep until it hits the next event. This next event could be either scan triggered by time interval or scan on demand.

---

- #### Core (Syscollector)

Implement the function run_task that resides inside the wm_context structure for Syscollector. \
Also to be coherent with the previous analysis should be cJSON * (* event) (cJSON *), and should be able to perform the Syscollector scan based on what is declared in the ossec.conf file. \
This method will do a sanity check of the payload that has just arrived (valid event, with sub payload, check if required). \
This method should take a "update_scan" mutex and launch the thread. \
A possible approach would be to increase the capabilities of the already implemented method wm_sync_message(). \
A new thread capable to scan the agent system must be implemented as part of this task. \

---

- #### Core (UTs)

It would be desirable to implement a couple of tests cases that demonstrate the execution of the Syscollector scan after an API query. \
It would be interesting to consider:
  - Message format of the components involved in the process.
  - That the mutex logic does how it is supposed to do in case of concurrent events.
  - Actions that threads will take in case the mutex is taken.
  - ...

---

- #### QA Integration Test

Integration test should be considered once the actual, and underdevelopment, integration test work reaches a stable state. \
The new Syscollector integration test should be capable to:
- Verify the agents' database integrity in case a scan is triggered by different methods.
- Verify that the logs are coherent and give an understandable state of the system.
- ...

**Comment by pereyra-m** [comment]
# Run a feed update on demand

This set of tasks would allow the user to run a vulnerability detector feed update on demand, without losing the current mechanism of interval. This analysis considers that the previous task "Button in the Wazuh UI to trigger a vulnerability detector scan" already has given to the **modulesd** daemon the possibility to receive messages for Vulnerability Detector. 

# Description

Basically, `wm_vuldet_main()` has three components: `wm_vuldet_run_update()`, `wm_vuldet_run_scan()` and `wm_vuldet_run_sleep()`. It is necessary that the main thread wakes up regularly to check the new socket for pending messages. The `wm_vuldet_run_update()` method requires minor changes. At least, the following commands should be implemented. The estimation considers that all feeds are going to be updated (it isn't possible to choose only a few):

- Run update
- Get status

After the update finishes, the module could query the Wazuh-DB tables **NVD_METADATA** and **METADATA** to get the current and new **TIMESTAMP** and **LAST_UPDATE** column values:
- The **TIMESTAMP** value correspond to the vendor version, a change in this column implies new data.
- **LAST_UPDATE** is the time of the last call to `wm_vuldet_run_update()`. A change here indicates a successful run.

 # Tasks 

- Task 1: 2SP
    * Modify the run_update method 
    * Create a thread to run an update on demand (using mutex logic)
    * Manual validation

- Task 2: 2SP
    * Modify the current vulnerability detector logic, to call the wm_vuldet_run_update() on interval and using the mutex logic

- Task 3: 3 SP
    * The commands have to be defined
    * Implement the parsing logic for the vulnerability detector socket 
    * Create the methods to receive the commands (run and status)
    * In case of a "run update" action, a worker thread is launched
    * Manual validation
    
- Task 4: Pending estimation 
    * Consider the "stop" command in the update process (this behavior must de defined)
    
- Task 5: 3SP
    * Add the new buttons to the documentation
    
- Task 6: 3SP
    * Adapt UT if needed 
    * Create UT for new features
    
- Task 7: Pending
    * Create new IT for this feature 
    
- Task 8: Pending
    * Exploratory
