### ISSUE TITLE
Improve the vulnerability detector module to allow a feed update on demand

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#9221]
# Description

Currently, the vulnerability detector module performs a feed update only every certain time interval.
This issue would give the user the possibility of requesting an update at anytime.

This analysis began in #9219.
This issue requires #9220.

# Requirements

Once the vulnerability detector module is capable of receiving messages, this issue must:
- Add the command for feed update, all of them or just a few
- Add the command for querying the status of the task 
- Add the command for retrieving the feed timestamp (version)

**Comment by DProvinciani** [comment]
Closing the issue as this is going to be implemented as part of the epic https://github.com/wazuh/wazuh/issues/9220.
