### ISSUE TITLE
Decoders and Rules for FortiNet Products

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh#9230]
Hello Team!

## Request: FortiDDOS
I am looking for a set of decoders and rules for FortiDDOS.
**Device Information**
|Vendor |Modelo|OS
|---|---|---|
|Fortinet| FortiDDoS 400B|FI400B v5.4.1,build0255,201222|

It is needed to create the decoders and rules based on the following article from the vendor: https://help.fortinet.com/fddos/4-3-0/FortiDDoS/log_ref.htm

### Sample
```
2021-05-27T23:59:59.998837-03:00 12.34.56.78 devid=XXXXXXXXX date=2021-05-28 time=00:00:00 tz=ART type=attack spp=4 evecode=2 evesubcode=27 description="TCP invalid flag combination " dir=1 protocol=6 sip=0.0.0.0 dip=12.34.56.79 dropcount=30 subnetid=95 facility=Local0 level=Notice direction=inbound spp_name="YYYYY" subnet_name="ZZZZZ" sppoperatingmode=detection 
```

## Request: FortiGate
I am looking for a set of decoders and rules for FortiGate
|Vendor |Modelo|OS
|---|---|---|
|Fortinet| FortiGate 500D|v6.4.5 build1828 (GA)|

**Reference:** [FortiOS_6.4.5_Log_Reference.pdf](https://github.com/wazuh/wazuh/files/6787254/FortiOS_6.4.5_Log_Reference.pdf)

### Sample
```
2021-07-08T12:16:15.792380-03:00 192.168.20.176 date=2021-07-08 time=12:16:16 devname="XXXXXXXXXX" devid="ZZZZZZZ" eventtime=1625757376533171154 tz="-0300" logid="0105048038" type="event" subtype="wad" level="error" vd="YYYYYYYYY" logdesc="SSL Fatal Alert received" session_id=2ac6e9c7 policyid=0 srcip=11.22.33.44 srcport=53764 dstip=22.33.44.55 dstport=443 action="receive" alert="2" desc="bad certificate" msg="SSL Alert received"
```

## Request: FortiMail
I am looking for a set of decoders and rules for FortiMail.
**Device Information**
|Vendor |Modelo|OS
|---|---|---|
|Fortinet| Fortimail VM04|v6.4.5(GA), build453, 2021.06.09|

**Reference:** [FortiMail-6.4.0-Log_Reference.pdf](https://github.com/wazuh/wazuh/files/6787258/FortiMail-6.4.0-Log_Reference.pdf)

### Sample
```
2021-07-08T13:45:20.966330-03:00 10.132.128.10 date=2021-07-08 time=13:45:21.846 device_id=XXXXXXXX log_id=0200027993 type=statistics pri=information  session_id="168GjLEk027992-16027992" client_name="" client_ip="11.22.33.44" client_cc="ZZ" dst_ip="12.34.56.78" from="noreply@domain.com" hfrom="noreply@domain.com" to="user@gmail.com" polid="2:2:5:SYSTEM" domain="HHHHHHHH" mailer="mta" resolved="FAIL" src_type="int" direction="out" virus="" disposition="Accept" classifier="Not Spam" message_length="23951" subject="Subject of the message" message_id="896710244.116204.16257.Mail@lnk2489" recv_time="" notif_delay="0" scan_time="0.008128" xfer_time="0.005643" srcfolder="" read_status=""
```

Thank you in advance!

**Comment by dariommr** [comment]
Hi Guys,
I made this set of rules based on the document provided before: [fortiddos-rules.xml.txt](https://github.com/wazuh/wazuh/files/6785969/fortiddos-rules.xml.txt)
I set up different groups based on the layer it belongs and the category defined in the document.
Let me know if it can be enhanced or changed.
Thanks again!

**Comment by dariommr** [comment]
Hi Guys,
I made this set of rules based on this [document](https://help.fortinet.com/fa/faz50hlp/56/5-6-7/Content/FMG-FAZ/2200_Events/0200_Event_handlers/0400_Predefined_event_handlers.htm) having in mind these parameters for the rules:
Severity Correlation:
```
    Critical: Level 10
    High    : Level 7
    Medium  : Level 5
    Low     : Level 3
```
    
Groups Correlation:
```
    Event Category
    Log Type
```

This is the rules file: [fortigate-rules.xml.txt](https://github.com/wazuh/wazuh/files/6888244/fortigate-rules.xml.txt)

Let me know if it can be enhanced or changed.
Thanks again!

**Comment by dariommr** [comment]
Hello Guys,
I made this set of rules for FortiMail based on this [document](https://fortinetweb.s3.amazonaws.com/docs.fortinet.com/v2/attachments/f7868f9d-b70f-11ea-8b7d-00505692583a/FortiMail-6.4.0-Log_Reference.pdf) having in mind these parameters for the rules:
Severity correlations
```
    0 Emergency   Level 13
    1 Alert       Level 10
    2 Critical    Level 7
    3 Error 	  Level 5
    4 Warning 	  Level 3
    5 Notice 	  Level 0
    6 Information Level 0
```
Group Correlations:
```
    Log Type
    Log Subtype
```
This is the rules file: [fortimail-rules.xml.txt](https://github.com/wazuh/wazuh/files/6933415/fortimail-rules.xml.txt)
Let me know if it can be enhanced or changed.
Thanks again!

**Comment by beachcondo93** [comment]
@dariommr Hey Dario, what you made was almost perfect. It did everything but parse out the URL and Hostname fields for my FortiGate logs. 

To remedy this, I added this to my FortiGate-decoders file that you originally made. Thank you for creating this!

`
<decoder name="forti-like-child">
   <parent>forti-like</parent>
   <regex>hostname="(\.*)"|hostname=(\.*)\s|hostname=(\.*)$</regex>
   <order>hostname</order>
</decoder>

<decoder name="forti-like-child">
   <parent>forti-like</parent>
   <regex>url="(\.*)"|url=(\.*)\s|url=(\.*)$</regex>
   <order>url</order>
</decoder>
`

**Comment by beachcondo93** [comment]
> @dariommr Hey Dario, what you made was almost perfect for my usage. It did everything but parse out the URL and Hostname fields for my FortiGate logs.
> 
> To remedy this, I added this to my FortiGate-decoders file that you originally made. Thank you for creating this!
> 
> ```
> <decoder name="forti-like-child">
>    <parent>forti-like</parent>
>    <regex>hostname="(\.*)"|hostname=(\.*)\s|hostname=(\.*)$</regex>
>    <order>hostname</order>
> </decoder>
> 
> <decoder name="forti-like-child">
>    <parent>forti-like</parent>
>    <regex>url="(\.*)"|url=(\.*)\s|url=(\.*)$</regex>
>    <order>url</order>
> </decoder>
> ```

Ok, the only thing I seem to be missing now is the status codes

```
2021-08-31 23:55:07 W3SVC2 hq-rms-01 10.18.1.202 GET /api/url/Get - 443 - xx.xx.xx.xx HTTP/1.1 Mozilla/5.0+(iPhone;+CPU+iPhone+OS+14_7_1+like+Mac+OS+X)+AppleWebKit/605.1.15+(KHTML,+like+Gecko)+Version/14.1.2+Mobile/15E148+Safari/604.1 - https://somewebsitename.com 401 0 0 320 1950 0
```

**Comment by beachcondo93** [comment]
Actually, looks like its not deciding the  ```user=""``` field still.

**Comment by dariommr** [comment]
Hello @beachcondo93 
It is possible, but currently, I do not have samples to test it, could you please share some log samples to test this again?
Thank you in advance!

**Comment by beachcondo93** [comment]
> Hello @beachcondo93
> It is possible, but currently, I do not have samples to test it, could you please share some log samples to test this again?
> Thank you in advance!

I added another regex to the FortiGate decoder to extracts the users. This is now working for me. 

```
<decoder name="forti-like-fields">
  <parent>forti-like</parent>
  <regex>user="(\S+)"</regex>
  <order>user</order>
</decoder>
```

**Comment by beachcondo93** [comment]
> Hello @beachcondo93
> It is possible, but currently, I do not have samples to test it, could you please share some log samples to test this again?
> Thank you in advance!

If you want a sample, here is a fresh one. 
```
date=2001-01-01 time= devname="" devid="FGT1" eventtime=1 tz="-0500" logid="1" type="utm" subtype="app-ctrl" eventtype="signature" level="information" vd="root" appid=4 user="firstname.lastname" authserver="authserver" srcip=1.1.1.1 dstip=1.1.1.1 srcport=1 dstport=1 srcintf="lan" srcintfrole="lan" dstintf="wan1" dstintfrole="wan" proto=6 service="SSL" direction="outgoing" policyid=1 sessionid=1 applist="block-high-risk" action="pass" appcat="Collaboration" app="Microsoft.Portal" hostname="" incidentserialno=1 url="/" msg="Collaboration: Microsoft.Portal," apprisk="elevated" scertcname="" scertissuer=""
```

**Comment by dariommr** [comment]
Hello @beachcondo93 
It seems it is decoding without any issues the `user`, but have in mind it is being decoded as `srcuser`, take a look:
```
**Phase 2: Completed decoding.
        name: 'forti-like'
        actn: 'pass'
        appcat: 'Collaboration'
        devid: 'FGT1'
        devname: '" devid='
        direction: 'outgoing'
        dstintf: 'wan1'
        dstintfrole: 'wan'
        dstip: '1.1.1.1'
        dstport: '1'
        eventtime: '1'
        level: 'information'
        logid: '1'
        msg: 'Collaboration: Microsoft.Portal,'
        policyid: '1'
        protocol: '6'
        service: 'SSL'
        sessionid: '1'
        srcintf: 'lan'
        srcintfrole: 'lan'
        srcip: '1.1.1.1'
        srcport: '1'
        srcuser: '"firstname.lastname"'
        subtype: 'app-ctrl'
        type: 'utm'
        tz: '-0500'
        vd: 'root'

**Phase 3: Completed filtering (rules).
        id: '403150'
        level: '0'
        description: 'FortiGate: UTM logs'
        groups: '['fortigate', 'utm']'
        firedtimes: '1'
        mail: 'False'
```

As you can see, it matches rule `403150` which is `level 0`, that level of rule, does not generate alerts, so you can manage to write some child rules.

Please let me know if I missed something.

**Comment by jcruzlp** [comment]
## Progress update

Having problems running the `runtest.py` test after merging all the txt files into one.
I'll try to split them into three different files for decoders and rules, but adding the FortiGate rules and decoders to our current ones.
