### ISSUE TITLE
[Syscollector module] create functionality diagrams

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#9305]
|Working branch|
|---|
|Functional diagrams: [9305-syscollector-functional-diagrams](https://github.com/wazuh/wazuh/tree/9305-syscollector-functional-diagrams)|
|Detailed diagrams: [9305-syscollector-detailed-diagrams](https://github.com/wazuh/wazuh/tree/9305-syscollector-detailed-diagrams)|

This issue aims to add function sequence diagrams of syscollector.

### Functional diagrams
![wm_syscollector](https://user-images.githubusercontent.com/1791430/128266866-3873bdd0-05e4-44c0-b718-9b366db7347f.png)
![syscollector-scan-sync](https://user-images.githubusercontent.com/1791430/128267083-5a8b90ec-56b0-410a-9dcb-01f1558e778d.png)

### Detailed diagrams
SyscollectorImp:
- [x] high level diagram (init, push and destroy calls) - @konangc87 
- [x] processes diagram (scan and sync) @konangc87 
- [x] ports diagram (scan and sync) - @konangc87 
- [x] network diagram (scan and sync) @konangc87 
- [x] packages diagram (scan and sync) @jnasselle 
- [x] os diagram (scan and sync) @konangc87 
- [x] hardware diagram (scan and sync) @konangc87 

wm_syscollector:
- [x] high level diagram (main, dump, stop, destoy, push) @konangc87 @jnasselle

**Comment by jnasselle** [comment]
## High level diagram
![sequence-syscollector](https://user-images.githubusercontent.com/1791430/126242560-adaa4823-bbd4-4337-844b-a5d68cccebb4.png)

## Processes diagram
![processes](https://user-images.githubusercontent.com/1791430/126242651-7a5f267d-e8a6-4d87-aa93-07c41f7d8e0a.png)

## Ports diagram
![ports](https://user-images.githubusercontent.com/1791430/126242672-06148e1e-97b4-46b2-acf4-0a49c1a65221.png)

## Network diagram
![network](https://user-images.githubusercontent.com/1791430/126242532-ebafcdf0-1bac-4be0-877f-0e67162be347.png)

## Packages diagram
![packages](https://user-images.githubusercontent.com/1791430/126242693-f75d7153-b029-46b7-8d22-d81dbcf83f9c.png)

## Os diagram
![os](https://user-images.githubusercontent.com/1791430/126242708-5526159c-c441-4594-9384-b855aaf93fd3.png)

## Hardware diagram
![hardware](https://user-images.githubusercontent.com/1791430/126242518-f0703bda-0246-45ce-b1f5-80ea2a654722.png)

**Comment by konangc87** [comment]
## Functional diagram
![syscollector-funcionality](https://user-images.githubusercontent.com/54002291/127342288-0fe900ab-d926-4750-a734-e94857bb8e14.png)
