### ISSUE TITLE
[Syscollector module] create features description

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#9306]
## Description
This issue aims describe the features involved as part of the work of Syscollector module memory analysis.

## DoD
- [x] Describe, appropriately, the features involved.

**Comment by tinachoB** [comment]
![image](https://user-images.githubusercontent.com/22640902/126719756-705bffe8-5a6f-430d-9ab1-d6a65b3e541a.png)


Changes have been made in branch: `9305-syscollector-functional-diagrams` [commit](https://github.com/wazuh/wazuh/commit/bc36eb9e85fe45d3bf343730fb5656f1acc82209)

**Comment by Dwordcito** [comment]
Approved, the work here it is finished, I close the issue and it will merge based on the review of the other PR #9305
