### ISSUE TITLE
Database is locked using Vulnerability Detector

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh#9309]
## Description

While executing the tests related to the `download feed of NVD`, we can detect that some errors are showing in `ossec.log`. 
I attach [ossec.log](https://github.com/wazuh/wazuh/files/6809306/ossec.log), and each description about how was tested.

## Packages Details

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm

### Environment 

Provider| Box| OS| CPU| Memory | 
--|--|--|--|--|
Vagrant | centos/8 | CentOS 8 | 2 | 1024 |

## Steps:

1. Set ossec.conf to download feeds of NVD from 2002 or with test you can do it:
```
 'nvd': {
        'os': [],
        'update_from_year': 2002,
        'system_log': 'National Vulnerability Database',
        'download_timeout': 1800
```

2. Set local_internal_option.conf with:
    ```
    wazuh_modules.debug=2
    monitord.rotate_log=0
    wazuh_db.debug=2
    ```
3. Restart `wazuh-manager` <systemctl restart wazuh-manager>
4. Execute test: `test_feeds/test_download_feeds`.

## Actual Behavior:

4. Finish downloading the last version successfully.
![imagen](https://user-images.githubusercontent.com/3978434/125458572-61fae7c2-4de9-416c-b510-cbbbf929b851.png)

5. Found some problems on `ossec.log` after downloading the last version ( it was for 40 minutes):
-  Exceeded the maximum number of attempts to access the DB.
- Database is locked.
- Unable to connect to socket 'queue/db/wdb'
![imagen](https://user-images.githubusercontent.com/3978434/125459107-15840e1e-8287-4052-b0a6-8e96f9d4eefb.png)

## Expected Behavior:
 4. Finish downloading the last version successfully. 
 5. Not find any error in `ossec.log` after downloading the last version
 
 
 
## Note: 
- I suggest you test it using the test modifying it like I described because the error is more frequent, when you do it manually they only happen a few times.
- It also affects tests of `wazuh-qa` :  (sometimes, the tests fails because the database is locked)
  | Path | Logs | 
  |--|--|
  |test_feeds/test_invalid_type_url_feeds| [YellowResultsInvalidTypeURLFeed.log](https://github.com/wazuh/wazuh/files/6856469/YellowResultsInvalidTypeURLFeed.log)
  |test_scan_results/test_redhat_inventory_redhat_feed | [YellowResultsScanRedhatInventoryFeed.log](https://github.com/wazuh/wazuh/files/6857621/YellowResultsScanRedhatInventoryFeed.log)

- In this [issue ](https://github.com/wazuh/wazuh-qa/issues/1531) you can see a research and a lot of logs execution with this fails. This error affect ours test executions.

- When I execute all suite of Vulnerability Detector Tests I can see the error on this tests: 
         - test_scan_results/test_ubuntu_inventory_canonical_feed
         - test_scan_results/test_redhat_inventory_redhat_feed
         - test_scan_results/test_debian_inventory_debian_feed 
   But If I execute only these tests no happens.

**Comment by damarisg** [comment]
I saw on Slack a [community ](https://wazuh.slack.com/archives/C0A933R8E/p1626306273169800) related to a message of `DataBase is locked`.

**Comment by cborla** [comment]
I couldn't reproduce it running it manually. 
In other hand, running QA integration test, messages like "Exceeded the maximum number of attempts to access the DB" and "SQL error: 'database is locked'" are show, but we consider, these errors are highly related to outside access to the Wazuh databases, triggering several race condition errors. 
As reported issue describes, a suspicious behavior could be hidden in some cases. I estimated that once QA tests were refactored, it will not be possible to reproduce reported errors.

Manually test:

-     Ubuntu 20.
-         VM 1:
-             NVD 'update_from_year': 2002
-             Default settings
-         VM 2:
-             NVD 'update_from_year': 2002
-             Stressfull settings: 
-                 10s interval. 
-                 10s ignore time.
-     Centos 8
-         VM 1:
-             NVD 'update_from_year': 2002
-             Default settings
-         VM 2:
-             NVD 'update_from_year': 2002
-             Stressfull settings: 
-                 5s interval. 
-                 5s ignore time.


It's necessary change external access method DB from wazuh-qa.

Samples: 

```
CVE_DB_PATH = f"{WAZUH_PATH}/queue/vulnerabilities/cve.db"

def load_db(db_path):
    """Load a database in db_path

    Args:
        db_path (str): path to the database
    """
    conn = sqlite3.connect(CVE_DB_PATH)      <--------
    cursor = conn.cursor()
    return conn, cursor

```

And replace it with wazuh_db friendly methods, like wazuh_db.py:

```
def query_wdb(command):
    """Make queries to wazuh-db using the wdb socket.

    Args:
        command (str): wazuh-db command alias. For example `global get-agent-info 000`.

    Returns:
        list: Query response data
    """
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    sock.connect(WAZUH_DB_SOCKET_PATH)

    data = []

    try:
        sock.send(wazuh_pack(len(command)) + command.encode())

        rcv = sock.recv(4)

        if len(rcv) == 4:
            data_len = wazuh_unpack(rcv)

            data = sock.recv(data_len).decode()

            # Remove response header and cast str to list of dictionaries
            # From --> 'ok [ {data1}, {data2}...]' To--> [ {data1}, data2}...]
            if len(data.split(' ')) > 1:
                data = json.loads(' '.join(data.split(' ')[1:]))
    finally:
        sock.close()

    return data
```

**Comment by snaow** [comment]
I am reopening the issue. 
The error was reported in QA tests design for Wazuh version 4.2 and earlier, at that time, Vulnerability Detector is not using `wazuh-db` daemon to manage the databases. 

In the sample you mention the DB `{WAZUH_PATH}/queue/vulnerabilities/cve.db` is accessed directly by `wazuh-modulesd:database`.

**Comment by snaow** [comment]
The issue will be handled internally by @wazuh/qa. 

The tests should not access `.db` files that are already open and belongs to another daemon.

For some use cases:

- we can not modify the databases when the daemon is stopped
- we can not access the db when the daemons are running- 
- we don't have an interface (like `wazuh-db`) to handle queries

For these cases, we will either remove the test or mark it as blocked until we have a valid interface to manage the dbs.
