### ISSUE TITLE
Internal error in `modulesd:oscap` in stress tests logs

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#9311]
Hello!

I found the following error in `wazuh-modulesd:oscap` while checking the stress tests logs, I have found it in both `4.2.0` and `4.1.5`:

- 4.2.0
  - Issue: https://github.com/wazuh/wazuh-jenkins/issues/2688#issue-940591748
  - Jenkins build: https://ci.wazuh.info/job/Test_stress/1639/
  - Target: Manager 4.2.0
  - Revision: 0.4.2
  - Repository: packages-dev.wazuh.com
  - Package path: warehouse/branches/4.2/

- 4.1.5
  - Issue: https://github.com/wazuh/wazuh-jenkins/issues/2675#issuecomment-878201860
  - Jenkins build: https://ci.wazuh.info/job/Test_stress/1702/
  - Target: Manager 4.1.5
  - Revision: 0.fix.ar
  - Repository: packages-dev.wazuh.com
  - Package path: warehouse/branches/4.1/

Error:

![image](https://user-images.githubusercontent.com/14913942/125837248-43d2d551-6f7f-43ff-8632-f7c9e4bbd039.png)

**Comment by davidjiglesias** [comment]
New versions have resolved this problem

**Comment by vikman90** [comment]
@rauldpm @davidjiglesias @QU3B1M OpenSCAP is deprecated as of 4.0.0, the logic code was removed:
- #10900

Please check the history:
1. [Jul 11, 2023] Added to the project.
2. [Jul 11, 2023] Marked as blocked by management.
3. [Jul 17, 2023] Dismissed to fix.
