### ISSUE TITLE
Move pre-compiled python to AWS DEV account

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh#9327]
Hi team,

To operate, the API, the framework, and the cluster require to have Python installed and all the requirements. To simplify and speed up the Wazuh installation process we compile Python and install all the necessary deps to finally embed them in the Wazuh package.

In this issue we are looking to modify the sources directory and the Python pre-compile to a development account in AWS, this way, if any error occurs with the Python package, it will not arrive at production, overwriting the previous package.

Regards

**Comment by CarlosRS9** [comment]
# Status update

A new bucket named `framework-python` has been created in Wazuh-dev environment. The following structure has been migrated from production environment to dev:

```
framework-python/
    deps/
        14/
            precompiled_cpython/
                aarch64/
                    cpython.tar.gz
                amd64/
                    cpython.tar.gz
            sources/
                cpython.tar.gz
```
