### ISSUE TITLE
Add support for non case-sensitive values when matching CDB list values

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh#9336]
**Description**

The goal of this issue is to add the possibility of using non-case-sensitive values when matching CDB list values. 

For example, when creating an allowlist of packages, Windows packages can contain lowercase and uppercase letters for the same package.

Since we need an exact match, we need to know exactly the value we will match beforehand, and sometimes this is not possible.

Another possibility that may solve this is this one: https://github.com/wazuh/wazuh/issues/6893

Regards,

Miguel Casares

**Comment by havidarou** [comment]
#6893 with PCRE will allow us to create a regex for case insensitive use cases. Closing this in favor of the aforementioned issue.
