### ISSUE TITLE
Fix MITRE endpoints returning wrong `external_id` out of references

### ISSUE THREAD

**Issue by gabiwassan** [wazuh/wazuh#9348]
|Wazuh version|Component|
|---|---|
| 4.3.x | API |

| Related to | #8879 |
|---|---|

**Description**

It was detected that the API responses for some MITRE resources are returning `external_id` of an unexpected type, which is not correct.
Only items from MITRE should be returned.

![image](https://user-images.githubusercontent.com/11060558/126342224-831601ba-8cf9-44b7-93f2-ab4fb22666ee.png)

**Comment by mcarmona99** [comment]
## Checks

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)


### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)
