### ISSUE TITLE
Force ignoring certain directories regarding syscheck and /var/ossec

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#937]
Hello, if you configure syscheck to check `/var/ossec/` in real time we must ignore certain directories such `/var/ossec/logs/` due to obvious reasons.

This applies not only for `/var/ossec/`. We must check this use case when using the next paths:

- `/var/ossec/`
- `/var/`
- `/`
- If installed in `/opt` same as `/var/ossec`

Regards,
Jesús

**Comment by snaow** [comment]
Hi,

What if a user wants to monitor those files explicitly? I believe it is better to give every user the possibility to decide what to monitor or what to exclude.
For the use case you mention, you can use ignore or restrict statements to exclude log files when using FIM in /var/ossec or even globally.

```
<ignore type="sregex">$.log</ignore>
<directories check_all="yes" restrict="!$.log">/var/ossec</directories>
```
Something to keep in mind is, there are no only log files which can change too frequent, there other internal files as ossec-agent.state that can change a lot as well in a short period of time.

Regards,
Pedro.
