### ISSUE TITLE
Cannot create socket when installing Wazuh into other directories different from /opt or /var

### ISSUE THREAD

**Issue by cristgl** [wazuh/wazuh#939]
With SELinux in enforcing mode and Wazuh installed into other directories different from /opt or /var, the socket needed for 'whodata' won't create. This is due to the .te file, which only works when Wazuh is installed into one of this two directories.

**Comment by vikman90** [comment]
Fixed in https://github.com/wazuh/wazuh/pull/938.
Thx @cristgl !!
