### ISSUE TITLE
Wazuh & Open Distro future

### ISSUE THREAD

**Issue by a108a108** [wazuh/wazuh#9397]
Hello,

since Open Distro will not continue to keep pace with Elasticsearch releases and work only up to version 7.10. Does that mean that future releases of Wazuh just won't work with Open Distro ? In general how does the Elasticsearch & Kibana license changes (from January 2021) affect Wazuh?

Sorry, if it was answered previously!

**Comment by s-ocando** [comment]
As the [Open Distro for Elasticsearch](https://opendistro.github.io/for-elasticsearch/) project has been archived and succeeded by OpenSearch, Wazuh now includes two OpenSearch-based components: the Wazuh indexer and the Wazuh dashboard.

The Wazuh indexer is an [Opensearch](https://github.com/opensearch-project/OpenSearch) distribution with additional tools that our team has developed to assist with the installation and configuration of the search engine. On the other hand, the Wazuh dashboard is a customized [OpenSearch Dashboards](https://github.com/opensearch-project/OpenSearch-Dashboards) distribution that includes the [Wazuh plugin](https://github.com/wazuh/wazuh-kibana-app).

These new components were included to improve the user experience and to facilitate the management of the Wazuh solution.
Nevertheless, Wazuh continues to support Elastic Stack and Open Distro for Elasticsearch. Check out this blog post to learn more: [Introducing Wazuh 4.3.0](https://wazuh.com/blog/introducing-wazuh-4-3-0/)
