### ISSUE TITLE
Real manager configuration

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#941]
Hello team, if you modify `cluster.name` in the ossec.conf but **not** restarting the manager the Wazuh API is showing false information (just reading the ossec.conf file). Then if you go to Kibana app a refresh the manager information, you'll have the new name but it's not being applied. This ends applying a `cluster.name` filter in Kibana and not showing alerts.

Is there a way to get the real configuration from the manager?

Regards,
Jesús

**Comment by vikman90** [comment]
Hi @jesusgn90,

This issue is related to https://github.com/wazuh/wazuh/issues/450 (PR https://github.com/wazuh/wazuh/pull/548). This feature will allow querying the currently applied configuration of any component of the agents and the manager.

Best regards.

**Comment by TJOSERAFAEL** [comment]
PR https://github.com/wazuh/wazuh/pull/548 merged to 3.7
