### ISSUE TITLE
opnSense / suricata logs do not show up in Wazuh

### ISSUE THREAD

**Issue by rschueler** [wazuh/wazuh#9421]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | syslog | Manager| vmware OVA | Centos |

Hi.

I've connected the opnSense firewall via remote syslog and want the Suricata messages to show up in Wazuh. 
The messages show up on my Wazuh manager in `/var/ossec/logs/archives/archives.log`. Here is an example:

`2021 Jul 29 09:40:53 OPNsense ->192.168.0.1 Jul 29 11:40:53 OPNsense suricata[20064]: {"timestamp": "2021-07-29T11:40:53.381953+0200", "flow_id": 1422765758731265, "in_iface": "re0", "event_type": "alert", "vlan": [99], "src_ip": "192.168.99.187", "src_port": 39462, "dest_ip": "198.49.23.144", "dest_port": 443, "proto": "TCP", "alert": {"action": "allowed", "gid": 1, "signature_id": 90159034, "rev": 1, "signature": "ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)", "category": "A Network Trojan was Detected", "severity": 1, "source": {"ip": "198.49.23.144", "port": 443}, "target": {"ip": "192.168.99.187", "port": 39462}, "metadata": {"first_seen": ["2021_07_09"], "confidence_level": ["100"]}}, "flow": {"pkts_toserver": 1, "pkts_toclient": 0, "bytes_toserver": 78, "bytes_toclient": 0, "start": "2021-07-29T11:40:53.381953+0200"}, "payload_printable": "", "stream": 0}`

This is not plain JSON, so I created a custom decoder OpnsenseSuricata_decoders.xml to strip away the first part of the message:
```xml
<decoder name="json">
  <prematch>suricata[\d+]: </prematch>
  <plugin_decoder offset="after_prematch">JSON_Decoder</plugin_decoder>
</decoder>
```

This looks also good, because when  I copy paste the above message to `/var/ossec/bin/wazuh-logtest` I receive a nice parsed alert, but I am not able to find any events with rule.id = 86601 in the frontend. The messages aso do not show up in `/var/ossec/logs/alerts/alerts.log`. What is wrong?

```
*Phase 1: Completed pre-decoding.
        timestamp: '2021 Jul 29 09:40:53'

**Phase 2: Completed decoding.
        name: 'json'
        alert.action: 'allowed'
        alert.category: 'A Network Trojan was Detected'
        alert.gid: '1'
        alert.metadata.confidence_level: '['100']'
        alert.metadata.first_seen: '['2021_07_09']'
        alert.rev: '1'
        alert.severity: '1'
        alert.signature: 'ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)'
        alert.signature_id: '90159034'
        alert.source.ip: '198.49.23.144'
        alert.source.port: '443'
        alert.target.ip: '192.168.99.187'
        alert.target.port: '39462'
        dest_ip: '198.49.23.144'
        dest_port: '443'
        event_type: 'alert'
        flow.bytes_toclient: '0'
        flow.bytes_toserver: '78'
        flow.pkts_toclient: '0'
        flow.pkts_toserver: '1'
        flow.start: '2021-07-29T11:40:53.381953+0200'
        flow_id: '1422765758731265.000000'
        in_iface: 're0'
        proto: 'TCP'
        src_ip: '192.168.99.187'
        src_port: '39462'
        stream: '0'
        timestamp: '2021-07-29T11:40:53.381953+0200'
        vlan: '[99]'

**Phase 3: Completed filtering (rules).
        id: '86601'
        level: '3'
        description: 'Suricata: Alert - ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)'
        groups: '['ids', 'suricata']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

**Comment by obnys** [comment]
Greetings,
my guess would be `level: '3'`
I was wondering why /var/ossec/rulesets/rules/0475-suricata_rules.xml only has the loglevels 0 and 3. That way an alert won't be triggered by default.

**Comment by nmkoremblum** [comment]
Hi @rschueler!

First of all, as an advice, it would be better for you to check the logs on the `archives.json` instead of the `.log` as it shows the boundaries of the events well defined.

In this case, the log starts as `Jul 29 11:40:53 OPNsense suricata[20064]: {"timestamp": "2021-07-29T11:40:53[...]`, the previous information is added by wazuh when storing the log. Because of this, the pre-decoder extracts the program name as "suricata" and continues decoding the rest of the log. So, your decoder should be written as follows:

```xml
<decoder name="json">
  <program_name>suricata</program_name>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
</decoder>
```
So when evaluating the log in the wazuh-logtest I get the following output:
```bash
# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.1.5
Type one log per line

Jul 29 11:40:53 OPNsense suricata[20064]: {"timestamp": "2021-07-29T11:40:53.381953+0200", "flow_id": 1422765758731265, "in_iface": "re0", "event_type": "alert", "vlan": [99], "src_ip": "192.168.99.187", "src_port": 39462, "dest_ip": "198.49.23.144", "dest_port": 443, "proto": "TCP", "alert": {"action": "allowed", "gid": 1, "signature_id": 90159034, "rev": 1, "signature": "ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)", "category": "A Network Trojan was Detected", "severity": 1, "source": {"ip": "198.49.23.144", "port": 443}, "target": {"ip": "192.168.99.187", "port": 39462}, "metadata": {"first_seen": ["2021_07_09"], "confidence_level": ["100"]}}, "flow": {"pkts_toserver": 1, "pkts_toclient": 0, "bytes_toserver": 78, "bytes_toclient": 0, "start": "2021-07-29T11:40:53.381953+0200"}, "payload_printable": "", "stream": 0}

**Phase 1: Completed pre-decoding.
        timestamp: 'Jul 29 11:40:53'
        hostname: 'OPNsense'
        program_name: 'suricata'

**Phase 2: Completed decoding.
        name: 'json'
        alert.action: 'allowed'
        alert.category: 'A Network Trojan was Detected'
        alert.gid: '1'
        alert.metadata.confidence_level: '['100']'
        alert.metadata.first_seen: '['2021_07_09']'
        alert.rev: '1'
        alert.severity: '1'
        alert.signature: 'ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)'
        alert.signature_id: '90159034'
        alert.source.ip: '198.49.23.144'
        alert.source.port: '443'
        alert.target.ip: '192.168.99.187'
        alert.target.port: '39462'
        dest_ip: '198.49.23.144'
        dest_port: '443'
        event_type: 'alert'
        flow.bytes_toclient: '0'
        flow.bytes_toserver: '78'
        flow.pkts_toclient: '0'
        flow.pkts_toserver: '1'
        flow.start: '2021-07-29T11:40:53.381953+0200'
        flow_id: '1422765758731265.000000'
        in_iface: 're0'
        proto: 'TCP'
        src_ip: '192.168.99.187'
        src_port: '39462'
        stream: '0'
        timestamp: '2021-07-29T11:40:53.381953+0200'
        vlan: '[99]'

**Phase 3: Completed filtering (rules).
        id: '86601'
        level: '3'
        description: 'Suricata: Alert - ThreatFox Cobalt Strike botnet C2 traffic (ip:port - confidence level: 100%)'
        groups: '['ids', 'suricata']'
        firedtimes: '1'
        mail: 'False'
**Alert to be generated.
```

I hope my answer helps you!,

Best Regards,

Mariano Koremblum

**Comment by rschueler** [comment]
Thank you. These decoder settings are working. Alerts are now showing up in security events.

> ```
> <decoder name="json">
>   <program_name>suricata</program_name>
>   <plugin_decoder>JSON_Decoder</plugin_decoder>
> </decoder>
> ```
