### ISSUE TITLE
Review custom upgrade API endpoint

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#9442]
|Wazuh version|Component|
|---|---|
| master | API/Framework |

Hello team,

After some merges in the main development branch (`master` -> `4.3.0`), the custom upgrade API integration test has started to fail consistently. We need to investigate why and fix it. Taking a look at the test report, it seems that the upgrade procedure has failed, as the `status` in the API response says `Error` instead of `Updating`:

```
  -   'status': 'Updating',
  -   'task_id': <tavern.util.loader.IntSentinel object at 0x7ff3e24f9dc0>,
  -   'update_time': <tavern.util.loader.StrSentinel object at 0x7ff3e24f9e20>},
  +   'node': 'master-node',
  +   'status': 'Error',
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

After some debugging I saw there is an error with the WPK package:

1- We make an API request to try to update agent `007`:

```
2021/08/03 12:40:14 INFO: testing 172.20.0.1 "PUT /agents/upgrade_custom" with parameters {"agents_list": "007", "installer": "upgrade.sh", "file_path": "/var/ossec/test_custom_upgrade_3.12.2.wpk", "wait_for_complete": "true"} and body {} done in 0.024s: 200
```

2- We make another API request to see the upgrade status (this is the request that fails in the tests):

```json
{
  "data": {
    "affected_items": [
      {
        "message": "Success",
        "agent": "007",
        "task_id": 1,
        "node": "worker1",
        "module": "upgrade_module",
        "command": "upgrade_custom",
        "status": "Error",
        "error_msg": "Send upgrade command error",
        "create_time": "2021-08-03T12:40:14Z",
        "update_time": "2021-08-03T12:40:22Z"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All upgrade tasks were returned",
  "error": 0
}
```

It can be seen that the status is `Error`.

3- Checking the agent 007 `ossec.log`:

```
2021/08/03 12:40:22 ossec-execd: ERROR: Error verifying WPK certificate.
2021/08/03 12:40:22 ossec-execd: ERROR: At unsign: Couldn't unsign package file '/var/ossec//var/incoming/test_custom_upgrade_3.12.2.wpk'
```

In addition to the WPK certificate error, the logger is not parsing the path correctly. It adds an extra `/` character.

Regards,
Víctor

**Comment by mcarmona99** [comment]
## Issue update

The error reported in this issue is also present in Wazuh version 4.2.0.

The error was found in the [4.2.0-rc12 API integration tests run](https://github.com/wazuh/wazuh/issues/9445).
