### ISSUE TITLE
SSL agents verification not working

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#945]
Hi, we are trying to register an agent using SSL certificates.
We want to verify both the manager, and the agent at the same time.

We managed to verify with success the manager with the rootCA.pem on the agent and sslmanager.cert/key on the manager.
When we tried to verify the agent with sslagent.cert/key on the agent and rootCA.pem on the manager we got an error, "SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/recored/rec_layer_s3.c:1399:SSL alert number 48", we tried looking online for an answer and could't find one that helps us.

The command we are running on the agent is:
"agent-auth -m <manager_ip> -p <port> -P <password> -x /var/ossec/etc/sslagent.cert -k /var/ossec/etc/sslagent.key"
The command we are running on the manager is:
"ossec-authd -a -v /var/ossec/etc/rootCA.pem"

Thanks for the help!

**Comment by vikman90** [comment]
Hi @agentsofshield,

I managed to reproduce this issue with the instructions of our documentation: [Verify agents via SSL](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#verify-agents-via-ssl).

```sh
openssl req -x509 -new -nodes -newkey rsa:2048 -keyout rootCA.key -out rootCA.pem -batch 
openssl req -new -nodes -newkey rsa:2048 -keyout sslagent.key -out sslagent.csr -batch
openssl x509 -req -days 365 -in sslagent.csr -CA rootCA.pem -CAkey rootCA.key -out sslagent.cert -CAcreateserial
```

If I create the certificates this way, I get this error in the agent:

> 140169853314880:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:1399:SSL alert number 48


And this error appears in the manager:
> ossec-authd: ERROR: 18:self signed certificate
> 140040827168512:error:1417C086:SSL routines:tls_process_client_certificate:certificate verify failed:ssl/statem/statem_srvr.c:2896:

I found this clue in the [MySQL documentation](https://dev.mysql.com/doc/mysql-security-excerpt/5.7/en/creating-ssl-files-using-openssl.html)

> Whatever method you use to generate the certificate and key files, the Common Name value used for the server and client certificates/keys must each differ from the Common Name value used for the CA certificate. Otherwise, the certificate and key files will not work for servers compiled using OpenSSL.

We should not define a _common name_ in the agent's certificate if we don't want to validate the host. So, we have to define a different _common name_ for the RootCA, for instance, "Manager":

```sh
openssl req -x509 -new -nodes -newkey rsa:2048 -keyout rootCA.key -out rootCA.pem -batch  -subj "/C=US/ST=CA/O=Manager"
openssl req -new -nodes -newkey rsa:2048 -keyout sslagent.key -out sslagent.csr -batch
openssl x509 -req -days 365 -in sslagent.csr -CA rootCA.pem -CAkey rootCA.key -out sslagent.cert -CAcreateserial
```

Please note that we added ` -subj "/C=US/ST=CA/O=Manager"` when creating the root CA.

These certificates do work and authenticate the agent from the manager. Please let me know if this fixes the issue for you, so we will fix our documentation.

Thank you for reporting this issue.
Best regards.

**Comment by vikman90** [comment]
PR to fix the documentation: https://github.com/wazuh/wazuh-documentation/pull/293.

**Comment by agentsofshield** [comment]
It worked! Thank you very much!
