### ISSUE TITLE
Release 4.2.0 - Release Candidate 12 - Footprint metrics - Syscollector (4h)

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#9484]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/9457 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9447 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC12                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc12                                         |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: 1985

<details><summary>Stress scripts used</summary>

</details>
<details><summary>Stress configuration</summary>

</details>

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
  ![monitor-manager-Test_stress_B1985_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/128208029-d2f5c547-34a5-437f-bfce-ece9e094daff.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/128208034-8987426d-8866-4cb2-908a-d77e5a10a46f.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/128208040-4cef4047-9083-46f7-9381-63b1fa2bafc1.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/128208041-76c1e163-98ef-4df2-8702-b280d981cbfa.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/128208043-e90958cd-97a8-4a5a-8f22-d4d5d195007d.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_PSS](https://user-images.githubusercontent.com/14913942/128208049-f5d8fa11-859d-416d-a333-240bf37cf5f2.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/128208050-247fd3ed-7cc9-40d0-8850-b5d39dbf4680.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/128208053-b8409e38-bca8-443d-8e09-da1d52b6ffa1.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/128208055-f32ccb14-bd41-4d8d-ba13-bfbb913c64bb.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/128208057-1eb72733-1a02-4564-9deb-f06ed8cf36cd.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_USS](https://user-images.githubusercontent.com/14913942/128208059-48e77614-60bf-4cf6-98ad-87b04f588677.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_VMS](https://user-images.githubusercontent.com/14913942/128208060-130ac6a1-eba2-4a57-a8e1-cdc83f1a7f32.png)
![monitor-manager-Test_stress_B1985_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/128208061-a40c68b4-0d3f-49c7-bcb2-1d287f83e82e.png)
![Test_stress_B1985_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/14913942/128208062-b83200e8-f25e-4eee-bd35-b7854cc7829f.png)
![Test_stress_B1985_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/14913942/128208066-0365b402-297b-4593-ac8f-c0eadfda0fbe.png)
![Test_stress_B1985_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/14913942/128208070-481dc542-f0c6-4faf-8bd7-55415ae5472e.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B1985_manager_2021-08-04.zip](https://github.com/wazuh/wazuh/files/6932350/ossec_Test_stress_B1985_manager_2021-08-04.zip)
  [alerts_Test_stress_B1985_manager_2021-08-04.zip](https://github.com/wazuh/wazuh/files/6932352/alerts_Test_stress_B1985_manager_2021-08-04.zip)

   </details>
+ <details><summary>CSV</summary>

  [monitor-manager-Test_stress_B1985_manager-pre-release.csv](https://github.com/wazuh/wazuh/files/6932353/monitor-manager-Test_stress_B1985_manager-pre-release.csv)
[Test_stress_B1985_manager_analysisd_state.csv](https://github.com/wazuh/wazuh/files/6932354/Test_stress_B1985_manager_analysisd_state.csv)
[Test_stress_B1985_manager_remoted_state.csv](https://github.com/wazuh/wazuh/files/6932355/Test_stress_B1985_manager_remoted_state.csv)

   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
    
  ![monitor-winagent-Test_stress_B1985_windows-pre-release_CPU](https://user-images.githubusercontent.com/14913942/128208186-94329aae-a24c-4db7-bad5-13c52883bcbd.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/128208191-1e0d23ee-0206-4995-99fd-bfcbf92fb1fe.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/128208193-1c4aa094-b9b7-44b0-98bb-3ec4b4a3995c.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Disk](https://user-images.githubusercontent.com/14913942/128208195-7b1f5669-c4a7-43ac-bf9c-2fc951543b3f.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Handles](https://user-images.githubusercontent.com/14913942/128208200-e22d47a8-5896-4d47-a4d1-8be077de4802.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/128208202-da557582-ce22-45ab-9a1f-e10a6af2230b.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/128208203-70ff5da2-4aac-42cd-b431-ebc8b48dfda2.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_RSS](https://user-images.githubusercontent.com/14913942/128208206-37486fcd-a9fa-47a4-a703-22fee73d5cb4.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_USS](https://user-images.githubusercontent.com/14913942/128208208-b045ab60-c7dc-45f9-b9ad-1e59d1932c1f.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_VMS](https://user-images.githubusercontent.com/14913942/128208209-0b55f496-7583-481e-92c7-93f833f62c4d.png)
![monitor-winagent-Test_stress_B1985_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/128208213-d1edcf6d-70b2-4e2f-a501-d9e122c49b17.png)
![Test_stress_B1985_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/128208216-ac434f3b-8eef-405e-820f-8d636edb78ca.png)
![Test_stress_B1985_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/128208220-308f3cbf-c6cc-42f1-8c45-d867c2977ad0.png)
![Test_stress_B1985_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/128208226-cbf429f4-cd51-4c7a-bb64-5be1ebb27b64.png)
![Test_stress_B1985_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/128208229-d6c33a5d-57a4-40f9-a888-e98737caaedf.png)

    
   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B1985_windows_2021-08-04.zip](https://github.com/wazuh/wazuh/files/6932356/ossec_Test_stress_B1985_windows_2021-08-04.zip)

   </details>
+ <details><summary>CSV</summary>

  [monitor-winagent-Test_stress_B1985_windows-pre-release.csv](https://github.com/wazuh/wazuh/files/6932357/monitor-winagent-Test_stress_B1985_windows-pre-release.csv)
[Test_stress_B1985_windows_agentd_state.csv](https://github.com/wazuh/wazuh/files/6932358/Test_stress_B1985_windows_agentd_state.csv)

   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B1985_centos-pre-release_CPU](https://user-images.githubusercontent.com/14913942/128208294-a1ae8434-e248-48cb-b216-15bf36fcbed5.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/128208298-f7f79c46-d519-4928-958b-393cc297512f.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/128208300-7a01acbe-5e64-4523-86f3-850e514be023.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_Disk](https://user-images.githubusercontent.com/14913942/128208303-89c197d9-0a73-484f-ba9d-85a1616f3939.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_FD](https://user-images.githubusercontent.com/14913942/128208306-688cc0ae-8f04-4e3e-a74a-608bcb729bd2.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_PSS](https://user-images.githubusercontent.com/14913942/128208309-e466021a-8d47-4d44-9e36-fc4521eaa7b7.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/128208312-7d9ea0bf-8d5a-46d3-83a7-7c0d54d29fdd.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/128208314-71d38a9a-8b7e-4936-bdcc-8b93973a2d71.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_RSS](https://user-images.githubusercontent.com/14913942/128208316-ceeb1436-32da-436d-b1e1-3d0e69210b7b.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/128208318-a62bada3-6d55-45b7-b32b-44d16f213d49.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_USS](https://user-images.githubusercontent.com/14913942/128208320-059fc23a-0812-49f2-8cda-8609d50523eb.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_VMS](https://user-images.githubusercontent.com/14913942/128208323-3b1b2a83-bdc4-4ee6-a70b-40915eedc591.png)
![monitor-agent-Test_stress_B1985_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/128208328-de499930-3a9d-45d8-8b50-5992e5bea333.png)
![Test_stress_B1985_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/128208330-151cd162-3c25-4e31-88bc-5bfe92655c21.png)
![Test_stress_B1985_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/128208332-ca4720ae-b075-437a-aa75-297b3c190841.png)
![Test_stress_B1985_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/128208334-c20a0a6b-0968-4d65-bb74-84b36837fd01.png)
![Test_stress_B1985_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/128208336-0e703035-a3d1-4665-8fb6-2632aa04773a.png)

   </details>
+ <details><summary>Logs and configuration</summary>

    
  [ossec_Test_stress_B1985_centos_2021-08-04.zip](https://github.com/wazuh/wazuh/files/6932362/ossec_Test_stress_B1985_centos_2021-08-04.zip)

   </details>
+ <details><summary>CSV</summary>

  [monitor-agent-Test_stress_B1985_centos-pre-release.csv](https://github.com/wazuh/wazuh/files/6932363/monitor-agent-Test_stress_B1985_centos-pre-release.csv)
[Test_stress_B1985_centos_agentd_state.csv](https://github.com/wazuh/wazuh/files/6932364/Test_stress_B1985_centos_agentd_state.csv)

   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B1985_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/14913942/128208405-ce332691-6fcb-4a19-985f-3e31891ba3a6.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/128208412-92fd14c3-204e-4c42-a98d-c87a40149426.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/128208414-e055d1b8-6cea-4151-8bf3-83a791ee9058.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/14913942/128208416-82bc5dfc-a475-44fe-8088-dd6c0e5ecd0b.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/14913942/128208419-7abbdf5c-cfce-4c29-b662-ea03ea04e8e6.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/14913942/128208423-3ad12965-4595-40ed-af1a-760779880a19.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/128208426-fefa9367-033a-4a7f-8f52-a71a02c42104.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/128208428-838d72de-f352-4422-8127-f9d0ef4f0824.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/14913942/128208432-7e33a2c0-fe7d-4846-984e-2f194a9f9b05.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/128208436-1338823a-1669-4db0-a6f6-43c44984d877.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/14913942/128208439-ff4d98ee-88a3-4e1c-ae4c-3c82d81597af.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/14913942/128208440-917969cb-7dbe-449f-8b30-e5fd9fea69a6.png)
![monitor-agent-Test_stress_B1985_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/128208443-746cf577-2a51-42fe-bac4-1b8a086bd1c5.png)
![Test_stress_B1985_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/128208447-73a10cea-ca4a-43a7-a6cd-3fe5ea8c81d2.png)
![Test_stress_B1985_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/128208449-d3ddab5a-1d5e-4493-9be1-8e60ced78788.png)
![Test_stress_B1985_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/128208452-8903a9d4-2d68-45f3-90f1-cbfefd298efd.png)
![Test_stress_B1985_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/128208453-fd6fbe32-536f-4f90-8e88-3f6845c52452.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B1985_ubuntu_2021-08-04.zip](https://github.com/wazuh/wazuh/files/6932366/ossec_Test_stress_B1985_ubuntu_2021-08-04.zip)

   </details>
+ <details><summary>CSV</summary>
    
  [monitor-agent-Test_stress_B1985_ubuntu-pre-release.csv](https://github.com/wazuh/wazuh/files/6932367/monitor-agent-Test_stress_B1985_ubuntu-pre-release.csv)
[Test_stress_B1985_ubuntu_agentd_state.csv](https://github.com/wazuh/wazuh/files/6932368/Test_stress_B1985_ubuntu_agentd_state.csv)

   </details>
</details>

**Comment by Dwordcito** [comment]
Windows 4.1.5 VS 4.2.0 RC12

Windows RC10 VS RC12

![image](https://user-images.githubusercontent.com/14300208/128563990-04b98738-6b7f-43fd-abe3-ae36896a6055.png)

**Comment by Dwordcito** [comment]
CentOS 4.1.5 VS 4.2.0 RC12

CentOS RC10 VS RC12

**Comment by Dwordcito** [comment]
Ubuntu 4.1.5 VS 4.2.0 RC12

Ubuntu RC10 VS RC12

**Comment by Dwordcito** [comment]
Analysisd 4.1.5 VS 4.2.0 RC12

Analysisd RC10 VS RC12

**Comment by Dwordcito** [comment]
remoted 4.1.5 VS 4.2.0 RC12

remoted RC10 VS RC12

**Comment by Dwordcito** [comment]
wazuh-db 4.1.5 VS 4.2.0 RC12

wazuh-db RC10 VS RC12
