### ISSUE TITLE
New decoders and rules for CISCO-IOS

### ISSUE THREAD

**Issue by dami-nicastro** [wazuh/wazuh#9499]
Hello team!

### **Request: CISCO-IOS**

I am looking for a new set of decoders and rules for CISCO

**Vendor: CISCO
Operating System: CISCO IOS
Models: All CISCO Wireless devices using IOS**

Please, follow this article from the vendor to create the decoders and rules:
https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html
For details about CISCO-IOS events severity:
https://www.cisco.com/c/en/us/td/docs/routers/access/wireless/software/guide/SysMsgLogging.html#wp1054858

### Log Sample:
```
Jul 29 20:08:37 UTC: %FTD-session-6-305012: Teardown dynamic TCP translation from INTF-INSIDE-1:DDD.DDD.DDD.DDD/XXXXX to INTF-INET-SWKO:DDD.DDD.DDD.DDD/XXXXX duration 0:00:00
```

Thanks for your help.

**Comment by dami-nicastro** [comment]
Here a set of rules to use with the previous decoder:
[new_rules_Cisco-ios.txt](https://github.com/wazuh/wazuh/files/6933456/new_rules_Cisco-ios.txt)

Thanks
Damian

**Comment by JavierBejMen** [comment]
## Branch
https://github.com/wazuh/wazuh/tree/9499_new_ios_ruleset

**Comment by JavierBejMen** [comment]
## Update
Decoders works with the provided log example, we need to test the whole .ini set to verify there are no conflicts.

The following decoder has been removed:
```xml
<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>(%\w+-\d-\w+):</regex>
  <order>id</order>
</decoder>
```
as it is redundant with one already present:
```xml
<!-- Cisco IOS
  - Extracts the ID of cisco ios messages IF NOT IDS/ACL log.
  -->

<decoder name="cisco-ios-default">
  <parent>cisco-ios</parent>
  <regex>%(\w+)-(\d)-(\w+):</regex>
  <order>cisco.facility, cisco.severity, cisco.mnemonic</order>
</decoder>
```

Test example:
```
Type one log per line

Jul 29 20:08:37 UTC: %FTD-session-6-305012: Teardown dynamic TCP translation from INTF-INSIDE-1:10.40.1.239/60914 to INTF-INET-SWKO:209.137.221.2/60914 duration 0:00:00

**Phase 1: Completed pre-decoding.
	full event: 'Jul 29 20:08:37 UTC: %FTD-session-6-305012: Teardown dynamic TCP translation from INTF-INSIDE-1:10.40.1.239/60914 to INTF-INET-SWKO:209.137.221.2/60914 duration 0:00:00'
	timestamp: 'Jul 29 20:08:37'
	hostname: 'UTC:'
	program_name: 'UTC'

**Phase 2: Completed decoding.
	name: 'cisco-ios'
	cisco.facility: 'FTD-session'
	cisco.mnemonic: '305012'
	cisco.severity: '6'
	duration: '0:00:00'
	message: 'Teardown dynamic TCP translation from INTF-INSIDE-1:10.40.1.239/60914 to INTF-INET-SWKO:209.137.221.2/60914'

**Phase 3: Completed filtering (rules).
	id: '4700'
	level: '0'
	description: 'Grouping of Cisco IOS rules.'
	groups: '['syslog', 'cisco_ios']'
	firedtimes: '1'
	mail: 'False'
```

**Comment by JavierBejMen** [comment]
## Update
Rules proposed use cases already covered by official Cisco IOS rules.
