### ISSUE TITLE
Syslog and agents

### ISSUE THREAD

**Issue by whois51** [wazuh/wazuh#95]
Is it possible to config syslog and allowed agents ip list at the same time? If is how would config file look like?

**Comment by vikman90** [comment]
Hi @whois51,

do you refer to listen to syslog clients and agents at the same time? If you do, you may use a configuration like this:

```
<!-- Listen Syslog clients -->
<remote>
  <connection>syslog</connection>
  <port>514</port>
  <protocol>udp</protocol>
</remote>

<!-- Listen Wazuh agents -->
<connection>secure</connection>
  <port>1514</port>
  <protocol>udp</protocol>
</remote>
```

If this does not answer your question please give us more details.

Anyway, if you have further questions, I suggest you use the [Wazuh mailing list](https://groups.google.com/forum/#!forum/wazuh), we will be pleased to assist you.
