### ISSUE TITLE
Routes Error wzMisc is undefined / Routes Warning Wazuh App Please add a new API

### ISSUE THREAD

**Issue by felimwhiteley** [wazuh/wazuh#950]
Hi folks, I've upgraded from version 2 of wazuh I'll provide a list of as many bits I've seen you ask. I've added in my API details with auth that works when used with curl. It passes the test connection button. But it constantly gives the error message about wzMisc. 

![screenshot_20180716_184221](https://user-images.githubusercontent.com/1309595/42775359-1022cef0-892c-11e8-951d-95c502aed32b.png)

There is a 500 error generated on each page when trying to GET http://172.16.12.54:5601/api/wazuh-elastic/timestamp when done via curl it gives
```
{"message":"4001 - Could not fetch .wazuh-version index","code":4001,"statusCode":500}
```
Doing a curl gives: curl -X GET localhost:9200/.wazuh-version?pretty=true
```
{
  ".wazuh-version" : {
    "aliases" : { },
    "mappings" : { },
    "settings" : {
      "index" : {
        "creation_date" : "1531536555808",
        "number_of_shards" : "1",
        "number_of_replicas" : "1",
        "uuid" : "aDxystqVQI6LJZuEx26esg",
        "version" : {
          "created" : "6030199"
        },
        "provided_name" : ".wazuh-version"
      }
    }
  }
}
```

GET "http://127.0.0.1:55000/agents/000?pretty"
```
{
   "error": 0,
   "data": {
      "status": "Active",
      "name": "srv-wazuh",
      "ip": "127.0.0.1",
      "dateAdd": "2018-07-13 17:18:39",
      "version": "Wazuh v3.3.1",
      "manager_host": "srv-wazuh",
      "lastKeepAlive": "9999-12-31 23:59:59",
      "os": {
         "major": "16",
         "name": "Ubuntu",
         "platform": "ubuntu",
         "uname": "Linux |srv-wazuh |4.15.0-24-generic |#26~16.04.1-Ubuntu SMP Fri Jun 15 14:35:08 UTC 2018 |x86_64",
         "version": "16.04.4 LTS",
         "codename": "Xenial Xerus",
         "arch": "x86_64",
         "minor": "04"
      },
      "id": "000"
   }
}
```

GET "http://127.0.0.1:55000/cluster/status?pretty" 
```
{
   "error": 0,
   "data": {
      "running": "yes",
      "enabled": "yes"
   }
}
```

GET "http://127.0.0.1:55000/cluster/node?pretty" 
```
{
   "error": 0,
   "data": {
      "node": "srv-wazuh",
      "cluster": "wazuh",
      "type": "master"
   }
}
```

GET "http://127.0.0.1:55000/syscheck/000?pretty" 
```
{
   "error": 0,
   "data": {
      "totalItems": 0,
      "items": []
   }
}
```

cat /etc/ossec-init.conf
```
DIRECTORY="/var/ossec/"
NAME="Wazuh"
VERSION="v3.3.1"
REVISION="3322"
DATE="Fri 13 Jul 17:17:17 BST 2018"
TYPE="server"
```

grep -i -E "version|revision" /usr/share/kibana/plugins/wazuh/package.json
```
    "version": "3.3.1",
    "revision": "0398",
        "version": "6.3.1"
```

grep -i -E "version|revision" /usr/share/kibana/package.json
``` 
 "version": "6.3.1",
```

I've added and removed the API settings in Wazuh kibana interface, starred them as default but it seems to forget it as the drop down complains of "No Api - wazuh-alerts-*" in the top right drop down. I followed the upgrade guide, the only issue was with it not likeing the cluster section of the dpkg config file. I was able to edit the postinst script comment out the overwriting of my own v3 config which has been updated to the new variables etc. (very little but adding the SMTP settings and enabling the cluster section). It would continually fail to complete the apt install without ifnoring the ossec.conf file overwrite.

Hopfully this is enough info, thanks for your help.

**Comment by felimwhiteley** [comment]
That fixed it thanks, I had followed all of the major upgrade guide, including the migration os Kibana index to v6.0

Thanks for your help, maybe one of the indexes was old?

**Comment by jesusgn90** [comment]
You are welcome @felimwhiteley !

Don't know what exactly happened because I haven't got enough information. Maybe an index was corrupted or with the latest versions of Elasticsearch our App must be reviewed internally, in any case next packages will be reviewed when upgrading from different major. Thanks for your feedback. 

Regards,
Jesús
