### ISSUE TITLE
wazuh logs appearing only after restart

### ISSUE THREAD

**Issue by HireLabs** [wazuh/wazuh#954]
I have updated wazuh-api, wazuh-manager, and wazuh-agents on all machines from 3.2.1 to 3.3.1, now I can't get complete logs.
Alerts are appearing once when I restart manager/clients separately. and I would like to get complete archive logs too in wazuh/kibana, anyone help ?

**Comment by jesusgn90** [comment]
Hello @HireLabs and @sulaiman35 ,

> By default, alerts will be generated on events that are important or of security relevance. To store all events even if they do not match a rule, enable the <log_all> option.
> 
> Alerts will be stored at /var/ossec/logs/alerts/alerts.(json|log) and events at /var/ossec/logs/archives/archives.(json|log). Logs are rotated and an individual directory is created for each month and year.

- https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html#alert

We have configured to take care about alerts generated by rules with a rule level greater or equal to 3. 

```
cat /var/ossec/etc/ossec.conf | grep log_alert_level

// <log_alert_level>3</log_alert_level>
```

The `archives.json` is where you can store all events from your Wazuh manager. To enable it, edit /var/ossec/etc/ossec.conf from your Wazuh manager and replace `<logall_json>no</logall_json>` by `<logall_json>yes</logall_json>`, then restart the manager (`systemctl restart wazuh-manager`).

The standard data flow using Elasticsearch is as follow:

1. Wazuh agents send data to Wazuh manager
2. Wazuh manager analyzes the data and generate some alerts in /var/ossec/logs/alerts/alerts.json
3. Logstash or Filebeat read the file /var/ossec/logs/alerts/alerts.json and it sends the alerts to Elasticsearch
4. Kibana reads data from Elasticsearch and give you a human readable format using visualizations

@HireLabs from your question _Alerts are appearing once when I restart manager/clients separately. and I would like to get complete archive logs too in wazuh/kibana, anyone help ?_ I don't understand what are you meaning at all. 

The manager generates some alerts just after starting but other kind of alerts need more time such a rootcheck scan or a sycheck scan (they take more time to complete a scan). In any case you are able to select different time range in Kibana (look at the search bar and in the top right corner you'll see "Last 15 minutes", expand the time range to see older alerts)

Let us know in a more detailed way what are you looking for.

Best regards,
Jesús

**Comment by jesusgn90** [comment]
Ok @sulaiman35 but note that you should take care about ingesting the archives.json file to Elasticsearch, it could generate tons of entries and flood your Elasticsearch nodes fast.

Regards,
Jesús

**Comment by sulaiman35** [comment]
@jesusgn90 Thanks alot for your support.

**Comment by jesusgn90** [comment]
You are welcome!

**Comment by jagannathan123** [comment]
Hello Folks,
  
    -> I installed with the wazuh-manager 3.6.2, wazuh-agent 3.6.1 , kibana -6.4.3 ,elasticsearch -6.4.3, logstash -6.4.3 . I am unable to getting the ossec-restart alert, But i get the alert for added manager and agent alerts.  

    -> Please give me suggestion for fixing this alert issue asap.


Thanks & Regards,
S.jagannathan.
![agent_added](https://user-images.githubusercontent.com/20808448/51728741-4453bd80-2097-11e9-83c6-aa92a71c5570.png)
![agent_manager_alerts](https://user-images.githubusercontent.com/20808448/51728742-4453bd80-2097-11e9-8454-0ab7f9fbbd8c.png)
