### ISSUE TITLE
Amazon Linux 2 sca wrong cisbenchmark mappings and cheks

### ISSUE THREAD

**Issue by JavierBejMen** [wazuh/wazuh#9541]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Master | SCA | Manager | Packages/Sources | Amazon Linux 2|

## Description

Some steps contain mismatched Cisbenchmarks tags and are not implemented as stated by the benchmark. This issue aims to map and implement correctly the sca for Amazon Linux 2 following this [Cisbenchmark](https://www.cisecurity.org/benchmark/amazon_linux/).

## Related
- [Slack community thread](https://wazuh.slack.com/archives/C0A933R8E/p1628148072364800)

## Tasks
- [x] Identify all incongruencies

Mismatched steps:
- [x] 1.1.6

Wrong steps implementation:
- [x] 1.1.6

**Comment by jcruzlp** [comment]
## Progress Update
Seems like some test are not wrongly implemented but its number doesn't match with the one that appears on the CIS benchmark.

To proceed with it ill identify all of these cases and replace the tags.

## Problematic tags
- 1.1.1.2 & 1.1.1.3-> Doesnt match with CIS benchmark.
- 1.1.1.4 -> Should be 1.1.1.2
- 1.1.1.5 -> Should be 1.1.1.3
- 1.1.4 -> Should be 1.1.5
- 1.1.6 -> Should be 1.1.10
- 1.1.7 -> Should be 1.1.11
- 1.1.8 -> Should be 1.1.13
- 1.1.9 -> Should be 1.1.14
- 1.1.10 -> Should be 1.1.12
- 1.1.11 -> Should be 1.1.15
- 1.1.12 -> Should be 1.1.16
- 1.1.13 -> Should be 1.1.17
- 1.1.14 -> Should be 1.1.18
- 1.1.15 -> Should be 1.1.8
- 1.1.16 -> Should be 1.1.9
- 1.1.17 -> Should be 1.1.7
- 1.1.18 is missing.
- 1.1.19 -> Should be 1.1.23

**Comment by jcruzlp** [comment]
Branch to track progress: https://github.com/wazuh/wazuh/tree/9541-update-amazon-2-SCA
