### ISSUE TITLE
about wazuh-manager to volumes the ossec.conf

### ISSUE THREAD

**Issue by yehaotong** [wazuh/wazuh#9560]
when I use the wazuh-manager and try to volumes the ossec.conf,it always failed(filed in init the etc/cont-init.d/2-manager),what is the problem ? I volumes the path is:/var/ossec/etc/ossec.conf,is that make me failed? ossec.conf do not need to put in /var/ossec/etc?

**Comment by yehaotong** [comment]
Is the ossec.conf can not be volumed?

**Comment by MiguelazoDS** [comment]
Hello @yehaotong, 

Sorry for the late response. I would like more details to help you with this. Are you trying a docker deployment and want to keep the configuration file in a separate volume and not inside the container? 

I assume you followed these steps detailed here. 

https://documentation.wazuh.com/current/docker/container-usage.html#wazuh-service-data-volumes

Could you confirm that? 

What is the specific error you are getting when trying to achieve this?

Regards!
