### ISSUE TITLE
Add a cache mechanism for the manager to save the calculated key hash and use it in future requests

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9568]
As part of the epic https://github.com/wazuh/wazuh/issues/9549, we are implementing a mechanism to send the hash of the agent key to the manager. This message is received by Authd and it validated whether is the same as the one calculated with the data that the manager has.

In case of connection issues of the agents with the manager, an agent could attempt multiple times to validate the hash. So, in order to avoid multiples hash calculations in the manager, it should have a cache with the hash of the agent key. This cache should be filled only when a first validation attempt is done.

It should be included with this implementation, an analysis on how expensive is in terms of memory having this cache, and the CPU improvement caused because of avoiding calculating hashes.

**Comment by pereyra-m** [comment]
### Introduction

To achieve this analysis, we could follow the following approach:
- The algorithm to hash the keys has been already developed. We can measure the time took by **authd** to calculate it.
- We can calculate the amount of memory used by **authd** to save this new variable for each agent

Then, we'll compare both situations to determine if a cache mechanism is necessary.

### Time consumption

The hash algorithm is very fast, it was necessary to use the microseconds unit with the function `gettimeofday()`.
The manager's hardware consists of an Ubuntu 20.04 VM, with 4GB Ram and 2 CPU (3.0GHz). Here we have the example code

<details>
  <summary>w_get_key_hash</summary>
  
  ```int w_get_key_hash(keyentry *key_entry, os_sha1 output) {
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    if (!key_entry || !output) {
        mdebug2("Unable to hash agent's key due to empty parameters.");
        return OS_INVALID;
    }

    char *key = key_entry->key;
    if (key) {
        OS_SHA1_Str(key, strlen(key), output);
        gettimeofday(&stop, NULL);
        mwarn("Timestamp difference: %lu", (stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec);
        return 0;
    }
    else {
        mdebug2("Unable to hash agent's key due to empty value.");
        return OS_INVALID;
    }
}
  ```
</details>

<details>
  <summary>w_auth_replace_agent</summary>
  
  ```
w_err_t w_auth_replace_agent(keyentry *key,
                             const char *key_hash,
                             authd_force_options_t *force_options){
    struct timeval stop, start;
    gettimeofday(&start, NULL);
    /* Check if the agent replacement is allowed */
    if (!force_options->enabled) {
        minfo("Agent '%s' won´t be removed because the force option is disabled.", key->id);
        return OS_INVALID;
    }

    /* Check if the agent antiquity complies with the configuration to be removed */
    double antiquity = 0;
    if (antiquity = OS_AgentAntiquity(key->name, key->ip->ip), antiquity > 0 && antiquity < force_options->connection_time) {
        minfo("Agent '%s' doesn´t comply with the antiquity to be removed.", key->id);
        return OS_INVALID;
    }

    /* Check if the agent key is the same than the existent in the manager */
    if (key_hash) {
        os_sha1 manager_key_hash;
        w_get_key_hash(key, manager_key_hash);
        if (!strcmp(manager_key_hash, key_hash)) {
            minfo("Agent '%s' key already exists on the manager.", key->id);
            gettimeofday(&stop, NULL);
            mwarn("Replace agent difference: %lu", (stop.tv_sec - start.tv_sec) * 1000000 + stop.tv_usec - start.tv_usec);
            return OS_INVALID;
        }
    }

    /* Replace the agent */
    minfo("Removing old agent '%s'.", key->id);
    add_remove(key);
    OS_DeleteKey(&keys, key->id, 0);
    return OS_SUCCESS;
}
  ```
</details>

I compared the time took for `w_auth_replace_agent()` and `w_get_key_hash()` 25 times. Every time **authd** receives an key request, it extracts the data sent by the agent and validates this information before removing it: the extra time was **%3,46** on average (14 us). 

We also need to consider that this situation is not really frequent: 
- When the agent is being enrolled for the first time, it hasn't got any key, so the hash isn't calculated
- The agent would only ask for a new key if the communication with **remoted** fails a few consecutive times
- After that attempt, the agent will wait until a new retry

Finally, the keys are kept in memory, so a hash calculation doesn't involve a disk read/write operation.

### Cache mechanism

To avoid the extra CPU calculation, we could save the key hash in memory. 
We should consider that:
- If we calculate it for every agent at the beginning, some of them may never use it. This approach may generate more CPU usage than the original implementation. 
- We could store in cache the hash only when an agent requests a new key, so it would start to save calculations in the second try. 

The `SHA1` algorithm stores the result in a 41 positions char array. So, a new variable in the key store would increase **%25** (from 160 to 200 bytes) the size of the `keyentry` structure for every agent that requests a key already having one.

### Analysis

The team will analyze the results to take a decision.

**Comment by DProvinciani** [comment]
Based on the analysis above, we decided to avoid the implementation of the cache because of the very low impact of the key validation mechanism. So, we close the issue.
