### ISSUE TITLE
agent_control: ERROR: randombytes failed for all possible methods for accessing random data

### ISSUE THREAD

**Issue by felimwhiteley** [wazuh/wazuh#96]
Hi There,

Trying to run 

`sudo /srv/ossec/bin/agent_control -i "001"`

But getting the following error:

2017/04/07 00:37:35 agent_control: ERROR: randombytes failed for all possible methods for accessing random data

The version is "Wazuh v2.0 - Wazuh Inc." downloaded from github main today.
sha256 of the source is:
`c5647ecebf5aa831c8a44e075078c2af4fb9ad1355b8c54eaa2cecf1b4d572f2  util/agent_control.c`

I ran an strace and it appears  it is chrooting into /srv/ossec then trying to access /dev/random & /dev/urandom which do not exists in the ossec directory. I've attached an strace. Thanks for your help.

[strace.txt](https://github.com/wazuh/wazuh/files/904182/strace.txt)

Just as test I tried via the REST API which actually worked...

**Comment by vikman90** [comment]
Hi @felimwhiteley,

thank you for notifying us. We have just solved it: https://github.com/wazuh/wazuh/commit/382f3a7a1aa3c8682bfc04411703f546b0480cbb

Thank you very much again for your feedback.

**Comment by felimwhiteley** [comment]
Brilliant, works like a charm! :-)
