### ISSUE TITLE
Release 4.2.0 - Release Candidate 13 - Footprint metrics - Logcollector-Syscollector 

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#9610]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: https://ci.wazuh.info/job/Test_stress/2194

<details><summary>Stress scripts used</summary>

</details>
<details><summary>Stress configuration</summary>

</details>

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
  ![monitor-manager-Test_stress_B2194_manager-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129713648-bd760aca-401d-490c-86be-8471a6a6c118.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129713653-779f8d1f-a381-4955-a67d-3966d4458249.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129713656-e10aa5b0-dd4f-4786-9917-49450bca3441.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129713657-5d04804e-331f-467e-88dc-da52c733c410.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_FD](https://user-images.githubusercontent.com/19505384/129713659-95a5141c-9843-4545-8cc9-1bcfc06036b1.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129713661-8df7b36c-d67f-4540-832c-d64902added9.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129713663-18a1e408-89f0-4ca9-a2df-34d29c6f2f5b.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129713664-9217671e-b5d5-4ad5-bc41-3e336a51a516.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129713665-91719bf9-4798-4ed8-95fe-a717178a1a1b.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129713666-15095cd6-6e7f-4a13-b56e-1402f6ab774f.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_USS](https://user-images.githubusercontent.com/19505384/129713667-186ccb28-dbf0-4bb4-889b-ca47cbf6acc2.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129713670-21939ca8-f574-4a81-adcd-b0b02d22a4b9.png)
![monitor-manager-Test_stress_B2194_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129713672-114ffcb6-f65d-40ed-80cb-05c60fc6c407.png)
![Test_stress_B2194_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/19505384/129713673-8d94ebc6-f9e4-4a25-bbf8-01778369d4d9.png)
![Test_stress_B2194_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/19505384/129713675-34aa4da0-2399-4928-905b-e239db863524.png)
![Test_stress_B2194_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/19505384/129713678-d2696c89-fd5f-4f78-82ef-b042ccf2e3cf.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  
  [ossec_Test_stress_B2194_manager_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999341/ossec_Test_stress_B2194_manager_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

 
  [B2194_manager_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999343/B2194_manager_centos_csv.zip)

   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
  ![monitor-winagent-Test_stress_B2194_windows-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129713731-34516f73-1a06-4b4e-b079-c8bcdc2577cd.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129713733-8f99472d-9712-4ff1-9325-473b4b014f5d.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129713735-46a6b858-3571-492c-89e6-c41abc3cafef.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129713739-b12acccd-6da9-4817-8197-5f60abeaf29f.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Handles](https://user-images.githubusercontent.com/19505384/129713740-37670a92-d1a8-4fe2-b036-8c78ca86d814.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129713741-f73223ff-51e1-4046-a13d-9390790727c1.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129713743-2e309950-cf82-48c7-9ebc-9fd04a4445ba.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129713746-add5fc29-a7d0-41f4-aed9-c7361eff14be.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_USS](https://user-images.githubusercontent.com/19505384/129713750-8d631a39-dfc1-41e3-9852-dbfac3557a25.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129713752-fc5fe317-5de2-455c-9e99-e625bb7bece0.png)
![monitor-winagent-Test_stress_B2194_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129713754-60fc2f57-bc7a-41a8-a0da-2ab7d2efd855.png)
![Test_stress_B2194_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129713755-cbeefda4-8695-4dd2-b0c2-c08fdfc7865a.png)
![Test_stress_B2194_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129713758-1b886a59-4025-415c-9af1-9f06271fa48f.png)
![Test_stress_B2194_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129713760-c316a55d-6e33-4be5-bbc5-e8104ebca3b0.png)
![Test_stress_B2194_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129713761-72aca61a-8125-4eeb-a389-23f57674e36d.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2194_windows_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999347/ossec_Test_stress_B2194_windows_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2194_agent_windows_csv.zip](https://github.com/wazuh/wazuh/files/6999349/B2194_agent_windows_csv.zip)

   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2194_centos-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129713805-05fcaca5-81ff-447d-833d-76a88e95499a.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129713807-0a1abd5c-b329-4d04-b1e3-619200031c21.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129713808-fb48e880-2c5a-42c5-87f8-c9a992442c01.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129713809-81adb6b3-2dbc-4e2e-a865-c1fc6b3b7519.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_FD](https://user-images.githubusercontent.com/19505384/129713811-b88627cb-ab60-4ac0-bccc-cd1330a44c54.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129713813-5abb2d4d-01f9-49d4-8b23-a99204c77763.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129713817-887c746f-68d5-4143-8f05-65ccce1aef51.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129713819-91e0b9a6-f848-458e-b268-51b81ad25ac1.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129713820-d1f8625f-8caa-4c94-af75-84f7bf762290.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129713821-ea724e6d-86de-4ec0-b470-eb10e949c3a3.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_USS](https://user-images.githubusercontent.com/19505384/129713822-eedc3a64-47f6-422d-a76f-219ec5184d67.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129713823-5afe8121-2500-40e0-a1ee-d783e6775162.png)
![monitor-agent-Test_stress_B2194_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129713824-960044a7-405e-47af-a39a-2f281d434779.png)
![Test_stress_B2194_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129713826-c5cda0ee-16bc-4ee4-9ea3-c5120dbee6fc.png)
![Test_stress_B2194_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129713829-1e4f25ea-4cd0-45d0-9e62-e846e5e748d7.png)
![Test_stress_B2194_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129713830-6d3bfe26-10b0-4907-8485-a6c69c1497e9.png)
![Test_stress_B2194_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129713831-067176ba-feed-4d70-b8c3-db920a952e52.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2194_centos_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999350/ossec_Test_stress_B2194_centos_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2194_agent_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999351/B2194_agent_centos_csv.zip)

   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2194_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129713888-05e14ebb-fe9c-451d-8ffd-52bf35ae42aa.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129713891-fdaedc1c-7ebd-43ef-848d-9e6c5916abf0.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129713894-fbbfef74-880c-4d46-983a-74bba4f29a96.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129713895-b3b0264f-5b56-4b36-8bb6-7806b9d3d845.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/19505384/129713901-07f9e7c4-f2b2-4eee-af7b-850b3293d799.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129713902-547896e5-a2c4-41d9-bf2d-21b976cbe7c4.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129713904-0ef0a5a2-1ef7-4ba1-9f45-62ec501bd78a.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129713905-60f384f0-8d8a-4218-a117-e03f5e33d83f.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129713907-99dd89b4-03f2-4307-b73a-064ff6670595.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129713908-b9995196-d5ef-4661-b452-7b80c9ee794f.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/19505384/129713910-73fc40de-9eea-4878-8718-6b57bea0349a.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129713911-45865dea-5a81-4a27-989f-efcec9b2a36e.png)
![monitor-agent-Test_stress_B2194_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129713913-1e2c57a2-d6dd-46b0-9f86-bf0864ba03f5.png)
![Test_stress_B2194_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129713915-d867f43a-72ff-419d-8cab-366e1d70484b.png)
![Test_stress_B2194_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129713919-c1f3c042-3eab-4dbb-8e1a-dbd382956164.png)
![Test_stress_B2194_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129713921-a3a4b08d-5280-4729-b247-e8f2ce0f6ea2.png)
![Test_stress_B2194_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129713922-5493dbb4-c613-42c5-842c-1c05cc51eaaa.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2194_ubuntu_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999354/ossec_Test_stress_B2194_ubuntu_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>
    
  [B2194_agent_ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/6999355/B2194_agent_ubuntu_csv.zip)

   </details>
</details>

**Comment by rauldpm** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

## Stress test documentation

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: 2234

**Results with all manager daemons activated**

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
    ![monitor-manager-Test_stress_B2234_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121250-f8f7020f-0115-4e1d-b8c6-0b320afd71b3.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121258-be742336-28b4-41bb-b3c8-f4d1fa929ebe.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121263-4948aa3d-1f1a-4142-b5b4-1ed2068f2463.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121268-049f6409-e6b1-4a89-add2-21a83c0c8773.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/130121272-0d977a64-de53-4373-9e13-a6dbf8e75f85.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130121277-f05e56e5-b453-4f36-b9c3-688e4aabc721.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121279-d387ce48-ed7a-433b-a051-4637ed693832.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121280-f5a36514-ed16-4dde-a4c4-c943675fbe34.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121282-d78ddaf0-2b0e-4026-9b45-6adab05ae67e.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130121285-390f448f-8020-4fb9-87e5-069e36271bdb.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121289-7b4f451a-8ee9-4c66-bf5b-348f0df95107.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121291-3ede3967-4043-46f7-a7fb-5e53ee298d17.png)
![monitor-manager-Test_stress_B2234_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121293-d34c8a24-06cb-493f-a4e8-d355a018b9e8.png)
![Test_stress_B2234_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/14913942/130121295-965549cb-baa4-4db0-a5f3-35533a8eaef2.png)
![Test_stress_B2234_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/14913942/130121297-fe2f9c8a-5f61-4dda-b1e6-199feba24f82.png)
![Test_stress_B2234_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/14913942/130121301-32a722fb-931c-4004-ae18-212c32f987e9.png)


   </details>
+ <details><summary>Logs and configuration</summary>

  
    [ossec_Test_stress_B2234_manager_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016886/ossec_Test_stress_B2234_manager_2021-08-16.zip)



   </details>
+ <details><summary>CSV</summary>

    [manager_csv.zip](https://github.com/wazuh/wazuh/files/7016887/manager_csv.zip)


   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
    ![monitor-winagent-Test_stress_B2234_windows-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121352-aaa28808-b9d1-4c60-816f-029c55b949b8.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121354-de093da1-31df-4ec0-9601-206f983daf9c.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121356-e9bca78e-a1ed-4f47-85c7-b6ef57f0120f.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121357-78fdd00d-1501-4cbf-a8b0-896703579bae.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Handles](https://user-images.githubusercontent.com/14913942/130121360-6a43bdb9-df42-4429-9eed-ec25da9b9b4c.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121363-3b6bc2b2-fbaf-4fcd-933b-b93e96e94f69.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121367-ebab74fc-faa9-4334-8e19-9b633849cbba.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121368-173c2bce-bd11-47fc-b3f5-eb3ed480796a.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121370-d97fb41e-dca8-4946-93ad-7597229ec83b.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121372-a6043dbe-79f9-435e-b4f1-e0bd1fc4bcef.png)
![monitor-winagent-Test_stress_B2234_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121376-c6cff0ce-2ad5-4e54-9b8e-334b12eb0b04.png)
![Test_stress_B2234_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130121378-55228c87-51cf-4a59-a79c-4b90cc0ba6c6.png)
![Test_stress_B2234_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130121380-42c54b79-4c09-49d3-ba73-2d59da33235e.png)
![Test_stress_B2234_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130121382-d7b8af42-defb-4c7c-bda9-9a11dea76f53.png)
![Test_stress_B2234_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130121383-db2f3e74-1a09-4618-93d8-56eed63558ce.png)


   </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B2234_windows_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016890/ossec_Test_stress_B2234_windows_2021-08-16.zip)


   </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B2234_windows-pre-release.csv](https://github.com/wazuh/wazuh/files/7016891/monitor-winagent-Test_stress_B2234_windows-pre-release.csv)
[Test_stress_B2234_windows_agentd_state.csv](https://github.com/wazuh/wazuh/files/7016892/Test_stress_B2234_windows_agentd_state.csv)


   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  
    ![monitor-agent-Test_stress_B2234_centos-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121441-0c301ff7-721d-49e4-ac36-6aa575e69f74.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121445-8b5dc12c-b141-4731-a808-633c3a9f3914.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121446-b84c045a-05ad-4fd4-ad31-6e69a6754f8e.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121450-d9bba148-ac9b-409f-b9b8-7cb9ffab87a4.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_FD](https://user-images.githubusercontent.com/14913942/130121452-906b4795-13f7-4105-b2da-32caca3692ec.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130121453-135292af-6cfd-40df-a529-fc2374ddab92.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121455-37a9f97b-8634-4c4a-9ee6-89deb7692003.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121458-3296e96d-5b87-4f0e-85a5-8cbdb104a218.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121461-cfe59506-f4b3-4f26-b955-fa29ee6722b5.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130121462-c4d45d0c-9052-419c-a53b-81a6f90a3671.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121463-aa42b624-f430-448c-8c2e-5057290e1608.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121465-cc515af0-d936-4a0b-a92f-d05b602695a8.png)
![monitor-agent-Test_stress_B2234_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121468-5c98c759-da93-4cc7-a8d2-97c0d044f0b7.png)
![Test_stress_B2234_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130121470-a3a94e03-0b78-4ca3-9b1a-2c48fb2a5590.png)
![Test_stress_B2234_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130121472-7484bff3-653f-4f1f-a290-9a3a4589b93a.png)
![Test_stress_B2234_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130121475-f9499c34-f55b-4349-8265-eb4d5e49c9e7.png)
![Test_stress_B2234_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130121477-eb48f3b8-c4b7-4e1b-83e9-6c30bef9a70b.png)



   </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B2234_centos_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016893/ossec_Test_stress_B2234_centos_2021-08-16.zip)


   </details>
+ <details><summary>CSV</summary>


    [centos_csv.zip](https://github.com/wazuh/wazuh/files/7016896/centos_csv.zip)


   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-Test_stress_B2234_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121534-ac5e775a-3b96-4fe6-ab78-9b06e02a4f6e.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121536-28c91eb3-221c-4e2c-8ae3-cd17fafbb0ba.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121541-df7312c5-c170-47a5-9aaf-22ecb1d2aa4b.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121543-05d7026d-7f76-44a5-a55e-03a6a3963798.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/14913942/130121547-cac2da00-4e7e-4693-9880-f3c7a04b113d.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130121551-d8d485c6-822c-4a31-8e61-6f37dd29902e.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121553-76e95998-3c54-4c24-8be2-ffd7c0055c48.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121557-0f2767e9-d03b-4222-bfc9-1f5e9a4474c5.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121559-00c241e1-073b-4144-8aa4-9a7af3944f62.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130121561-3ac3c1b7-5da2-4a1f-b11f-1a417bb508ea.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121562-a92a3e1e-3249-416d-a9bb-cfb4e9b06934.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121565-c5e08b00-593b-424a-9c01-bd86bb2bfcdd.png)
![monitor-agent-Test_stress_B2234_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121567-655098e5-2438-4ab1-b525-facb35a75119.png)
![Test_stress_B2234_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130121568-79341ace-9c92-41dd-bf81-f7bb816eabfd.png)
![Test_stress_B2234_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130121571-0cc1a1f0-67b0-4176-b5a2-9c646385d12b.png)
![Test_stress_B2234_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130121572-223ebf32-784e-491a-86af-89dbd56cf344.png)
![Test_stress_B2234_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130121575-807885b5-1ef2-4138-b6a1-277a0ce485cb.png)


   </details>
+ <details><summary>Logs and configuration</summary>

 
    [ossec_Test_stress_B2234_ubuntu_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016900/ossec_Test_stress_B2234_ubuntu_2021-08-16.zip)


   </details>
+ <details><summary>CSV</summary>
    
 
    [ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/7016901/ubuntu_csv.zip)



   </details>
</details>
