### ISSUE TITLE
 Release 4.2.0 - Release Candidate 13 - Footprint metrics - Logcollector-SCA 

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#9611]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: https://ci.wazuh.info/job/Test_stress/2195

<details><summary>Stress scripts used</summary>

</details>
<details><summary>Stress configuration</summary>

</details>

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
  ![monitor-manager-Test_stress_B2195_manager-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714229-1c689d42-2515-4161-95f1-f3f1eb80cc8e.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714231-a70bd461-9ff5-4c10-b26b-742477819637.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714232-3ae56f1d-c35f-48b5-9423-2c66b1f753dd.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714237-79d44081-79e0-4396-85f6-15a663904115.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_FD](https://user-images.githubusercontent.com/19505384/129714239-9810ca48-4f6c-4ff2-9907-169652e6aa3e.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129714242-7a18d9e2-34ae-468e-b24b-f381a4024e7a.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714245-dc85063d-dd3c-41e5-98e4-2c8cd8990ef3.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714246-bfe8da97-6d54-494c-a3c0-f08fe4ed30f2.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714247-1a22e445-f079-4a63-9e8b-d22f590a8c0b.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129714251-b81c4ff2-7abc-4918-ae43-e4ee62b63ede.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714253-f2c2b8ac-c593-446f-bea6-952c40ac000a.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714255-ed1e4704-15ef-4d80-a341-6e070f34df1b.png)
![monitor-manager-Test_stress_B2195_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714256-d22a0d58-3c6e-46fc-8064-4b5fbfe4e608.png)
![Test_stress_B2195_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/19505384/129714257-203c5c0d-24e5-4e89-b189-bc7d78057a0c.png)
![Test_stress_B2195_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/19505384/129714258-436c054c-0c07-470d-9160-a59dc3057e9f.png)
![Test_stress_B2195_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/19505384/129714261-3ac38db7-a02b-43f5-ae18-26469200bc24.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  
  [ossec_Test_stress_B2195_manager_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999366/ossec_Test_stress_B2195_manager_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

 
  [B2195_manager_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999367/B2195_manager_centos_csv.zip)

   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
  ![monitor-winagent-Test_stress_B2195_windows-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714329-62dd1c67-7b57-4289-b17b-4563aa678163.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714333-7b07c73b-4cc1-46a8-af72-84cd404286a2.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714334-04e68ecc-1767-4fb8-b933-5fc2693b3c5f.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714337-7eb4f96b-9be3-4191-b9ef-61c0e6cbb852.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Handles](https://user-images.githubusercontent.com/19505384/129714340-3185a388-132b-44bd-b389-eec098ddc8b9.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714341-2d1cef48-4520-438c-91c4-b81c85710912.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714344-b14a047e-9deb-4982-b3f7-87b4e1dc26ca.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714349-69104455-a9e5-4fc0-90c7-78606d387617.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714350-87c17417-79e8-4b1c-a0cd-fd2d9007cb8b.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714352-fa3c63ff-3b94-4f30-908b-fb0a76e44793.png)
![monitor-winagent-Test_stress_B2195_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714355-523c93cc-f36d-424d-b7b2-f546b0034566.png)
![Test_stress_B2195_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129714358-15dd2d89-b57c-4414-a7f7-88b00820a163.png)
![Test_stress_B2195_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129714361-03f9392b-44cc-4201-9a53-73a27fbdf884.png)
![Test_stress_B2195_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129714362-586cd15e-884a-4669-871d-a3c6d5bda2d9.png)
![Test_stress_B2195_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129714364-d3b95990-a244-4c1d-a414-574ed4958db2.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2195_windows_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999369/ossec_Test_stress_B2195_windows_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2195_agent_windows_csv.zip](https://github.com/wazuh/wazuh/files/6999371/B2195_agent_windows_csv.zip)

   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2195_centos-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714416-b34c1549-1fcb-47cc-aeeb-2cbe0af43461.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714420-f406c84c-4725-4b5f-8588-329a4515b541.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714421-5012d328-d713-44ab-9039-b4de79fa1f9a.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714424-b9a84461-087f-45ca-a343-56e0ddd88a7b.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_FD](https://user-images.githubusercontent.com/19505384/129714425-902fd014-b058-4ec4-97e5-f1ce209da154.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129714429-81a8f0e9-880e-4ba7-ac1e-c61e9ce0dba3.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714432-48a53efa-813f-4240-8cf7-6380d79cf05e.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714437-3064c02d-40b5-4470-8936-3be6c1a7e3f1.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714438-caa5ed34-5ff2-479a-9813-c5c9bfb3199e.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129714439-06345454-7f64-421e-96a1-a93f572ca122.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714443-7cf7cad2-f95c-4c1f-869b-e21a6dcb59d8.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714445-33b2b8e1-26e9-4e7b-bd9d-dc6b0eab0048.png)
![monitor-agent-Test_stress_B2195_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714446-05d964ee-a4c9-4e49-9571-cfb15522c107.png)
![Test_stress_B2195_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129714447-06aa3c88-604d-4c59-ad55-b97dfdb6c7f0.png)
![Test_stress_B2195_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129714451-2659fc43-58a8-418b-acbd-aca6cdd517fa.png)
![Test_stress_B2195_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129714453-9866aa93-baa3-4b67-b1f9-2d0c7d6ea294.png)
![Test_stress_B2195_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129714455-b3e36dab-1a2e-4c8c-9509-79b7ae1b5ee6.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2195_centos_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999375/ossec_Test_stress_B2195_centos_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2195_agent_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999376/B2195_agent_centos_csv.zip)

   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2195_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714516-89b7fcfd-f985-4545-96c6-e329fe61e301.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714518-430a870e-cdd8-41e4-bd65-bff6487a9ab6.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714519-2ee531b1-3473-435a-8a84-f9bf83a2a8dc.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714524-7f117df6-9530-4e23-82aa-3874d9f34db5.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/19505384/129714525-db031963-ab36-4527-90b6-73ce4e6fbf9e.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129714530-2b077586-a9b0-4bfe-b11d-96bc0fdd60f2.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714533-e9202184-f686-40c6-b4e1-65a8f9b0a699.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714534-3fdad167-ae9f-46ce-8fe6-1000a25650fd.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714536-a7c5d348-0465-4f2e-8c14-25a434164683.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129714538-2620e8a3-f139-4151-bc38-4750b6ec63eb.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714542-4720f896-e6de-43aa-96ad-b8c31b6a4705.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714545-4e27f2d8-ccba-45a2-afb7-dc86cc7dbcb1.png)
![monitor-agent-Test_stress_B2195_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714547-f6881137-03cb-43ff-bf73-1a4de8b0946c.png)
![Test_stress_B2195_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129714548-793d8dcf-0fd0-42e1-870f-b0c7805bd601.png)
![Test_stress_B2195_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129714549-3e0eeba8-fa95-49a9-857d-9cd7ba586c1b.png)
![Test_stress_B2195_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129714557-7c4b00f4-f25f-42d5-8f5a-8e5d84ce0762.png)
![Test_stress_B2195_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129714560-a211029e-3ba6-4ad9-a1e4-3b8033cde509.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2195_ubuntu_2021-08-14.zip](https://github.com/wazuh/wazuh/files/6999379/ossec_Test_stress_B2195_ubuntu_2021-08-14.zip)

   </details>
+ <details><summary>CSV</summary>
    
  [B2195_agent_ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/6999380/B2195_agent_ubuntu_csv.zip)

   </details>
</details>

**Comment by rauldpm** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

## Stress test documentation

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: 2235

**Results with all manager daemons activated**

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
    ![monitor-manager-Test_stress_B2235_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121693-190f4378-71b6-453d-b78b-5857b9511167.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121696-640b5d9c-07bf-48f9-b88a-a136845b98d1.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121698-92d616c1-84b5-4189-b581-c09fc703dfa0.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121701-03e29e05-d636-4bce-8d52-afeb434de561.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/130121703-97e61702-d820-4436-9ea5-04c0685a0275.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130121705-5cc50091-ac10-40fb-9e17-172d960e76ac.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121707-85c58b74-9066-41d0-8e5d-a3816c68381e.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121710-3d07599e-338b-4f24-95d3-e2db79838b6c.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121711-ad528e44-b65f-4196-97a2-a83b54abd4a4.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130121712-99197ea3-0a39-45aa-abec-1b028a2fcd5b.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121714-a55f7708-27ed-482b-a310-248acc03fd8a.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121716-44febf8b-3f9e-4889-a9d5-7d02a2650577.png)
![monitor-manager-Test_stress_B2235_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121718-c9f28457-f507-494b-9d12-39bcdc80fecf.png)
![Test_stress_B2235_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/14913942/130121720-fe522811-b3d8-4d55-8e19-047665680733.png)
![Test_stress_B2235_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/14913942/130121721-4047590f-4171-467b-9fe8-543e09b97d68.png)
![Test_stress_B2235_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/14913942/130121723-908b1986-48a5-4fef-a95e-b2358950ee30.png)


   </details>
+ <details><summary>Logs and configuration</summary>

  
    [ossec_Test_stress_B2235_manager_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016910/ossec_Test_stress_B2235_manager_2021-08-16.zip)



   </details>
+ <details><summary>CSV</summary>

    [manager_csv.zip](https://github.com/wazuh/wazuh/files/7016911/manager_csv.zip)


   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
    ![monitor-winagent-Test_stress_B2235_windows-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121800-d0a14213-100f-450c-91a0-a804fdb38c64.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121801-09d16562-421d-4551-bd1d-c45824d66e6f.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121803-d11853e7-1300-4caa-9301-035f702e3db4.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121805-20d49431-1077-45dc-b756-f791e112bb39.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Handles](https://user-images.githubusercontent.com/14913942/130121807-202aaa41-fec8-4a52-a9de-7338b643a42a.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121809-179ac4f3-0813-4dfb-b551-d1dbd4bd2c91.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121810-f66f95e8-4e45-4f84-a47e-dbde9adadf2b.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121811-057f1d8b-978b-448e-8abb-dba08dcc023d.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121814-464d579b-b1e7-4af7-ad88-da386dbca408.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121817-015a31fc-0992-4789-8a5a-64aa56616b49.png)
![monitor-winagent-Test_stress_B2235_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121818-9894d6b3-ccb7-427e-a0e3-a594207bd8e7.png)
![Test_stress_B2235_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130121819-f1e25de1-15f5-4c32-865d-6180af7249ab.png)
![Test_stress_B2235_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130121821-be9857a8-42df-431a-b932-266dbccec6ac.png)
![Test_stress_B2235_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130121823-a3300687-d3f9-45d3-8e67-825e19b705e7.png)
![Test_stress_B2235_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130121827-6944301d-5171-4b71-bced-719c0a5e21a7.png)


   </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B2235_windows_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016914/ossec_Test_stress_B2235_windows_2021-08-16.zip)


   </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B2235_windows-pre-release.csv](https://github.com/wazuh/wazuh/files/7016917/monitor-winagent-Test_stress_B2235_windows-pre-release.csv)
[Test_stress_B2235_windows_agentd_state.csv](https://github.com/wazuh/wazuh/files/7016918/Test_stress_B2235_windows_agentd_state.csv)


   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  
    ![monitor-agent-Test_stress_B2235_centos-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130121885-1b5a6490-bd61-4874-92d8-cb91183cf65f.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130121888-c2b146b0-f626-44da-ab19-88f5a3591c39.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130121890-458455ce-4a6c-4718-b367-52054298f65d.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130121892-d18a101b-a83b-4c53-9791-a22adae6d7e6.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_FD](https://user-images.githubusercontent.com/14913942/130121893-68298316-5901-4b90-bcdc-9153ee4b759d.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130121894-047ebeeb-b846-4e04-8728-4e201648604f.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130121897-f46b6d41-ec93-49d0-8af3-505dd5e5ca82.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130121898-a75e440b-0349-4969-8252-d0394de03aae.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130121901-3c026252-4e73-4202-99bc-a83beb01c208.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130121902-51776957-560b-428a-bce3-2237c52a3577.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_USS](https://user-images.githubusercontent.com/14913942/130121907-c9c55091-999f-4359-abb0-4e880dccfad8.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130121908-ce12cb39-0361-4e40-a77f-606d0018980a.png)
![monitor-agent-Test_stress_B2235_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130121911-1817fcee-2ad2-4654-b8bb-f171e490f565.png)
![Test_stress_B2235_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130121912-91d2a41d-6dab-4690-9fda-3e88a4f3bffb.png)
![Test_stress_B2235_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130121914-aa7c3863-f9c4-405d-a5ee-ae6266e27c6a.png)
![Test_stress_B2235_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130121916-224b0d8c-4ec3-49d2-a7b3-61a32343b9be.png)
![Test_stress_B2235_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130121918-21340b2b-1ab1-4c25-be4f-e25ddcc9dbb2.png)



   </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B2235_centos_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016926/ossec_Test_stress_B2235_centos_2021-08-16.zip)


   </details>
+ <details><summary>CSV</summary>

    [centos_csv.zip](https://github.com/wazuh/wazuh/files/7016927/centos_csv.zip)



   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-Test_stress_B2235_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130122027-2f84ac9b-0b88-484b-87ea-439e3e6b8e97.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130122030-431d80c1-6b4b-4b54-bc53-8ed8ae05f9af.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130122032-e46cb477-cc8c-47ff-90d3-a78a13a12def.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130122034-471769a4-7c3b-44fc-81ef-7ed1d6422d62.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/14913942/130122037-16127eed-73ad-434b-af63-b766066d87e1.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130122040-4a1c2cb6-a250-4b92-b14b-460dd43b4744.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130122042-5dbce380-8501-41f0-a2f5-0a8d78317fa8.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130122043-67eacac3-2d24-4da5-8d0c-cd4e87a67959.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130122045-8e4078c4-f07d-4f3e-a07b-81b5a803182e.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130122046-e98dd358-dc02-464a-af3b-d557cf53f0fd.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/14913942/130122048-cdcc45b1-87d0-4052-a1f1-ff6b2df749ba.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130122050-5b61d777-2ea7-4c8a-a2e6-0acc23f711fb.png)
![monitor-agent-Test_stress_B2235_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130122053-7e9df2fc-ed98-4c54-aade-67bfef5ed735.png)
![Test_stress_B2235_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130122055-dc75d2e5-dabe-41a9-84dd-94a8d693b727.png)
![Test_stress_B2235_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130122056-80d2456e-82ad-4da3-b00c-d09ced6884c4.png)
![Test_stress_B2235_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130122061-d64082af-b634-45d3-80c8-88cb800dd9a2.png)
![Test_stress_B2235_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130122063-b798d45c-bf4e-4bf5-8dfc-efbb463d0df9.png)


   </details>
+ <details><summary>Logs and configuration</summary>

 
    [ossec_Test_stress_B2235_ubuntu_2021-08-16.zip](https://github.com/wazuh/wazuh/files/7016929/ossec_Test_stress_B2235_ubuntu_2021-08-16.zip)



   </details>
+ <details><summary>CSV</summary>
    
 
    [ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/7016931/ubuntu_csv.zip)



   </details>
</details>
