### ISSUE TITLE
Release 4.2.0 - Release Candidate 13 - Footprint metrics - Logcollector-Syscheck

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#9612]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: https://ci.wazuh.info/job/Test_stress/2196

<details><summary>Stress scripts used</summary>

</details>
<details><summary>Stress configuration</summary>

</details>

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
  ![monitor-manager-Test_stress_B2196_manager-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714756-114f01ed-8984-4470-b4f5-761d231eff5c.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714759-2a9cdb49-c855-4d8c-8af0-004df92b80f1.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714763-3f6dbd10-0ef6-4460-b5af-a543e770178b.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714764-3ac9d5a8-bf7e-43b0-b070-edf7b0960a05.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_FD](https://user-images.githubusercontent.com/19505384/129714765-fbce02a1-9834-4e86-a516-16a4969d42e1.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129714767-9ea9a135-7bbe-4354-b138-5e3d769380be.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714770-2aaa436a-6d7e-4491-bbfe-fe27b193655f.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714773-be537fd5-185c-428f-bd8e-9ee47fbe3fc9.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714777-9c3440c9-afd2-4614-8c7d-a70bd35f4170.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129714779-bb415ba4-ca38-40a6-b96e-02e384aaaa62.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714781-6c75cfeb-4f74-4ba4-8070-e3a30795be29.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714782-2b2f9094-5312-4827-8ea1-a6c6b4c120b2.png)
![monitor-manager-Test_stress_B2196_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714784-0329637a-75a7-4d75-adf3-9a6b2ac2cbbc.png)
![Test_stress_B2196_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/19505384/129714787-86460f7b-cd0f-4914-a6e0-4d447dc55715.png)
![Test_stress_B2196_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/19505384/129714789-188e6a84-5f86-448a-aa5c-a0aeb6e3fc02.png)
![Test_stress_B2196_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/19505384/129714791-d6a2bc25-4d28-4e04-a425-c94f5b13fe36.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  
  [ossec_Test_stress_B2196_manager_2021-08-15.zip](https://github.com/wazuh/wazuh/files/6999383/ossec_Test_stress_B2196_manager_2021-08-15.zip)

   </details>
+ <details><summary>CSV</summary>

 
  [B2196_manager_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999384/B2196_manager_centos_csv.zip)

   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
  ![monitor-winagent-Test_stress_B2196_windows-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714851-18ea3a47-4a86-4af0-8d66-576eb27cf26c.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714852-c335554a-19d5-438e-8af6-8a72f88bc6d7.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714854-da448464-ad96-490b-9f4d-200fa9ff8414.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714856-436854bc-a3f4-4d60-9296-5bf26e2dcee0.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Handles](https://user-images.githubusercontent.com/19505384/129714858-4ccf1bf6-55a6-4cc4-8322-e14936e373b2.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714859-57074845-6147-44f4-838e-785a8dff91fe.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714860-143fc031-3faa-491d-817d-dde7d13b68fa.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714864-c7536e67-498d-4917-8557-f8c16e154dc2.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714865-0de5e620-1f4c-48b5-8417-91bea6a54037.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714870-ae157783-0841-49b7-843e-fe6ba08f26a5.png)
![monitor-winagent-Test_stress_B2196_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714871-703c5620-2b0a-47ee-b678-769f685afcb1.png)
![Test_stress_B2196_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129714872-2af285b4-937e-4002-906e-66cd9d8e08be.png)
![Test_stress_B2196_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129714873-0e5c7f12-32bb-4866-b8a8-ccee58309581.png)
![Test_stress_B2196_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129714875-f5afc6f9-7aa0-408f-89a6-b80af8ef8060.png)
![Test_stress_B2196_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129714876-aa99de95-9714-48c8-a578-06383831b610.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2196_windows_2021-08-15.zip](https://github.com/wazuh/wazuh/files/6999385/ossec_Test_stress_B2196_windows_2021-08-15.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2196_agent_windows_csv.zip](https://github.com/wazuh/wazuh/files/6999386/B2196_agent_windows_csv.zip)

   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2196_centos-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714928-1c21a219-7102-4eea-8d1f-0ae0b7867a59.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714933-a652d38a-7dac-4a21-a505-4345a6a2e762.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129714934-8f1f964d-967e-4acf-bc88-c72ab4cf8207.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129714935-ea8add27-52c7-419a-b858-1747ba4531be.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_FD](https://user-images.githubusercontent.com/19505384/129714937-0eea9e17-b549-4c84-a683-0ccbffe23303.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129714938-7cbd7917-8d8f-4c56-a5ab-150dd7fc019a.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129714941-4520d281-c5dc-404e-9c56-85e4c6c1596d.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129714944-779d8bc2-2e65-415d-a6d6-22b743b8b3f2.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129714945-c9581e94-9999-4e83-a437-341405bf89f7.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129714947-c8cc8953-e334-45a6-9bcc-a44d4d32abdf.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_USS](https://user-images.githubusercontent.com/19505384/129714948-64b1de7a-ba57-4ae6-8a76-7dd4e55d81cd.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129714950-a2ee11f5-1af0-4bbc-9b72-aa51ce6c2749.png)
![monitor-agent-Test_stress_B2196_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129714951-04e2beea-2012-45b9-ab7b-e3af32d6a357.png)
![Test_stress_B2196_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129714954-4f38962b-af55-4e4b-9b2f-8299fb8f2ef4.png)
![Test_stress_B2196_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129714956-eb944869-29f2-4bdd-b640-2dad48e0902c.png)
![Test_stress_B2196_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129714958-4292e88b-e0ad-40fb-abb1-7b3f8c0b799e.png)
![Test_stress_B2196_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129714959-0a511c83-9d6b-43a4-97a4-9a13a7bef9a1.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2196_centos_2021-08-15.zip](https://github.com/wazuh/wazuh/files/6999391/ossec_Test_stress_B2196_centos_2021-08-15.zip)

   </details>
+ <details><summary>CSV</summary>

  [B2196_agent_centos_csv.zip](https://github.com/wazuh/wazuh/files/6999392/B2196_agent_centos_csv.zip)

   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

  ![monitor-agent-Test_stress_B2196_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/19505384/129714997-91832a00-82e2-498e-8559-c4888b50ed64.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/19505384/129714999-0240824d-f233-4252-bb47-9c2c915687e1.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/19505384/129715001-201d2d35-5f52-4d24-b604-72d887fc42e0.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/19505384/129715003-802cddb2-8e4e-4936-bafb-9ba19171a324.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/19505384/129715005-bbbc8ee4-e610-4c89-8818-0c738e9df738.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/19505384/129715006-c2e1d294-c966-46c1-b83d-95d688b45906.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/19505384/129715007-55b69b29-1c27-4a27-882d-ebce079c343e.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/19505384/129715008-5fe9880e-1c13-45ae-95f8-3c5126e059b3.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/19505384/129715010-710f23c4-175b-4960-8ef4-5c2f3866f03a.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/19505384/129715013-a351ceb8-4711-447f-a6c1-0c84053945a3.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/19505384/129715014-acd586f0-1183-48fc-8c4f-d24cea0fcc8d.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/19505384/129715016-d840a769-2063-4820-98db-9449aac22df3.png)
![monitor-agent-Test_stress_B2196_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/19505384/129715017-893c599b-2899-4704-a65f-850b58711790.png)
![Test_stress_B2196_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/19505384/129715020-8f547115-d3e8-4828-9474-427fedac5143.png)
![Test_stress_B2196_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/19505384/129715021-378d760c-f1cc-4672-bb26-df9c64184f0a.png)
![Test_stress_B2196_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/19505384/129715023-2c6a6772-c6f0-4eeb-9679-c06640348eb5.png)
![Test_stress_B2196_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/19505384/129715024-6fd8bc99-9b74-45e9-9bef-34c3c53a03ab.png)

   </details>
+ <details><summary>Logs and configuration</summary>

  [ossec_Test_stress_B2196_ubuntu_2021-08-15.zip](https://github.com/wazuh/wazuh/files/6999396/ossec_Test_stress_B2196_ubuntu_2021-08-15.zip)

   </details>
+ <details><summary>CSV</summary>
    
  [B2196_agent_ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/6999399/B2196_agent_ubuntu_csv.zip)

   </details>
</details>

**Comment by rauldpm** [comment]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** |#9677 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9573 |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC13                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc13                                         |

## Stress test documentation

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

**Jenkins build**: 2243

**Results with all manager daemons activated**

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>
    
    ![monitor-manager-Test_stress_B2243_manager-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130122171-01441ca5-8942-4941-987e-07df35258b95.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130122173-e15072aa-7c3c-468a-88bb-1eadb3f9dc32.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130122176-f0399703-0444-4da3-bde1-d252878d0a88.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130122179-e60c1533-26a5-4970-8e1c-02de0f684808.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_FD](https://user-images.githubusercontent.com/14913942/130122182-bca233ea-d8a4-44b3-8126-7c68bdff4eea.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130122184-07f287b7-ef21-4ff2-895a-2836c6967f25.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130122187-d3c88681-3713-4c0e-b6a3-df7a57910608.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130122190-2e479323-418e-495b-a171-e0584f723f7d.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130122194-e468f25b-0f13-4efb-b36f-eab2dcebb359.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130122197-c49099d8-fa71-465b-ac23-c56449a9cd90.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_USS](https://user-images.githubusercontent.com/14913942/130122198-bda24aac-50c8-445f-842c-c24b53a905dc.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130122202-22619e7b-b579-45d6-bd85-19baa80f43ce.png)
![monitor-manager-Test_stress_B2243_manager-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130122203-eda818d4-2c00-4b03-a541-754bcfb25162.png)
![Test_stress_B2243_manager_analysisd_state_EDPS](https://user-images.githubusercontent.com/14913942/130122204-dde4d1d6-fe75-4a6d-a775-d1736e7f3b49.png)
![Test_stress_B2243_manager_analysisd_state_Number_Events](https://user-images.githubusercontent.com/14913942/130122205-e5c3203c-1194-4e9d-837e-3eba29abcdee.png)
![Test_stress_B2243_manager_analysisd_state_Queues_state](https://user-images.githubusercontent.com/14913942/130122207-9d6caf46-a5e5-4c3f-8cac-fe1bedfd5f0e.png)


   </details>
+ <details><summary>Logs and configuration</summary>

  
    [ossec_Test_stress_B2243_manager_2021-08-18.zip](https://github.com/wazuh/wazuh/files/7016937/ossec_Test_stress_B2243_manager_2021-08-18.zip)



   </details>
+ <details><summary>CSV</summary>

    [manager_csv.zip](https://github.com/wazuh/wazuh/files/7016938/manager_csv.zip)


   </details>
</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>
 
    ![monitor-winagent-Test_stress_B2243_windows-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130122251-bdb3f31b-9837-4e4a-978e-75d39b7195a7.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130122255-1938ee28-5363-4e4d-a245-b09b3b1553b7.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130122257-db33faa9-e9a3-4583-b028-a0553cffc192.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130122258-0038f3ab-07fc-4f01-b147-980874ae6732.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Handles](https://user-images.githubusercontent.com/14913942/130122260-a7bd8299-3ea5-47af-b8f6-b4f74a9469d8.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130122262-9db80d14-881e-4e0d-b772-5ce509fab516.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130122263-bbc91dca-a179-492b-b64a-acce672ef11f.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130122270-a5ec640c-5811-4114-803d-1a08d3a47e79.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_USS](https://user-images.githubusercontent.com/14913942/130122273-ab062a0b-96e2-47d2-8c9b-73e97ac0e659.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130122275-2d794c53-09fb-41a1-b477-24960929e233.png)
![monitor-winagent-Test_stress_B2243_windows-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130122276-a1cdd6ee-ffd6-4948-bc81-df6ded6a2f0c.png)
![Test_stress_B2243_windows_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130122278-ee285e80-7e64-43f4-bcec-7eb8c433ffb7.png)
![Test_stress_B2243_windows_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130122279-0236d75f-7ab1-4126-a9c9-411aa9719293.png)
![Test_stress_B2243_windows_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130122282-c717d5f6-80a5-4fc6-a674-53cb2614ec25.png)
![Test_stress_B2243_windows_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130122283-720ab314-af95-486a-b070-5bb039bc1adf.png)


   </details>
+ <details><summary>Logs and configuration</summary>

    [windows_logs.zip](https://github.com/wazuh/wazuh/files/7016943/windows_logs.zip)
[fimError_1.log.zip](https://github.com/wazuh/wazuh/files/7016944/fimError_1.log.zip)
[fimError_2.log.zip](https://github.com/wazuh/wazuh/files/7016946/fimError_2.log.zip)


   </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B2243_windows-pre-release.csv](https://github.com/wazuh/wazuh/files/7016947/monitor-winagent-Test_stress_B2243_windows-pre-release.csv)
[Test_stress_B2243_windows_agentd_state.csv](https://github.com/wazuh/wazuh/files/7016948/Test_stress_B2243_windows_agentd_state.csv)


   </details>
</details>

<details><summary>CentOS agent</summary>

+ <details><summary>Plots</summary>

  
    ![monitor-agent-Test_stress_B2243_centos-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130122516-44aa7c0c-468f-4876-ab03-3f891a62ba6f.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130122518-e521385c-26b9-4124-98ae-604bb43d9802.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130122519-106944dd-9ba0-40ab-ad47-9c44a8cce1ca.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130122521-99adf925-0275-4453-9524-83784317a459.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_FD](https://user-images.githubusercontent.com/14913942/130122522-eaf07ab7-4056-4ed6-8729-c270671af119.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130122524-c5876c69-21e6-4945-bd3b-4f9be35f7225.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130122527-087c72f8-e71e-42ef-bc15-c99a5bb87503.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130122528-39ebf0da-d706-4f7d-a719-a5e76fadd7c7.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130122531-dde6e7f0-832e-44d3-8699-892123847849.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130122533-64f3fb24-7c15-496b-a7ac-724199e11548.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_USS](https://user-images.githubusercontent.com/14913942/130122535-684f8624-a17b-4870-90f1-d26644236e9c.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130122537-8ad84bdf-cbe8-4636-a1b9-01a52acc5156.png)
![monitor-agent-Test_stress_B2243_centos-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130122538-71e40373-9025-46d2-b56c-8f099625f8d4.png)
![Test_stress_B2243_centos_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130122541-3c4c76d8-19d3-4df2-b323-8908c22c20e5.png)
![Test_stress_B2243_centos_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130122543-77e2ee44-9ffb-481d-8fc6-498e8f2f9226.png)
![Test_stress_B2243_centos_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130122544-7705d291-8cbf-48d9-8f1d-c1e0f02064d2.png)
![Test_stress_B2243_centos_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130122546-ddc70fbb-520f-48c6-8c56-947a4104a144.png)



   </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B2243_centos_2021-08-18.zip](https://github.com/wazuh/wazuh/files/7016950/ossec_Test_stress_B2243_centos_2021-08-18.zip)


   </details>
+ <details><summary>CSV</summary>


    [centos_csv.zip](https://github.com/wazuh/wazuh/files/7016951/centos_csv.zip)


   </details>
</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![monitor-agent-Test_stress_B2243_ubuntu-pre-release_CPU](https://user-images.githubusercontent.com/14913942/130122595-06f66d61-2cb5-4430-a08b-df67df846092.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_Disk_Read](https://user-images.githubusercontent.com/14913942/130122596-1d9a15e3-4574-40cb-8583-637074383a7b.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_Disk_Written](https://user-images.githubusercontent.com/14913942/130122597-aae84d1b-9428-4434-8899-5e0e039434f2.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_Disk](https://user-images.githubusercontent.com/14913942/130122599-1b20b385-9f7e-40fe-8225-b91694ebe0be.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_FD](https://user-images.githubusercontent.com/14913942/130122601-c7c2fbc1-73e3-43fd-8bbf-db3e9379f0c0.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_PSS](https://user-images.githubusercontent.com/14913942/130122604-31850132-f314-406e-828b-8218ce902c03.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_Read_Ops](https://user-images.githubusercontent.com/14913942/130122607-bec2b660-8d72-4dc3-bb3a-e6531abc1759.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_RSS_MAXMIN](https://user-images.githubusercontent.com/14913942/130122608-4336360c-350e-4577-8486-643459b3097d.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_RSS](https://user-images.githubusercontent.com/14913942/130122609-965791df-8b0e-489d-ae1a-6fff9bb9eda9.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_SWAP](https://user-images.githubusercontent.com/14913942/130122611-df64440f-686e-477c-ab4a-4b7fd82c310a.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_USS](https://user-images.githubusercontent.com/14913942/130122615-1ae36577-c524-455c-a71b-ee5e95efaf51.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_VMS](https://user-images.githubusercontent.com/14913942/130122616-63602734-18b6-48c7-81a1-c2033b3e3f8d.png)
![monitor-agent-Test_stress_B2243_ubuntu-pre-release_Write_Ops](https://user-images.githubusercontent.com/14913942/130122619-e2ead52d-d404-4b61-95fc-a06417957dfa.png)
![Test_stress_B2243_ubuntu_agentd_state_AgentD_Number_of_events_buffered](https://user-images.githubusercontent.com/14913942/130122620-cd615542-d981-4d43-974e-d84211a3bbc3.png)
![Test_stress_B2243_ubuntu_agentd_state_AgentD_Number_of_generated_events](https://user-images.githubusercontent.com/14913942/130122622-b6ca0492-cbee-4551-aeb0-eb5fd922e768.png)
![Test_stress_B2243_ubuntu_agentd_state_AgentD_Number_of_messages](https://user-images.githubusercontent.com/14913942/130122625-8180de06-6364-40e3-9da0-e77ed0fb8238.png)
![Test_stress_B2243_ubuntu_agentd_state_AgentD_Status](https://user-images.githubusercontent.com/14913942/130122628-111379f3-0b2f-4df5-a444-31d79d30f147.png)


   </details>
+ <details><summary>Logs and configuration</summary>

 
    [ossec_Test_stress_B2243_ubuntu_2021-08-18.zip](https://github.com/wazuh/wazuh/files/7016953/ossec_Test_stress_B2243_ubuntu_2021-08-18.zip)



   </details>
+ <details><summary>CSV</summary>
    
 
    [ubuntu_csv.zip](https://github.com/wazuh/wazuh/files/7016954/ubuntu_csv.zip)
 


   </details>
</details>
