### ISSUE TITLE
Analysis increment of Windows disk metric

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#9667]
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue** | https://github.com/wazuh/wazuh/issues/9457 |
| **Main footprint metrics issue** | https://github.com/wazuh/wazuh/issues/9447 |
| **Related issue** | https://github.com/wazuh/wazuh/issues/9484                                         |
| **Version** | 4.2.0                                      |
| **Release candidate #** | RC12                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.2.0-rc12                                         |

## Description
This issue aims to make a deep **Syscollector module** **DISK USAGE** analysis of footprint metrics related to stress tests on Windows OS:
  |Measure|Status|Comment|
  |---|---|---|
  | Disk average use (%) | :red_circle: | 243.36%|
  | Disk_Written | :red_circle: | 6695.59% |

This information is provided in the following comment: https://github.com/wazuh/wazuh/issues/9484#issuecomment-894483461

## DoD
- [x] Analysis evidence
- [ ] Create issues for fixing purposes (if applies)

**Comment by HanesSciarrone** [comment]
## Explanation of Disk consumption

The disk consumption increasing was expected, the reason about this is the new module added on Wazuh 4.2 agent. This module store system infromation on local database used to compare the next system information collected and only send to Wazuh manager data that not match with before sent it. Thanks of that Wazuh has prevented a lot of network traffic, but how Wazuh agent has local database the information storage increase considertly
