### ISSUE TITLE
Bring Authd the capability to avoid re-registering agents that already has valid keys - Unit testing

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9716]
This is a tracking purposes issue to reflect the work that should be done on Unit Testing development for the epic https://github.com/wazuh/wazuh/issues/9549. So, as part of this issue we will:

- Provide 100% of coverage for new functions added to the code.
- Update the coverage for modified functions that already had 100% of coverage.

**Comment by MiguelazoDS** [comment]
### UTs analysis

#### Manager side

The following tests need revision:

- test_auth_validate.c
    - test_w_auth_validate_data
    - test_w_auth_validate_data_force_insert
    - test_w_auth_validate_data_register_limit
- test_auth_parse.c
    - extern w_err_t w_auth_parse_data
    - test_w_auth_parse_data
- test_enrollment_op.c
    - test_setup_context
    - test_setup_context_2
    - test_setup_context_3
    - test_setup_w_enrolment_request_key
    - test_w_enrollment_connect_empty_address
    - test_w_enrollment_connect_empty_config
    - test_w_enrollment_connect_invalid_hostname
    - test_w_enrollment_connect_could_not_setup
    - test_w_enrollment_connect_socket_error
    - test_w_enrollment_connect_SSL_connect_error
    - test_w_enrollment_connect_success
    - test_w_enrollment_send_message_wrong_hostname
    - test_w_enrollment_request_key
    - test_w_enrollment_extract_agent_name_localhost_allowed
    - test_w_enrollment_extract_agent_name_localhost_not_allowed
- test_agent_op.c
    - test_create_agent_add_payload

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/9769 was merged.
