### ISSUE TITLE
Bring Authd the capability to avoid re-registering agents that already has valid keys - Exploratory testing

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9717]
This is a tracking purposes issue to reflect the work that should be done on Exploratory Testing for the epic https://github.com/wazuh/wazuh/issues/9549. So, as part of this issue we will validate that:

- In the case of having communication issues with `remoted`, the `ping-pong` logic will no longer happen with new agents.
- In the case of having communication issues with `remoted`, the `ping-pong` logic will happen with legacy agents.
- The agent properly sends the `K: ` parameter in the registration message to `Authd` in order to validate its key in case of having one.
  - The agent receives a new key if the one that it has is wrong.
  - The agent keeps its key if it is correct.
- The `agent-auth` tool properly sends the `K: ` parameter in the registration message to `Authd` in order to validate its key in case of having one.
  - The agent receives a new key if the one that it has is wrong.
  - The agent keeps its key if it is correct.

**Comment by pereyra-m** [comment]
### Cluster tests

The tests were carried out in the following environment:
- Manager/Worker Ubuntu 20.04, 2 cores, 4GB RAM. Packages installation.
- Agent Ubuntu 20.10, 4 cores, 4GB RAM. Packages installation.

For every case situation:
- Agent key empty: the `client.keys` file is deleted
- Agent duplicated on the manager: the agent is registered the first time correctly

**Comment by MiguelazoDS** [comment]
## Windows agent cases
---

### Environment:

- Wazuh Agent: Windows Server 2019 (Vagrant)
    - Cores: 2
    - RAM: 2GB
- Wazuh Manager: Centos 8 (Vagrant)
    - Cores: 4
    - RAM: 4GB

### Tests (executed in a different order to what is listed above)

- **Inexistent, Agent not duplicated on the manager**
This was the first enrollment process. For this case, the client.keys in the Windows VM was deleted before the manager IP is configured in the ossec.conf file. After the proper configuration, the enrollment process ends successfully.
![1](https://user-images.githubusercontent.com/13010397/130146977-c1f21bc0-d77a-4e33-a2b9-acd388791525.png)
![2](https://user-images.githubusercontent.com/13010397/130146980-22f045bf-4781-4f99-a401-64322ad1878a.png)
- **Empty, Agent not duplicated on the manager**
For this case, the agent was removed from the manager and the client.keys content removed. The enrollment ends successfully.
![3](https://user-images.githubusercontent.com/13010397/130147008-5b8004a8-7653-4a7d-ad75-397b4296da19.png)

**Comment by palaciosjeremias** [comment]
# Environment:
Wazuh Agent: 
- OS: Ubuntu 18.04.4 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic
Wazuh Manager: 
- OS: Ubuntu 20.04.2 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic

# Tests:
All the tests from Linux agent-auth were validated with the expected result:
The key was generated for all the scenarios
![image](https://user-images.githubusercontent.com/11434230/130150205-dfa5f8cc-67e4-43c0-a64b-c130300ef59b.png)
except when the agent already has a key and the same match with the one on the manager side:
![image](https://user-images.githubusercontent.com/11434230/130150283-ad59549a-e2b4-4d3f-a136-0173f12a2551.png)

**Comment by palaciosjeremias** [comment]
## Linux Agentd test cases

### Environment:
Wazuh Agent: 
- OS: Ubuntu 18.04.4 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic
Wazuh Manager: 
- OS: Ubuntu 20.04.2 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic

### Tests:
All the tests from Linux Agentd were validated with the expected result:
The key was generated for all the scenarios
## Linux agent-auth test cases

### Environment:
Wazuh Agent: 
- OS: Ubuntu 18.04.4 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic
Wazuh Manager: 
- OS: Ubuntu 20.04.2 LTS (VMWare)
- Branch: dev-9549-authd-key-hash-logic

### Tests:
All the tests from Linux agent-auth were validated with the expected result:
The key was generated for all the scenarios
![image](https://user-images.githubusercontent.com/11434230/130150205-dfa5f8cc-67e4-43c0-a64b-c130300ef59b.png)
except when the agent already has a key and the same match with the one on the manager side:
![image](https://user-images.githubusercontent.com/11434230/130156515-a9e4fc02-3623-47e5-84a1-2a5fb63ad419.png)

except when the agent already has a key and the same match with the one on the manager side:
![image](https://user-images.githubusercontent.com/11434230/130150283-ad59549a-e2b4-4d3f-a136-0173f12a2551.png)

**Comment by palaciosjeremias** [comment]
## agent_control regression tests
It's confirmed the correct functionality of agent_control listing and controlling the registered agents
![image](https://user-images.githubusercontent.com/11434230/130234332-cbfaa733-e8d9-45b9-801a-33bb7128aeb0.png)
![image](https://user-images.githubusercontent.com/11434230/130234839-3ea4c2e7-5e2b-4f17-a9ba-6dc7978e2594.png)

**Comment by palaciosjeremias** [comment]
## Wazuh-db regression tests
It's confirmed the correct content of the registered agents in the Wazuh DB.
![image](https://user-images.githubusercontent.com/11434230/130235262-32273920-bfb8-4c0f-86ad-2664ff0567a9.png)

**Comment by palaciosjeremias** [comment]
#Remoted regression tests
It's confirmed the correct functionality of Remoted, being able to decrypt, encrypt and communicate with the registered agents.
![image](https://user-images.githubusercontent.com/11434230/130236630-385b0651-5016-42e5-8da8-3e2cb054b8aa.png)

**Comment by palaciosjeremias** [comment]
# Known issues
It's confirmed the fix of the following known issue:
Previously, when the agent fails to communicate with the manager repeatedly, requests a new key that will always replace the previous one.
Besides a ping, pong mechanism was implemented to verify the status of the manager, this leads to a time window where the logic fails and the agent was able to register to replace the old key even if the key was valid.
Now, the agent no longer use the ping logic and directly request keys when fails to communicate; and is Authd the one that will reject the registration if the key is identified as valid.
To test this, Remoted was stoped and we could confirm that when the agent requests the new key, Authd rejects the registration.
![image](https://user-images.githubusercontent.com/11434230/130237742-8da2706c-f6b7-4159-98b1-9f433c20a4d8.png)

**Comment by palaciosjeremias** [comment]
## Upgrade regression tests
It's confirmed the correct functionality of Wazuh manager and Wazuh agent after an upgrade. The agents already registered continue communicating with the manager:


**Agent** **4.1.5** and **manager** **4.1.5** registered and communicating:
![image](https://user-images.githubusercontent.com/11434230/130256553-0d605561-ce78-49e1-85f7-5ac47f807dc3.png)

**Agent** **4.1.5** and **manager** from **dev-9549-authd-key-hash-logic** registered and communicating:
![image](https://user-images.githubusercontent.com/11434230/130257321-ac28e4f8-a4bb-43f8-8eb9-89c462133595.png)

**Agent** from **dev-9549-authd-key-hash-logic** and **manager** from **dev-9549-authd-key-hash-logic** registered and communicating:
![image](https://user-images.githubusercontent.com/11434230/130257773-498598d2-e11d-49be-abb9-448b2bd67fc6.png)
