### ISSUE TITLE
Bring Authd the capability to avoid re-registering agents that already has valid keys - QA plan and execution

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9718]
## Description

This is a tracking purposes issue to reflect all the work done on QA for the epic https://github.com/wazuh/wazuh/issues/9549. In this issue, we will expose the overall QA plan and the results of all the testing performed as well.

In the next sections, we add details and explain the criteria of all the QA instances.

## Code reviews

For each PR created as part of this epic, the reviewer should take into account the next items.

- **Functional revision**: Make sure that the changes satisfy all the requirements of the issue.
- **Performance**: If the implementation performs a task with some complexity level, evaluate the performance of the implemented algorithm.
- **Memory**: Evaluate the right usage of the memory in the heap and the stack as well.
- **Unit testability**: Evaluate if the implementation will allow the development of unit test cases in an easy and effective way.
- **Mantenibilidad**: Evaluate whether the code will be easy to be modified or extended in the future.
- **Spelling and language**: Evaluate the spelling and gram in the comments.
- **Security**: Evaluate whether the code is secure.
- **Interoperability**: Evaluate whether the change should be coordinated and communicated to other teams.

Each reviewer will leave a comment in the review enumerating the criteria taken into account.

## Static analysis of code

- Each pull request should include the results of the `scan-build` execution.
- After having the epic implemented, a `Coverity` analysis will be executed. For details of the results, check the issue https://github.com/wazuh/wazuh/issues/9719.

## Unit testing

As part of this epic, the implementation should have 100% of coverage for all the new functions included in the code, as well as the modified functions that already had 100% of coverage. For details, check the next issue:

- https://github.com/wazuh/wazuh/issues/9716

## Exploratory testing

After having the epic implemented, all the team will perform exploratory testing over the implementation. The exploratory should run the tests described in the comment https://github.com/wazuh/wazuh/issues/9718#issuecomment-898600561 and any other critical test as well. For details of the results, check the next issue:

- https://github.com/wazuh/wazuh/issues/9717

**Comment by DProvinciani** [comment]
## Issues found

In this comment, we will leave a link to each of the issues found in any of the QA instances.

**Comment by DProvinciani** [comment]
## Tests required

In this comment, we will leave a detailed description for each of the tests of interest to validate the right behavior of the overall implementation.

**Comment by palaciosjeremias** [comment]
##User interface:
Authd, and specifically local-server has hard-defined response messages. That's why the new scenario of rejecting the registration of an agent because the key hash match (the previous agent is valid and shouldn´t be replaced) has the same response as when the replace option (force) is disabled.
**main server:**
`ERROR: Duplicated IP: <ip>`
`ERROR: Duplicated agent name: <name>`

**local-server:**
`( 9007), Duplicated IP`
`( 9008), Duplicated name`

On the other hand, the log message it has a specific INFO message to let the user knows the reason of the rejection:
`Agent <id> key already exists on the manager.`

**Comment by DProvinciani** [comment]
As all the related issues were closed, we close this issue.
