### ISSUE TITLE
Bring Authd the capability to avoid re-registering agents that already has valid keys - Coverity analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh#9719]
This is a tracking purposes issue to reflect the results of the Coverity static analysis for the epic https://github.com/wazuh/wazuh/issues/9549. If the scan reports issues, the PR with the fixes should be linked to this issue.

**Comment by palaciosjeremias** [comment]
During the Coverity analysis, 2 issues were identified as new defects introduced during the development:
- **CID 239255** (#1 of 1): Printf arg type mismatch (PW.PRINTF_ARG_MISMATCH) 1. printf_arg_mismatch: argument is incompatible with corresponding format string conversion
- **CID 239256** (#1 of 1): Missing varargs init or cleanup (VARARGS) 8. missing_va_end: va_end was not called for parameters.

**Comment by palaciosjeremias** [comment]
After the fix implemented in https://github.com/wazuh/wazuh/pull/9756, a new Coverity execution shows that the new defects introduced during the development of this feature were fixed.
Coverity report:
https://scan9.coverity.com/reports.htm#v42399/p12779
