### ISSUE TITLE
Implement a method to solve the Agentd and Authd keys management differences

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9720]
As part of the epic #9549, we are implementing a mechanism to send the hash of the agent key to the manager.  When the manager performs the validation of the key coming from the agent (when it has one), the comparison condition never results in `True` because the key that is stored in the structure is not equally calculated.

`authd` and `agentd` differs in the way they initialize the key structure by using a `rehash_keys` option sent to the 
`OS_ReadKeys()` function. `agentd` stores an md5 hash using the raw key, name, and id value from the client.keys file that later will use as an encryption key to communicate with its manager, while `authd` stores just the raw key. 

In this issue we should implement the next items:

- Evaluate the pros and cons to where is the best place to perform the changes. Manager or agent side.
- The new logic should resolve the two different initialization methods.
- It shouldn´t impact in performance or memory usage on the manager side.
- It should make the library more secure and easy to use.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/9724 was merged.
