### ISSUE TITLE
Error in WazuhDBQueryTask's date_fields

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#9736]
|Component|
|---|
| Framework |

## Description
In the `__init__` method of the class `WazuhDBQueryTask`, superclass' `__init__` method is being called like this:
https://github.com/wazuh/wazuh/blob/af255be1a234943e634bb41db3fd21f6a97b1330/framework/wazuh/core/task.py#L33-L38

As of now, the database fields `create_time` and `last_update_time` are not in lowercase but uppercase. This shouldn't be an issue, since in SQLite field names are case insensitive.

The problem is in `WazuhDBQueryTask`'s `_format_data_into_dictionary` method, which is the following:
https://github.com/wazuh/wazuh/blob/af255be1a234943e634bb41db3fd21f6a97b1330/framework/wazuh/core/task.py#L55-L60

Even though field names are case insensitive, the DBMS will return then as uppercase, like they're in the DB, and the aforementioned method won't work, since `create_time` != `CREATE_TIME` and `last_update_time` != `LAST_UPDATE_TIME`; and so the timestamp won't be formatted into UTC.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
# Issue update
I've doing research about  `_format_data_into_dictionary` function and how it's overwritten on each `WazuhDB`'s child class.
Easiest way to fix this error is `lower()` keys. But I want to do more research before making changes.
Regards,
Alexis.

**Comment by Kondent** [comment]
# Issue Update
I've been checking on this again and seems like everything is working properly with `_format_data_into_dictionary` as is.
More specifically, `_format_data_into_dictionary` is currently formatting utc as planned.
It appears to be an error related to unit tests. Its fixed at issue #9424 / pr #9733.
Regards,
Alexis
