### ISSUE TITLE
GCP module improvement research

### ISSUE THREAD

**Issue by abohorqu** [wazuh/wazuh#9753]
|Wazuh version|Component|
|---|---|
| 4.1.5-rev | Modulesd/Integratord |

Hello team,

I am opening this issue to help us identify possible bottlenecks in the GCP integration and in this way see how many EPS would be in theory the maximum supported by the integration/Wazuh.

By researching and testing this, the following possible bottlenecks are identified:

1- It is observed that there is a delay from when the process starts from `modulesd` until it actually begins to pull the messages:

```
2021/08/18 09:31:05 wazuh-modulesd:gcp-pubsub[17667] wm_gcp.c:121 at wm_gcp_run(): DEBUG: Launching command: /var/ossec/wodles/gcloud/gcloud --project wazuh-dev-258815 --subscription_id test_gcloud_blog --credentials_file /var/ossec/wodles/wazuh-dev.json --max_messages 100 --log_level 1
2021/08/18 09:31:09 wazuh-modulesd:gcp-pubsub[17667] wm_gcp.c:171 at wm_gcp_run(): DEBUG: gcloud_wodle - DEBUG - GET CLIENT
2021/08/18 09:31:09 wazuh-modulesd:gcp-pubsub[17667] wm_gcp.c:171 at wm_gcp_run(): DEBUG: gcloud_wodle - DEBUG - CHECK PERMISSIONS
2021/08/18 09:31:09 wazuh-modulesd:gcp-pubsub[17667] wm_gcp.c:171 at wm_gcp_run(): DEBUG: gcloud_wodle - DEBUG - PROCESS MESSAGES
2021/08/18 09:31:09 wazuh-modulesd:gcp-pubsub[17667] wm_gcp.c:171 at wm_gcp_run(): DEBUG: gcloud_wodle - DEBUG - PULL REQUEST STARTED
```

2- To define the desired number of extracted events we use the "`max_messages`" parameter in the configuration. Which according to the documentation is "The maximum number of messages to return for this request. Must be a positive integer". 

Defining a "`max_messages`" value of "180000" and an interval of 1 minute which would be approximately 3000 EPS, the integration only extracts an approximate 450-600 EPS. 

Given that we have identified the possible bottlenecks, we should continue doing tests to see how we can improve it and obtain an agreed maximum of 3000 EPS.

Please let me know if you have any questions.

Regards.

**Comment by MiguelCasaresRobles** [comment]
Solved here: https://github.com/wazuh/wazuh/issues/9774
