### ISSUE TITLE
wazuh-clusterd didn't started.

### ISSUE THREAD

**Issue by iAklis** [wazuh/wazuh#976]
Hello team, I can't start wazuh-clusterd 
```
[root@/var/ossec/bin] #./wazuh-clusterd -d
Error starting wazuh-clusterd: No module named cluster
```
But I make sure the `/var/ossec/framework/wazuh/cluster` is existed

/etc/ossec-init.conf
```
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.5.0"
REVISION="3502"
DATE="Thu Jul 19 23:54:00 CST 2018"
TYPE="server"
```

I removed the whole **/var/ossec** and run the `./install.sh` again. But it didn't work still.

Regards,
Aklis Chen

**Comment by cristgl** [comment]
Hi @iAklis , 

You have installed Wazuh v3.5.0, which is not tested yet. We have tried to reproduce your issue, but it is successfully working. 
Can you please provide more information about your environment configuration (python version, etc)?

I recommend you install Wazuh v3.3 packages [https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-server/index.html](url) and try it again. 

Best regards.

**Comment by iAklis** [comment]
Hi, @cristgl ,

The Python version is `Python 2.7.5`. It works well after I run `ln -s /var/ossec/framework/wazuh wazuh`.

But I wanna to know the cause.  I am glad to provide more detail for teams.

Regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hi @iAklis,

I see you're doing a symbolic link (`ln -s /var/ossec/framework/wazuh wazuh`) to fix the problem. That shouldn't be necessary since Wazuh does it by itself in the code:

https://github.com/wazuh/wazuh/blob/3c2410a3044c296aa5a291df36ac64c9b5cb92e7/framework/scripts/wazuh-clusterd.py#L19-L24

To know exactly why it is happening, I'm going to ask you to do some modifications of the `/bin/wazuh-clusterd.py` script in order to get the error traceback:

https://github.com/wazuh/wazuh/blob/3c2410a3044c296aa5a291df36ac64c9b5cb92e7/framework/scripts/wazuh-clusterd.py#L56-L57
Change that block of code for the following (lines 56 and 57)
```python
except Exception as e:
    raise
```

Thanks,
Marta

**Comment by iAklis** [comment]
Hi @mgmacias95 ,

I followed your advice and print the path appened to stdin. It helps nothing.  
```
[root@worker] /var/ossec/bin$ ./wazuh-clusterd 
./../framework
Traceback (most recent call last):
  File "./wazuh-clusterd", line 49, in <module>
    from wazuh.cluster import __version__, __author__, __ossec_name__, __licence__
ImportError: No module named cluster
[root@worker] /var/ossec/bin$ ls ./../framework/wazuh/
agent.py   common.pyc         database.pyc   __init__.py         __main__.py     ossec_queue.pyc    pyDaemonModule.pyc  syscheck.py      wdb.py
agent.pyc  configuration.py   decoder.py     __init__.pyc        manager.py      ossec_socket.py    rootcheck.py        syscollector.py  wdb.pyc
cluster    configuration.pyc  exception.py   InputValidator.py   manager.pyc     ossec_socket.pyc   rule.py             utils.py
common.py  database.py        exception.pyc  InputValidator.pyc  ossec_queue.py  pyDaemonModule.py  stats.py            utils.pyc
```

Is there some difference between the solution with symbolic link and the original way?

Regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hello @iAklis,

It's been helpful for me since it means that you've been able to import `wazuh`, `wazuh.common`, `wazuh.exception` and `wazuh.pyDaemonModule` but not `wazuh.cluster`.

Can you please paste the output of `ls -l ../framework/wazuh/cluster`? I'd like to check if its a permissions issue.

Thanks,
Marta

**Comment by iAklis** [comment]
Hi @mgmacias95 ,


There is the output `ls -l ../framework/wazuh/cluster`.
```
[root@worker] /var/ossec/bin$ ls -l ../framework/wazuh/cluster
total 264
-rw-r----- 1 root ossec  2535 Jul 20 17:09 cluster.json
-rw-r----- 1 root ossec 20463 Jul 19 23:54 cluster.py
-rw-r----- 1 root root  20223 Jul 20 15:21 cluster.pyc
-rw-r----- 1 root ossec 36167 Jul 19 23:54 communication.py
-rw-r----- 1 root root  37100 Jul 20 15:21 communication.pyc
-rw-r----- 1 root ossec  5601 Jul 19 23:54 control.py
-rw-r----- 1 root root   5318 Jul 20 17:09 control.pyc
-rw-r----- 1 root ossec   535 Jul 19 23:54 __init__.py
-rw-r----- 1 root root    540 Jul 20 15:21 __init__.pyc
-rw-r----- 1 root ossec 31724 Jul 19 23:54 master.py
-rw-r----- 1 root root  26396 Jul 20 15:21 master.pyc
-rw-r----- 1 root ossec 28828 Jul 19 23:54 worker.py
-rw-r----- 1 root root  25495 Jul 20 15:21 worker.pyc
```

Regards,
Aklis

**Comment by mgmacias95** [comment]
Hello @iAklis,

A permissions issue is discarded now. I'd like to ask you some questions about your environment:

* Is it a clean install or an upgrade? If it's an upgrade, from which version? Did you install your previous wazuh installation via packages or sources?
* Can you check if the file `/var/ossec/framework/wazuh/cluster.py` exists? It may be a conflict.
* Which OS are you using?

Thanks,
Marta

**Comment by iAklis** [comment]
Hello @mgmacias95 ,

I install it from sources.
And I removed the whole /var/ossec and run the ./install.sh again. But it didn't work.  

Regards,
Aklis Chen

**Comment by iAklis** [comment]
Hello, @mgmacias95 ,

I found that 
```
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import wazuh
>>> dir(wazuh)
['Connection', 'Wazuh', 'WazuhException', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '__version__', 'common', 'database', 'exception', 'execute', 'main', 'msg', 'python_version', 're', 'strftime', 'utils']
>>> wazuh.__file__
'/usr/lib/python2.7/site-packages/wazuh-3.5.0-py2.7.egg/wazuh/__init__.pyc'
>>> exit()
```

There is a conflict in `PATH`. 

After I were aware of the problem,  I changed that block of code for the following and solved it.
```
 path.insert(0, dirname(argv[0]) + '/../framework')
```

Another one, I don't think append(insert also) the path in PATH from sys.argv is an elegant solution. 

Regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hello @iAklis,

Thank you for your feedback and your help.

What's this file?
```python
>>> wazuh.__file__
'/usr/lib/python2.7/site-packages/wazuh-3.5.0-py2.7.egg/wazuh/__init__.pyc'
```

Wazuh only installs python files under `/var/ossec/framework`, not anywhere else. Can you paste the contents of that directory?

Also, we're working in a python package to fix this problem and many others (for example, not depending on the python version installed in the system). The `path.append` is a temporary solution.

Best regards,
Marta

**Comment by iAklis** [comment]
Hi @mgmacias95 ,

This file is `framework/wazuh/__init__.py`.  The wazuh directory almostly equals `framework/wazuh` but `cluster/` dosen't exist. 

Maybe they were created by my mistake like run `framework/setup.py`

Best regards,
Aklis

**Comment by mgmacias95** [comment]
Hello @iAklis,

Can you paste the contents of the file `/usr/lib/python2.7/site-packages/wazuh-3.5.0-py2.7.egg/wazuh/__init__.py`. I'd like to check its Wazuh version:
https://github.com/wazuh/wazuh/blob/e3411b3de3949d721e45deff0b5c3e0b710743ca/framework/wazuh/__init__.py#L21

Thanks,
Marta

**Comment by iAklis** [comment]
Hi @mgmacias95 ,

The version is '3.5.0'

```
#!/usr/bin/env python

# Created by Wazuh, Inc. <info@wazuh.com>.
# This program is a free software; you can redistribute it and/or modify it under the terms of GPLv2

from wazuh import common
from wazuh.utils import execute
from wazuh.database import Connection
from time import strftime
from wazuh.exception import WazuhException
import re


"""
Wazuh HIDS Python package
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Wazuh is a python package to manage OSSEC.

"""

__version__ = '3.5.0'


msg = "\n\nPython 2.7 or newer not found."
msg += "\nUpdate it or set the path to a valid version. Example:"
msg += "\n  export PATH=$PATH:/opt/rh/python27/root/usr/bin"
msg += "\n  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rh/python27/root/usr/lib64"

try:
    from sys import version_info as python_version
    if python_version.major < 2 or (python_version.major == 2 and python_version.minor < 7 ):
        raise WazuhException(999, msg)
except Exception as e:
    raise WazuhException(999, msg)

class Wazuh:
    """
    Basic class to set up OSSEC directories
    """

    OSSEC_INIT = '/etc/ossec-init.conf'

    def __init__(self, ossec_path='/var/ossec', get_init=False):
        """
        Initialize basic information and directories.
        :param ossec_path: OSSEC Path. By default it is /var/ossec.
        :param get_init: Get information from /etc/ossec-init.conf.
        :return:
        """

        self.version = None
        self.installation_date = None
        self.type = None
        self.path = ossec_path
        self.max_agents = 'N/A'
        self.openssl_support = 'N/A'
        self.ruleset_version = None
        self.tz_offset = None
        self.tz_name = None

        if get_init:
            self.get_ossec_init()

        common.set_paths_based_on_ossec(self.path)

    def __str__(self):
        return str(self.to_dict())

    def to_dict(self):
        return {'path': self.path, 'version': self.version, 'compilation_date': self.installation_date, 'type': self.type, 'max_agents': self.max_agents, 'openssl_support': self.openssl_support, 'ruleset_version': self.ruleset_version, 'tz_offset': self.tz_offset, 'tz_name': self.tz_name}

    def get_ossec_init(self):
        """
        Gets information from /etc/ossec-init.conf.

        :return: ossec-init.conf as dictionary
        """

        try:
            with open(self.OSSEC_INIT, 'r') as f:
                line_regex = re.compile('(^\w+)="(.+)"')
                for line in f:
                    match = line_regex.match(line)
                    if match and len(match.groups()) == 2:
                        key = match.group(1).lower()
                        if key == "version":
                            self.version = match.group(2)
                        elif key == "directory":
                            # Read 'directory' when ossec_path (__init__) is set by default.
                            # It could mean that get_init is True and ossec_path is not used.
                            if self.path == '/var/ossec':
                                self.path = match.group(2)
                                common.set_paths_based_on_ossec(self.path)
                        elif key == "date":
                            self.installation_date = match.group(2)
                        elif key == "type":
                            if (str(match.group(2)) == "server"):
                                self.type = "manager"
                            else:
                                self.type = match.group(2)
        except:
            raise WazuhException(1005, self.OSSEC_INIT)

        # info DB
        conn = Connection(common.database_path_global)

        query = "SELECT * FROM info"
        conn.execute(query)

        for tuple in conn:
            if tuple[0] == 'max_agents':
                self.max_agents = tuple[1]
            elif tuple[0] == 'openssl_support':
                self.openssl_support = tuple[1]

        # Ruleset version
        ruleset_version_file = "{0}/ruleset/VERSION".format(self.path)
        try:
            with open(ruleset_version_file, 'r') as f:
                line_regex = re.compile('(^\w+)="(.+)"')
                for line in f:
                    match = line_regex.match(line)
                    if match and len(match.groups()) == 2:
                        self.ruleset_version = match.group(2)
        except:
            raise WazuhException(1005, ruleset_version_file)

        # Timezone info
        try:
            self.tz_offset = strftime("%z")
            self.tz_name = strftime("%Z")
        except:
            self.tz_offset = None
            self.tz_name = None

        return self.to_dict()


def main():
    print("Wazuh HIDS Library")
```

Regards,
Aklis Chen

**Comment by mgmacias95** [comment]
Hello @iAklis,

Thank you so much for posting that. I thought it could be an older Wazuh version because the cluster subpackage was not present at first (that was your problem actually). But after seeing you have Wazuh v3.5, I realised that our `setup.py` is not correct:

https://github.com/wazuh/wazuh/blob/1efb8a229aecca0c33cba5f978aff0b9786d7565/framework/setup.py#L18

Only package _wazuh_ is specified, but not _wazuh.cluster_. This is why after you run `python setup.py install`, the cluster package wasn't installed.

I'm going to do a pull request to fix that. Thank you so much for your help!!

Best regards,
Marta
