### ISSUE TITLE
Improve AIT environment healthcheck to reduce token requests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#9761]
|Wazuh version|Component|
|---|---|
| 4.3.0 | Wazuh API Integration Tests |

## Description

After this PR https://github.com/wazuh/wazuh/pull/9399/, from the moment tests begin until they finished, the docker healthcheck will be trying to obtain an API token every second.

## Fix

Implement new logic to the healthcheck to check if it could obtain an API token before. If the API goes down after the initial check, all tests must fail so we do not need to check its health every second.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment]
## Update
I finished working with a candidate solution to solve this issue, and seems like it's not flooding with auth requests anymore. Need to discuss few related things with this development with my team and then I can open a PR.
Regards,
Alexis
