### ISSUE TITLE
Randomly disconnected agents

### ISSUE THREAD

**Issue by rejszynski** [wazuh/wazuh#9776]
Hi,

I have stumbled upon an issue, where over a hundred of agents in our production environment randomly disconnected from the manager.
The communication is opened, and we did not add any new rules on firewall and did not change any settings in our network.
When I restarted the manager, agents reconnected successfully, but what is my concern is that I did not have any information about this incident in Wazuh Manager logs.
As far I understand, I should look for this action inside of /var/ossec/logs/ossec.log or am I missing something?
Could anyone guide me how to log this kind of information inside the manager?
Log from agent is not very helpful, because it suddenly says, the Server is unavailable.
But why? Every service is started and works fine, so where to look for additional information about this?
Moreover if server would be unavailable, other agents would disconnect as well.
Log from agent below:

```
2021/08/19 14:04:29 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2021/08/19 14:04:59 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2021/08/19 14:18:09 ossec-agentd: WARNING: Server unavailable. Setting lock.
2021/08/19 14:18:09 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
2021/08/19 14:18:09 ossec-agentd: INFO: Trying to connect to server (192.168.8.70:1514/tcp).
2021/08/19 14:18:14 ossec-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2021/08/19 14:19:46 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
2021/08/19 14:19:46 ossec-agentd: INFO: Trying to connect to server (192.168.8.70:1514/tcp).
2021/08/19 14:20:02 ossec-logcollector: WARNING: Process locked due to agent is offline. Waiting for connection...
2021/08/19 14:20:51 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
2021/08/19 14:20:51 ossec-agentd: INFO: Trying to connect to server (192.168.8.70:1514/tcp).
2021/08/19 14:21:57 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
2021/08/19 14:21:57 ossec-agentd: INFO: Trying to connect to server (192.168.8.70:1514/tcp).
2021/08/19 14:23:02 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
2021/08/19 14:23:02 ossec-agentd: INFO: Trying to connect to server (192.168.8.70:1514/tcp).
2021/08/19 14:24:07 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '192.168.8.70'.
2021/08/19 14:24:07 ossec-agentd: WARNING: Unable to connect to any server.
2021/08/19 14:24:07 ossec-agentd: INFO: Closing connection to server (192.168.8.70:1514/tcp).
```

Wazuh manager version - 3.12.3.
I am looking forward to response.
Thanks.

**Comment by rejszynski** [comment]
Anyone please? :)

**Comment by vikman90** [comment]
@rejszynski sorry for the late reply. I see that @MiguelazoDS already answered this question at Slack.

Let me close this issue as there is another one (#9549) in which we're working to fix known problems related to agent registration. Should you have further questions or troubles do not hesitate to open this issue back.

Best regards.
