### ISSUE TITLE
Investigate FIM db compilation in uncommon systems

### ISSUE THREAD

**Issue by antoniomanuelfr** [wazuh/wazuh#9815]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3| FIM | Manager/Agent | Packages/Sources | All |

Hi team! 
The changes introduced in https://github.com/wazuh/wazuh/pull/9225 are producing some failures in some OS like Solaris 10 when the OS can't find the `stdlibc++`

The purpose of this issue is to investigate these failures and check other systems are not affected by these changes.

- [x] Solaris 10
- [x] Solaris sparc (10, 11)
- [x] HP-UX
- [x] AIX

**Comment by antoniomanuelfr** [comment]
Solaris 10 was fixed in https://github.com/wazuh/wazuh/pull/9225/commits/cca9bb3968e4772bdbaec050d0fa3e6e55da0d4f

**Comment by Dwordcito** [comment]
HPUX Compilation

GCC 9.4
![image](https://user-images.githubusercontent.com/14300208/152657726-7e97bd11-d167-4e00-8fdc-8da640aae63c.png)
Download link:
https://s3.us-west-1.amazonaws.com/packages.wazuh.com/utils/gcc/gcc_9.4_HPUX_build.tar.gz

CMake 3.22.2
![image](https://user-images.githubusercontent.com/14300208/152657746-f8ef270a-ccc3-4ed7-84dc-0e807bf8bc2c.png)
Download link:
https://s3.us-west-1.amazonaws.com/packages.wazuh.com/utils/cmake/cmake_3.22.2_HPUX_build.tar.gz
