### ISSUE TITLE
Wazuh-deb changing

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh#984]
Hi,
I want to install an wazuh agent on a big amount of linux computers.
In order to save time I am trying to change the /var/ossec/etc/ossec.conf file before spreading it.
I started in- "dpkg-deb -R wazuh-agent_3.3.1-1_amd64.deb tmp", modified the server configuration to what i need (ip address, port and protocol).
In addition, I was able to change the server ip on "/usr/share/wazuh-agent/scripts/tmp/gen_ossec.sh": I changed the server ip, and the NEWCONFIG to be "./ossec.conf"
At the end i rebuild the deb package with "dpkg-deb -b tmp wazuh_agent.deb".
After coping the package to a different computer and running "dpkg -i wazuh_agent.deb" i notice that only the server's ip became the address i wanted, while the port&protocol changed back to the default values.

Is there a way to change the port number and protocol before installing the package?

Thank you

**Comment by Cerv1** [comment]
Hi @agentsofshield,

I've been researching what you needed and yes, you can change both the port and the protocol before installing the agent.

You only need to modify the file `/usr/share/wazuh-agent/scripts/tmp/src/init/inst-functions.sh`, exactly, the lines **298** and **299**:
```
echo "      <port>1514</port>" >> $NEWCONFIG
echo "      <protocol>udp</protocol>" >> $NEWCONFIG
```
Here you can change both variables for the value you want. If you have the agent already installed don't forget to uninstall and remove all the configuration before installing the new custom version of the agent to prevent failures.

Also, in this file you can also change the manager's ip address. Exactly in the line **294**:
```
echo "      <address>$SERVER_IP</address>" >> $NEWCONFIG
```
You only need to change `$SERVER_IP` to the value you need.

I hope this helps you.

Best regards,
Sergio.

**Comment by agentsofshield** [comment]
Thank you, worked like a charm! Now we need to do the same with the rpm package, do you know what is the parallel command to dpkg-deb in RHEL and what to change there?

**Comment by Cerv1** [comment]
Hello again @agentsofshield,

As far as I know, there is no equivalent on RHEL distributions. 

You can try to install the agent from sources following this [guide](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_sources.html#installing-linux-agent). Also, this way it's easier to make the changes you need by modifying [this file](https://github.com/wazuh/wazuh/blob/master/src/init/inst-functions.sh#L294-L299) and installing the agent with the installation script.

Best regards,
Sergio.
