### ISSUE TITLE
SPIKE - Windows debug symbols generation analysis

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh#9909]
## Description
This issue aims to get a better understanding of what it is needed for generating debug symbols under Windows platform.

## DoD
- [x] cv2pdb with wine
- [x] Dependencies for achieving this
- [x] Analysis evidence

**Comment by jnasselle** [comment]
# SPIKE results
## cv2pdb
- Sources https://github.com/rainers/cv2pdb
- Precompiled: http://files.npackd.org/cv2pdb/cv2pdb-0.48.exe
- Runtime deps: 
- Linux support: cannot be emulated using wine
- Extract symbols:
- TODO: check if there's a way to set a UUID that allows to check the relation of a symbol file and a binary.
## Enabling dumps during installation
- Wix was able to set proper flags during the installation process
  - Steps to validate:
- Wix was able to create <INSTALLDIR>/dumps folder
  - Steps to validate:
## Check that binaries does not contains symbols at all
- Steps:
- Result: 
## Deploy symbols using compressed zip file
- Steps:
- Result: 
- TODO: symbols file should be signed somehow.
## Debugging session with wingdb
- Steps:
- Result: 
## Analyzing post-mortem dump with gdb
- Steps:
- Result: 
# Proposed implementation
- Extracting symbols with cv2pdb and packaging them into a zip file will be done before creating MSI file in Windows Environment.
