### ISSUE TITLE
OS summary error due to OS name reported from ZscalerOS

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#9926]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.1.5 | Wazuh API & Syscollector| Manager & Agent | Sources | ZscalerOS |

When installing a Wazuh agent on ZscalerOS(https://help.zscaler.com/zia/downloading-vzen-vm) based on `FreeBSD` the OS is reported as `- 0.0` causing the os summary API to fail and Wazuh summary agents not to load in the WUI. 

`WUI` : 

![image](https://user-images.githubusercontent.com/16334770/131114455-767728e9-f308-4b12-a408-8e5d5922b07e.png)

`Wazuh API`: 

![image](https://user-images.githubusercontent.com/16334770/131114545-72ae2e44-be83-4c0a-86f4-6821d603ece3.png)

![image](https://user-images.githubusercontent.com/16334770/131114583-109c5963-be66-40c0-b21b-77aade24e62e.png)

`OS information`: 

![image](https://user-images.githubusercontent.com/16334770/131114857-36a61582-2411-4e2e-bc35-cb4b0134ed2f.png)

Regards,
Wali

**Comment by jnasselle** [comment]
Hi @elwali10 ,

After a failed attempt to get a ZscalerOS demo environment from Zscaler (thanks @tinachoB  btw), we were blindly developing only with the information you kindly shared in this issue.
In case you have the ability to directly or indirectly access some of these environments, the output of the following command will be really useful:
- SQL query to global.db (please obfuscate agent id and key from output)
```
sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent where os_version = '0.0'"
```
- ZscalesOS agent 'version detected' log: excecute the next command in agent's CLI
```
grep "Version detected" /var/ossec/logs/ossec.log
```

Regards,
Nico

**Comment by elwali10** [comment]
Hello @jnasselle, 

Following are the requested information: 

- Output of sqlite3 /var/ossec/queue/db/global.db "SELECT * FROM agent where os_version = '0.0'" 

```
000|ZAB||any|xxxxxxxxxxxxxxxxxxxxxxxx|(null)|0.0|0|0|||(null)|ZscalerOS |ZAB |24-RELEASE-p4 |ZscalerOS 24-RELEASE-p4 #28: Wed Feb 17 17:40:17 PST 2021     root@zero:/usr/obj/usr/src/sys/SMKERNEL |amd64|amd64|Wazuh v4.1.5|ab73af41699f1xxxxxxxxxx00|fd756ba04d9cxxxxxx251|WAZUH|node01|1633014761|1633014802|default|synced|active
```

- Output of  grep "Version detected" /var/ossec/logs/ossec.log 
```
2021/08/27 14:36:16 ossec-agentd: INFO: Version detected -> ZscalerOS |ZAB |24-RELEASE-p4 |ZscalerOS 24-RELEASE-p4 #28: Wed Feb 17 17:40:17 PST 2021     root@zero:/usr/obj/usr/src/sys/SMKERNEL |amd64 [(null)|(null): 0.0] - Wazuh v4.1.5
2021/09/30 20:42:01 ossec-agentd: INFO: Version detected -> ZscalerOS |ZAB |24-RELEASE-p4 |ZscalerOS 24-RELEASE-p4 #28: Wed Feb 17 17:40:17 PST 2021     root@zero:/usr/obj/usr/src/sys/SMKERNEL |amd64 [(null)|(null): 0.0] - Wazuh v4.1.5
```

- Uname  

```
uname -m
 amd64

uname -r
24-RELEASE-p4

uname -s
ZscalerOS

uname -v
ZscalerOS 24-RELEASE-p4 #28: Wed Feb 17 17:40:17 PST 2021     root@zero:/usr/obj/usr/src/sys/SMKERNEL
```

Regards,
Wali

**Comment by jnasselle** [comment]
Thanks @elwali10 !

Apparently when `os_platform` is set to `(null)` (second value of keepalive `[(null)|(null): 0.0]` message section) cause that API could not show Agent Summary in Kibana and API request.

This was addressed also by the current PR.

Regards,
Nico
