### ISSUE TITLE
About the decode error(wazuh version:4.15)

### ISSUE THREAD

**Issue by godt21** [wazuh/wazuh#9935]
|Wazuh version| Component | Action type |
|4.1.5|decoders | error |

## Description
Hi, I am trying complete the easy decoder，refere to the example is no error ,but i try to imporove it and when I use the /var/ossec/bin/ossec-logtest , i meet a error about 
Phase 2: Completed decoding.
       No decoder matched

### LOG example
aabbcc cat 11.22.33.44 2021-08-30
### regex 
\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+

**Comment by jnasselle** [comment]
Hi @godt21 ,

The good news is that your regex actually works! There's a tool [`ossec-regex`](https://documentation.wazuh.com/4.1/user-manual/reference/tools/ossec-regex.html) (`wazuh-regex since v4.2.0`) that allows to check your string against [OSMatch](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/regex.html#sregex-os-match-syntax) and [OSRegex](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax) regular expressions. For example:

```
echo "aabbcc cat 11.22.33.44 2021-08-30" | /var/ossec/bin/ossec-regex '\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+'
+OSRegex_Execute: aabbcc cat 11.22.33.44 2021-08-30
 -Substring: 11.22.33.44
+OS_Regex       : aabbcc cat 11.22.33.44 2021-08-30
```
Notice that your IP was correctly obtained from the log using a OSRegex. This is really a key data, because there are multiple options in decoders, but some only works with OSMatch. You could take a look here:https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/decoders.html

If you define you custom decoder (guide [here](https://documentation.wazuh.com/4.1/user-manual/ruleset/custom.html)) in `/var/ossec/etc/decoders/local_decoder.xml` like the next one:
```xml
<decoder name="testing_some_regex">
    <prematch>\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+</prematch>
    <regex>\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+</regex>
    <order>my_ip</order>
</decoder>
```
And testing it with `ossec-logtest`
```
/var/ossec/bin/ossec-logtest 
2021/08/30 18:14:50 ossec-testrule: INFO: Started (pid: 79554).

ossec-testrule: Type one log per line.

aabbcc cat 11.22.33.44 2021-08-30

**Phase 1: Completed pre-decoding.
       full event: 'aabbcc cat 11.22.33.44 2021-08-30'
       timestamp: '(null)'
       hostname: 'wazuh-dev'
       program_name: '(null)'
       log: 'aabbcc cat 11.22.33.44 2021-08-30'

**Phase 2: Completed decoding.
       decoder: 'testing_some_regex'
       my_ip: '11.22.33.44'
```

Hope this helps!

Regards,
Nico

**Comment by godt21** [comment]
Hi, Nico, thanks for   your answer ,maybe my describe is not complete, I think the relationship of decode and  rule  is the <program_name>something</program_name> , and I can decode my log without program, but my rule can not found the decode, the fllowing is my decode and rule 
decodes : 
```
<decoder name="log-test">
  <program_name>^aabbcc</program_name>
</decoder>
<decoder name="testing_some_regex">
    <parent>log-test</parent>
    <prematch>\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+</prematch>
    <regex>\S+\s(\d+.\d+.\d+.\d+)\s\d+-\d+-\d+</regex>
    <order>my_ip</order>
</decoder>
```
rules:
```
<group name="syslog">

<rule id="100010" level="5">
  <program_name>^aabbcc</program_name>
  <description>log</description>
</rule>
</group>
```

And the /var/ossec/bin/ossec-logtest result as fllowing
```
Since Wazuh v4.1.0 this binary is deprecated. Use wazuh-logtest instead

ossec-testrule: Type one log per line.

aabbcc example 11.22.33.44 2021-08-30


**Phase 1: Completed pre-decoding.
       full event: 'aabbcc example 11.22.33.44 2021-08-30'
       timestamp: '(null)'
       hostname: 'manager'
       program_name: '(null)'
       log: 'aabbcc example 11.22.33.44 2021-08-30'

**Phase 2: Completed decoding.
       No decoder matched.
```

If I do not use the <program></program>, how is the rules match the decode ?

**Comment by godt21** [comment]
If I do not use the `<program></program>` , how is the rules match the decode ?
Regards

**Comment by jnasselle** [comment]
Hi @godt21 ,

Now the problem makes more sense! :smile:. My answers down :arrow_down: 

> Q1: If I do not use the <program_name>something</program_name>, how is the rules match the decode ?

Good question. [<program_name>](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#program-name) relays on a decoder's previous step: the pre-deconding stage, that automatically extract and set some specific values (program_name, timestamp, hostname) from well-known syslog headers formats (i.e RFC3164). 
You can avoid defining a decoder and use only a rule targeting a specific program name, but you can't extract extra content from the logs. For example, only defining a rule (and adding a syslog header)

```
[root@centos8 vagrant]# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.2.0
Type one log per line

Dec 11 01:00:00 host aabbcc[1234]: this is my test log

**Phase 1: Completed pre-decoding.
	full event: 'Dec 11 01:00:00 host aabbcc[1234]: this is my test log'
	timestamp: 'Dec 11 01:00:00'
	hostname: 'host'
	program_name: 'aabbcc'

**Phase 2: Completed decoding.
	No decoder matched.

**Phase 3: Completed filtering (rules).
	id: '100010'
	level: '5'
	description: 'log'
	groups: '['local', 'syslog', 'sshd']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.

```


> Q2: NOT all regex is apply to wazuh ? such as (.*) is match all, but it is not take effect in wazuh

Currently Wazuh support tree regex types: OSRegex, OSMatch and the well-known PCRE. Those regex availability and default value depends on each rule/decoder option. For example [`<status>`](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#status) option accept `osmatch` regex as default,but it could be changed to `pcre2` or `osregex` by using the `type` option attribute:

```
<status type="pcre2">some status value</status>
```

> Q3: Did you have more detail decode and rule syntax, I found more ossec syntax is apply to wazuh, but the document is not show. such as <category></category>

You can find [Ruleset XML Syntax ](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html)in the next links:
- [Rule Syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html)
- [Decoders Syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html)

Here's a link to [`<category>`](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#category) documentation.

> Q4：if the wazuh is support <> for regex such as 
> `(?<create_time>\d+-\d+-\d+\s+\d+:\d+:\d+)\s+\S+\s+(?<src_ip>\S+)\s+\S+\s+\w+\s+device_id=(?<device_client_id>\S+)\s+\S+\s+(?<s    ummary>.*?>)`
> for log 
> `2021-08-31 08:09:14	Local0.Critical	10.10.10.10	TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01  [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>`
> I found the decodes is match `<>` will error and i use `"<>"` will meet error too

That grouping and extracting syntax is not supported by Wazuh. We rely on two decoders options for achieving that: [`<regex>`](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#regex-decoders) and [`<order>`](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#order).

Hope this helps!
Regards,
Nico

**Comment by godt21** [comment]
Hi,Nico:
Tks for your answer,  The Q1 Q3 Q4 have be resolved ， But about Q2 I still have a problem
The log is as fllowing:
`2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>`
My regex is : (`\d+-\d+-\d+\s+\d+:\d+:\d+)\s+\S+\s+(\S+)\s+\S+\s+\w+\s+(\S+)\s+\S+\s+(.*)`
I'v test the regex in python code , and it is valid, the error happened in wazuh is (.*) can not match, we have many not standard log， so we need the (.*)to refer the log 
My decode is as fllowwing:
```
<decoder name="test-log">
    <prematch>(\d+-\d+-\d+\s+\d+:\d+:\d+)\s+\S+\s+(\S+)\s+\S+\s+\w+\s+(\S+)\s+\S+\s+(.*)</prematch>
    <regex>(\d+-\d+-\d+\s+\d+:\d+:\d+)\s+\S+\s+(\S+)\s+\S+\s+\w+\s+(\S+)\s+\S+\s+(.*)</regex> 
    <order>flag, date, cpu, mes</order>
</decoder>
```
And i am not understand the `<status type="pcre2">some status value</status>`  my wazuh tell me the status is `ossec-testrule: ERROR: Invalid element 'status' for decoder 'decoder'`

**Comment by jnasselle** [comment]
Hi @godt21 ,

Happy to help! As i told you previously, [`<regex>`](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/decoders.html#regex-decoders) use [OSRegex ](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/regex.html#regex-os-regex-syntax)regular expression by default. The regex syntax to match anything is (\.*):
![image](https://user-images.githubusercontent.com/1791430/131686734-a8ad2352-be37-44a7-8643-0467c22e5028.png)

By other hand, this log match with default ruleset `windows-date-format` decoder, so yours must inherit from it.

```
<decoder name="test-log">
    <parent>windows-date-format</parent>
    <use_own_name>true</use_own_name>
    <prematch>\d+-\d+-\d+\s+\d+:\d+:\d+\s+\S+\s+\S+\s+\S+\s+\w+\s+(\S+)\s+\S+\s+\.*</prematch>
    <regex>(\d+-\d+-\d+\s+\d+:\d+:\d+)\s+\S+\s+(\S+)\s+\S+\s+\w+\s+(\S+)\s+\S+\s+(\.*)$</regex> 
    <order>flag, date, cpu, mes</order>
</decoder>
```

Testing it with `ossec-logtest`

```

2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>


**Phase 1: Completed pre-decoding.
       full event: '2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>'
       timestamp: '(null)'
       hostname: 'wazuh-dev'
       program_name: '(null)'
       log: '2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>'

**Phase 2: Completed decoding.
       decoder: 'windows-date-format'
       flag: '2021-08-31 08:09:14'
       date: '10.10.10.10'
       cpu: 'device_id=TJ-DC-SDEC-iFW-208-01'
       mes: 'Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>'
```
Notice that output shows `windows-date-format` as decoder despite[ `<use_own_name>`](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/decoders.html#use-own-name) was set `true`. This was solved since v4.1.0 with `wazuh-logtest`, this could be tested as well

```
[root@centos8 vagrant]# /var/ossec/bin/wazuh-logtest 
Starting wazuh-logtest v4.2.0
Type one log per line

2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>

**Phase 1: Completed pre-decoding.
	full event: '2021-08-31 08:09:14 Local0.Critical 10.10.10.10 TJ-DC-SDEC-iFW-208-01: NetScreen device_id=TJ-DC-SDEC-iFW-208-01 [Root]system-critical-00033: Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>'

**Phase 2: Completed decoding.
	name: 'test-log'
	parent: 'windows-date-format'
	cpu: 'device_id=TJ-DC-SDEC-iFW-208-01'
	date: '10.10.10.10'
	flag: '2021-08-31 08:09:14'
	mes: 'Src IP session limit! From 10.10.10.10:12334 to 11.11.11.11:80, proto TCP (zone Trust, int ethernet2). Occurred 1 times. (2021-06-06 08:25:32)<000>'
```

Regarding to your question:

> And i am not understand the <status type="pcre2">some status value</status> my wazuh tell me the status is ossec-testrule: ERROR: Invalid element 'status' for decoder 'decoder'

My example was made to make a point about changing the default regex used several rules and decoders options. For example, if you are using Python Regex, changing  [`<regex>`](https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/decoders.html#regex-decoders) to work with `pcre2` might be more familiar to you.

Regards,
Nico

**Comment by godt21** [comment]
Hi Nico,
   Thanks for your answer, my questions got soloved all, in addition, I have a problem in install wazuh, about the kibana, I use the version 3.31 about es (`https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/elastic_server_deb.html`)and the package to install, the process is successfully, but the kibana hava a error ` Kibana server is not ready yetroot`
If you hava any suggestions
Regards,

**Comment by jnasselle** [comment]
Hi @godt21 ,

Happy to know that my help was useful! 
About your problem with Kibana, it's suggested to keep problems in different threads in order to be more atomic and helpful to other users of our community. I recommend you to join our [Slack Community](https://wazuh.com/community/join-us-on-slack/#thank-you) that it's more dynamic and responsive, with 4K+ users (and Wazuh contributors) available to help!

Regards,
Nico
