### ISSUE TITLE
Impossible to change the API users passwords with CURL

### ISSUE THREAD

**Issue by SimonVCartesoft** [wazuh/wazuh#9936]
Hi everyone,

I'm trying to change the password of 2 users with CURL, but I get this error permanantly..

```
invalid constant string
```

I get a token with this command

```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
```
I have check my token with (echo $TOKEN) and he is ok, I can GET all what i want..
And there is my PUT
```
curl -k -H  "Authorization: Bearer $TOKEN" -X PUT 'https://localhost:55000/security/users/2{"password": "QWer123."}'
```
I only have the defaults users 
- wazuh
- wazuh_wui

<br>
PS: I have try this command on the dev tools (in the plugin, and it's work)

```
PUT/security/users/2{"password": "QWer123."}
```

<br><br>
Someone can help me with this ?
<br>
Thanks you all

**Comment by Selutario** [comment]
Hello @SimonVCartesoft,

In this case, the endpoint you want to use requires some special parameters when used with cURL. 

Specifically, you will need to add a header to indicate that the body schema is `application/json` and then, the body itself where the JSON with the new password will go, as specified in the endpoint reference: [PUT /security/user/{user_id} ](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.security_controller.update_user)

Below you can see a complete cURL example that should work for you. In this case, the password of the user with ID 2 will be updated, which corresponds to `wazuh-wui` user. 
```
curl -k -X PUT "https://localhost:55000/security/users/2?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d '{"password": "QWer123."}'
```

Please note that the token of the affected users will expire after changing the password. Therefore, if you modify `wazuh:wazuh` and it is the one you are using at the moment, you will have to request a new token. 

Let me know any possible questions or problems. 

Regards,
Selu.

**Comment by SimonVCartesoft** [comment]
It's work thank you ;)
