### ISSUE TITLE
[logcollector] Target socket does not work

### ISSUE THREAD

**Issue by soolor** [wazuh/wazuh#9937]
|Wazuh version|Component|Install type|Install method|Platform|
|4.1.5|logcollector|Agent|Packages|Ubuntu|

Hi Everyone,

I meet an issue of logcollecor when i use the target with customer socket. Could you let me know if there's anything missing in the config？

Here're configurations:
--------------------------
  <socket>
      <name>test</name>
      <location>/var/run/test.socket</location>
      <mode>tcp</mode>
      <prefix>box_syslog: </prefix>
  </socket>

   <localfile>
     <log_format>syslog</log_format>
     <location>/var/ossec/test/*.log</location>
     <target>agent, test</target>
   </localfile>

logs in ossec.log: ( i turn on logcollector.debug = 2)
---------------------------------------------------------
root@client04:/var/ossec/etc# cat /var/ossec/logs/ossec.log | grep socket
2021/08/30 11:32:08 ossec-logcollector[11774] logcollector.c:1574 at set_sockets(): DEBUG: Socket 'test' (tcp) added. Location: /var/run/test socket                            <<<<< added
2021/08/30 11:33:05 ossec-logcollector[11774] mq_op.c:157 at SendMSGtoSCK(): ERROR: Unable to connect to socket 'test': /var/run/test.socket (tcp)                          <<<< but failed to connect to

2021/08/30 11:33:28 ossec-logcollector[11774] read_syslog.c:134 at read_syslog(): DEBUG: Read 1 lines from /var/ossec/test/flood-994.log

2021/08/30 11:33:28 ossec-logcollector[11774] mq_op.c:164 at SendMSGtoSCK(): DEBUG: Discarding event from '/var/ossec/test/flood-994.log' due to connection issue with 'test'   <<<<<<

Infor:
-----
root@client04:/var/ossec/etc# cat /etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v4.1.5"
REVISION="40114"
DATE="Thu Apr 22 10:19:35 UTC 2021"
TYPE="agent"

Thanks,
Soolor

**Comment by jnasselle** [comment]
Hi @soolor ,

Could you please share to me your `<socket>` and `<localfile>` block configuration?

Regards,
Nico

**Comment by soolor** [comment]
Hi Jnasselle,
Sorry for missing this.

Here're the configurations:

  <socket>
      <name>test</name>
      <location>/var/run/test.socket</location>
      <mode>tcp</mode>
      <prefix>t-box_syslog: </prefix>
  </socket>

   <localfile>
     <log_format>syslog</log_format>
     <location>/var/ossec/test/*.log</location>
     <target>agent, test</target>
   </localfile>

**Comment by soolor** [comment]
Hi Jnasselle,
It seems to be the format problem.  I copy the configurations in the attached file config.txt.

**Comment by soolor** [comment]
Hi  Jnasselle,

I just closed this issue by mistake. And I reopen it now.
Configurations are copied:

```xml
  <socket>
      <name>test</name>
      <location>/var/run/test.socket</location>
      <mode>tcp</mode>
      <prefix>box_syslog: </prefix>
  </socket>
   <localfile>
     <log_format>syslog</log_format>
     <location>/var/ossec/test/*.log</location>
     <target>agent, test</target>
   </localfile>
```

Could you help on this?

thanks,
Soolor

**Comment by jnasselle** [comment]
Hi @soolor ,

Unfortunately [`<socket>`](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/socket.html) option act as a client and do not create the UNIX socket. Opening it before wazuh execution will allow you to capture logs as you might need. For example, using your configuration:
1. In one terminal open a UNIX socket listener
```
nc -klU /var/run/test.socket
```
2. Restart the manager in other terminal and append a log
```
 systemctl restart wazuh-manager.service
echo "hello world!" >>  /var/ossec/test/mytest.log
```

First terminal will show:
```
box_syslog: hello world!
```
I opened an documentation issue here to add this information: https://github.com/wazuh/wazuh-documentation/issues/4217

Maybe the [socat](https://linux.die.net/man/1/socat) tool will be useful in case you want to push that information to a Web API o redirect it to any kind of communication layer.

Hope this helps!
Regards,
Nico

**Comment by soolor** [comment]
Hello Nico,

Thank you for your response. It really does help for me.

But I have another question: is there any way to add content in the messages  before logcollector sends them to manager?
For example,  I collect the log file mytest.log:

```
   <localfile>
     <log_format>syslog</log_format>
     <location>/var/ossec/test/mytest.log</location>
   </localfile>
```

The content in mytest.log is: hello world!
```
root@client04:/home/appadmin# cat mytest.log
hello world!
```

I expect the manager could receive this, 'box-log' is added:
```
box-log: hellow world!
```

Can wazuh agent do this?

Thanks,
Soolor

**Comment by jnasselle** [comment]
Hi @soolor!

Sure! There are two ways of customizing logs before sending them:
- Using socket's `[<prefix>](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/socket.html#prefix)` option (you already used it :+1: ). Every log sent using this socket will be prepended with this value.
- Using localfile's `[<out_format>`](https://documentation.wazuh.com/4.1/user-manual/reference/ossec-conf/localfile.html#out-format) option. This allows a more powerful log customization thanks to field substitution feature and the possibility to apply this to a particular socket using the `target` attribute.
 For example, using your configuration:
```xml
  <socket>
      <name>test</name>
      <location>/var/run/test.socket</location>
      <mode>tcp</mode>
  </socket>
   <localfile>
     <log_format>syslog</log_format>
     <location>/var/ossec/test/*.log</location>
     <out_format>box-log: $(log)</out_format>
     <target>agent, test</target>
   </localfile>
```
This configuration will send the customized log both manager and socket as well.

Hope this helps!
Regards,
Nico

**Comment by soolor** [comment]
Hello Nico,

I tried in the lab, it works perfectly. Thank you for your great help!

Regards,
Soolor

**Comment by jnasselle** [comment]
Hi @soolor,

You are welcome! We are happy to help our community! I'm going to close this issue, but please feel free to reopen it if you need further help.

Regards,
Nico
