### ISSUE TITLE
Include the actual agent's IP in all the alerts

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#994]
Alerts include the IP address of the agent in the mode it was registered, this is, it may be a CIDR or even "any".

Alerts should include the actual IP of an agent. So we have to decide one of these options:
1. The agent will report its IP to the manager. This IP is the address to reach the agent or the primary agent host's IP.
2. The IP appearing in the alert is the visible address by the manager. This IP may be different if the agent is behind a NAT.

IMHO the second option is the best since it is coherent with the agent key authorization. The agent's IP (endpoint side) can be obtained via Syscollector.

**Comment by jesusgn90** [comment]
Is this related to https://github.com/wazuh/wazuh/issues/630?

Regards!

**Comment by chemamartinez** [comment]
Hi @vikman90 and @jesusgn90,

This issue was solved at https://github.com/wazuh/wazuh/issues/2199 and will be included in the next released version for Linux, Windows and MAC OS X agents.

Regards.
