### ISSUE TITLE
System inventory data is not displayed.

### ISSUE THREAD

**Issue by sahanaprasad** [wazuh/wazuh#9940]
<img width="1423" alt="Screenshot 2021-08-30 at 18 03 51" src="https://user-images.githubusercontent.com/42026982/131339531-8de1dbec-a856-4f73-9b78-5e93b5ec36c5.png">
getting empty tables.
api call is returning following data: {
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No syscollector information was returned",
  "error": 0
}
System inventory is enabled in wazuh-agent:

  <wodle name="syscollector">
    <disabled>no</disabled>
    <interval>2m</interval>
    <scan_on_start>yes</scan_on_start>
    <hardware>yes</hardware>
    <os>yes</os>
    <network>yes</network>
    <packages>yes</packages>
    <ports all="no">yes</ports>
    <processes>yes</processes>
  </wodle>

**Comment by tinachoB** [comment]
Hi @sahanaprasad - Thanks for reporting this.

Could you please let me know which Wazuh manager and Wazuh agent versions did you set up? 
Also, which Operating System are you using in your environment?

I'd like to know a little more context around this issue. Did this happen suddenly? After a fresh install? After an upgrade?

This information will help me to understand what is going on in your env.

Thanks in advance!

**Comment by sahanaprasad** [comment]
hi, @tinachoB Wazuh agent 4.2.0 is installed on the CentOS 7.6 machine.
previously I had installed agent 4.1.5 on a different centos 7 machine. Inventory is working fine for that agent. I also upgraded the agent there to v4.2.0, it's showing the inventory data. I'm facing this issue for the freshly registered agents only.

**Comment by tinachoB** [comment]
Hi @sahanaprasad, thanks for the information.
Did you upgrade the Wazuh manager (with the elastic, filebeat and Kibana modules) too?

**Comment by sahanaprasad** [comment]
No @tinachoB  I did not upgrade the manager. Will that solve the issue?
Also, it's working for one of the agents with v4.2.0 which was upgraded lately.

**Comment by tinachoB** [comment]
Hi @sahanaprasad - That's the problem. You can have agent versions lower than the manager one but you can not the opposite. In other words, you always need to have your manager version up to date (greater version available) to get the expected behavior.
I'd suggest you to upgrade the Wazuh manager and try again. 
Please, let me know if you have further questions.

**Comment by sahanaprasad** [comment]
@tinachoB can you please tell me where can I find the latest Wazuh image for Kubernetes in order to specify it in wazuh-master-sts.yaml and wazuh-worker-sts.yaml?

**Comment by tinachoB** [comment]
Hi @sahanaprasad - You should update your `.yaml` files with the following information:

```
containers:
- name: wazuh-manager
  image: 'wazuh/wazuh-odfe:4.2.0'
```

Please, try this out and let me know.

**Comment by sahanaprasad** [comment]
I tried this and go API connection error @tinachoB

**Comment by tinachoB** [comment]
Hi @sahanaprasad - That means that you need to update your `kibana-deploy.yaml` file with the following:

`image: 'wazuh/wazuh-kibana-odfe:4.2.0'`

**Comment by sahanaprasad** [comment]
<img width="701" alt="Screenshot 2021-08-31 at 18 43 43" src="https://user-images.githubusercontent.com/42026982/131508768-3ae96293-0b68-4f8f-aaa8-e321e5e8ebd1.png">
I still have the issue. made changes in kibana-deploy.yaml @tinachoB

**Comment by tinachoB** [comment]
Could you please double-check that your wazuh-manager service is up and running? (`systemctl status wazuh-manager`).

Also, Could you please execute the following commands in your wazuh manager box? This will help us to find, hopefully, the specific issue:
- `cat /var/ossec/logs/ossec.log | grep -i -E "error|warn|critical"`
- `cat /var/ossec/logs/api.log | grep -i -E "error|warn|critical"`
- `cat /var/log/messages | grep -i segfault`
- `cat /var/log/messages | grep -i memory`

Thanks!

**Comment by sahanaprasad** [comment]
@tinachoB  This is the specific error i'm getting.
<img width="535" alt="Screenshot 2021-09-01 at 10 06 28" src="https://user-images.githubusercontent.com/42026982/131612636-b8cb0469-364d-4e78-8552-20db69154736.png">
wazuh-manager is up and running.
Please find the output of the commands :

`cat /var/ossec/logs/ossec.log | grep -i -E "error|warn|critical"`
output: 2021/09/01 04:33:48 ossec-authd: ERROR: SSL Error (-1)
2021/09/01 04:33:49 ossec-authd: ERROR: SSL Error (-1)
2021/09/01 04:33:52 ossec-authd: ERROR: SSL Error (-1)
2021/09/01 04:34:18 wazuh-analysisd: CRITICAL: (1210): Queue 'queue/sockets/queue' not accessible: 'No such file or directory'

`cat /var/ossec/logs/api.log | grep -i -E "error|warn|critical"`
output: no response for this command

`cat /var/log/messages | grep -i segfault`
output: cat: /var/log/messages: No such file or directory

`cat /var/log/messages | grep -i memory`
output: cat: /var/log/messages: No such file or directory

**Comment by sahanaprasad** [comment]
Got the resolution for this on wazuh slack community.
please refer this thread [https://wazuh.slack.com/archives/C0A933R8E/p1630486853045100?thread_ts=1630484310.039200&cid=C0A933R8E] to resolve the API issue.
Thank You!! @tinachoB  @Selutario  for helping me with this issue.

**Comment by sahanaprasad** [comment]
Got the resolution for this on wazuh slack community.
please refer this thread [https://wazuh.slack.com/archives/C0A933R8E/p1630486853045100?thread_ts=1630484310.039200&cid=C0A933R8E] to resolve the API issue.
Thank You!! @tinachoB @Selutario for helping me with this issue.

**Comment by tinachoB** [comment]
Glad to see you have all up and running, @sahanaprasad ! 
Best!
