### ISSUE TITLE
Fix errors in API agent PUT integration tests

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#9943]
|Component|
|---|
| Wazuh API integration tests |

While testing the code developed for [this issue](https://github.com/wazuh/wazuh/issues/9774), we noticed that two integration tests of the `test_agent_PUT_endpoints.tavern.yaml` set of tests failed. The failed tests were:

1. PUT /agents/node/{node_id}/restart
   - Restart all agents belonging to a node (worker1)
2. PUT /agents/{agent_id}/upgrade_custom
   - Customly upgrade agent 007 selecting installer

We need to investigate if the errors could be due to a race condition, since after relaunching the tests every one of them passed with no problems; and then implement a solution.

The artifacts of the failed tests with the different logs are available for download [here](https://github.com/wazuh/wazuh/files/7082983/artifacts.zip).
### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
If seems the restart test failed because one of the agents was still `pending` and not active:

```
    verify_response_with:
    - extra_kwargs:
        data: '{'affected_items': [{'id': '001', 'status': 'pending'}
```

An agent should never be pending at this point of the test, there have been a completed setup and some delays before it happens.
