### ISSUE TITLE
Read, parse and store new authd configuration options values.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9953]
As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. That being said, it is needed to add the functionality to read the new options from the `ossec.conf` file. 

For this issue, is required:

- Implement the parsing logic for the new `force` configuration block.
- Set default values and store configuration from files.
- Manual validation that the options are properly parsed.
- Return the new configurations when the daemon receives a query of them.

**The configuration options are hidden with the following default values**

```
<enabled>yes</enabled>
<key_mismatch>yes</key_mismatch>  
<disconnected_time enabled="yes">1h</disconnected_time>  
<after_registration_time>1h</after_registration_time>  
```

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10027 was merged.
