### ISSUE TITLE
Implement logic for key_mismatch authd new option.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9954]
As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. That being said, this option should allow the user to choose whether or not an agent is replaced when it already has a valid key.

- This new option should behave as follow:
  - `yes` value: The agent replacement only occurs if the agent sends to the manager a key that doesn't match to the one the manager stores. Implemented in #9549.
  - `no` value: The agent is always replaced. Behavior prior to #9549
- Fix and update the UT cases for this new implementation.

**Take into account that all conditions are complemented to fulfill the force block behavior.**

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10143 was merged.
