### ISSUE TITLE
Implement logic for after_registration_time authd new option.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9955]
As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. This option should allow the user to avoid agent replacement if the agent is not old enough considering its registration time.

- For this new option, the time set in the property is evaluated against the registration date, obtained from the `global` database, and the current time. If the calculus is greater than the value configured, the agent is susceptible to be replaced.
- Fix and update the UT cases for this new implementation.

**Take into account that all conditions are complemented to fulfill the force block behavior.**

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10138 was merged.
