### ISSUE TITLE
Implement logic for disconnected_time authd new option.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9956]
As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. This option allows an agent to be replaced if it is in a disconnected state for a certain period of time.

- This new option should behave as follow:
  - `yes` value: The agent replacement only occurs if the agent is in a `disconnected` state for a specified period of time. The information for that is requested from the `global` database. The disconnected time is set considering any state different from `active` and `pending`. But also a new time field should be included in the `global` database to know how long an agent was disconnected. That value from the database is used to evaluate a condition against the value specified in the setting. Once the agent is active, the field is reset to 0.
  The syntax is: `<disconnected_time enabled="yes">1h<disconnected_time>`
  - `no` value: The agent may be replaced regardless of its state. 
- Fix and update the UT cases for this new implementation.

**Take into account that all conditions are complemented to fulfill the force block behavior.**

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10102 was merged.
