### ISSUE TITLE
Deprecate force_time authd option.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9957]
As part of epic #9550 it is required to add new configuration options to the `authd` module to decide what actions should be taken during an agent replacement. 

For this issue is required:

- Deprecate the `force_time` functionality .
- Add a warning log when the option is found in the configuration file.
- The `force_insert` option should be still parsed to translate its configured value to the new configuration block (#9953).
  - with force_insert = no, the enabled option in the new force block should be false.
  - with force_insert = yes, the default options for the new block will be loaded.
- Remove the setting when the daemon receives a query of them through the socket.
- Perform an upgrade validation.
- Fix UT cases.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh/pull/10207 was merged.
