### ISSUE TITLE
Ignore / Filter Snap partitions

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh#996]
Hello team, we have a problem with the recently added [Snap](https://docs.snapcraft.io/snaps/intro) packages (Ubuntu 18.04 is an example). 

Take a look at the next rule:

```xml
  <rule id="531" level="7" ignore="7200">
    <if_sid>530</if_sid>
    <match>ossec: output: 'df -P': /dev/</match>
    <regex>100%</regex>
    <description>Partition usage reached 100% (disk space monitor).</description>
    <group>low_diskspace,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
  </rule>
```
Snap generates some partitions and they are always at 100% and read only mode. It works in that way but we need to filter them. Take a look at the output of the next command:

```
# df -h | grep loop
/dev/loop0        21M    21M     0 100% /snap/gnome-logs/25
/dev/loop2        13M    13M     0 100% /snap/gnome-characters/103
/dev/loop1       141M   141M     0 100% /snap/gnome-3-26-1604/59
/dev/loop3       3,4M   3,4M     0 100% /snap/gnome-system-monitor/36
/dev/loop4        13M    13M     0 100% /snap/gnome-characters/69
/dev/loop6        15M    15M     0 100% /snap/gnome-logs/37
/dev/loop5       141M   141M     0 100% /snap/gnome-3-26-1604/70
/dev/loop7       3,8M   3,8M     0 100% /snap/gnome-system-monitor/51
/dev/loop8       2,4M   2,4M     0 100% /snap/gnome-calculator/180
/dev/loop9        87M    87M     0 100% /snap/core/4486
/dev/loop10      1,7M   1,7M     0 100% /snap/gnome-calculator/154
/dev/loop11       30M    30M     0 100% /snap/sublime-text/22
/dev/loop12       87M    87M     0 100% /snap/core/4917
```
The above partitions will always generate alerts, this could be a flood if we have multiple agents using Snap. Also in the OSSEC repository they were talking about this (https://github.com/ossec/ossec-hids/issues/1418)

Regards,
Jesús

**Comment by LFBernardo** [comment]
you can simply add the bold entries below to the rule to silence it permanently. Maybe Wazuh can just update the rule for us at source?

 <rule id="532" level="0">
    <if_sid>531</if_sid>
    <match>cdrom|/media|usb|/mount|floppy|dvd|**/dev/loop0**|**/dev/loop1**</match>
    <description>Ignoring external medias.</description>
  </rule>
