### ISSUE TITLE
Logs not showing up in archives.json

### ISSUE THREAD

**Issue by Colgaton** [wazuh/wazuh#9966]
|Wazuh version| Component | Action type |
wazuh-manager-4.2.0-1.x86_64 running on amazon linux 2. All in one install.

## Description
I am trying to ingest aws network firewall alert logs into wazuh. I have rules working already in wazuh-logtest and wazuh are getting the logs from a s3 bucket using aws-s3 and a custom configuration.
But, the logs don't show up in archives.json, and no alerts are generated.

Log show the bucket was scanned:

2021/09/01 20:48:10 wazuh-modulesd:aws-s3: INFO: Executing Bucket Analysis: (Bucket: bucket-name, Type: custom)
2021/09/01 20:48:12 wazuh-modulesd:aws-s3: INFO: Fetching logs finished.

If I use the following command it shows it pulling the files:

/var/ossec/wodles/aws/aws-s3 --bucket bucket-name --debug 10 --type custom --region us-west-2

Rules:

  <rule id="100014" level="7">
      <if_sid>80200</if_sid>
      <field name="aws.firewall_name">\.+</field>
      <field name="aws.availability_zone">\.+</field>
      <field name="aws.event.alert.action">blocked</field>
      <description>AWS Network Firewall: $(aws.event.src_ip) - $(aws.event.dest_ip):$(aws.event.dest_port) - $(aws.event.proto) - $(aws.event.tls.sni) - $(aws.event.alert.action).</description>
  </rule>
  <rule id="100015" level="3">
      <if_sid>80200</if_sid>
      <field name="aws.firewall_name">\.+</field>
      <field name="aws.availability_zone">\.+</field>
      <field name="aws.event.alert.action">allowed</field>
      <description>AWS Network Firewall: $(aws.event.src_ip) - $(aws.event.dest_ip):$(aws.event.dest_port) - $(aws.event.proto) - $(aws.event.tls.sni) - $(aws.event.alert.action).</description>
  </rule>

I understand that even if the logs are not triggering the rules, it should store the logs in the archives.json file because I have logall yes in the ossec.conf:

<ossec_config>
  <global>
    <jsonout_output>yes</jsonout_output>
    <alerts_log>yes</alerts_log>
    <logall>yes</logall>
    <logall_json>yes</logall_json>

I have other buckets being scanned (guardduty, cloudtrail, config) and they work fine. This is the first and only custom bucket, and it is not working.

### Log source / integration
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>5m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="custom">
    <name>bucket-name</name>
    <regions>us-west-2</regions>
  </bucket>
</wodle>

### Log reference
https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-logging.html

### Log examples
{"integration":"aws","aws":{"firewall_name":"Egress-Firewall","availability_zone":"us-west-2b","event_timestamp":"1630377847","event":{"timestamp":"2021-08-31T02:44:07.024634+0000","flow_id":1166309500340431,"event_type":"alert","src_ip":"x.x.x.x","src_port":443,"dest_ip":"x.x.x.x","dest_port":35538,"proto":"TCP","alert":{"action":"allowed","signature_id":2,"rev":0,"signature":"","category":"","severity":3},"tls":{"subject":"CN=ec2messages.us-west-2.amazonaws.com","issuerdn":"C=US, O=Amazon, OU=Server CA 1B, CN=Amazon","serial":"01:F7:1C:FB:5A:DC:88:85:52:B4:EB:7C:1B:D1:37:80","fingerprint":"3a:85:ff:4a:2a:e4:ee:44:d0:d1:9d:6b:f0:37:d9:c6:a5:3d:bb:da","sni":"ec2messages.us-west-2.amazonaws.com","version":"TLS 1.2","notbefore":"2021-01-05T00:00:00","notafter":"2021-12-18T23:59:59","ja3":{},"ja3s":{}},"app_proto":"tls"}}}

**Comment by jcruzlp** [comment]
Hello, first of all, thank you for your patience!
In the [new 4.2.2 release](https://documentation.wazuh.com/current/release-notes/release-4-2-2.html) there was made changes to the `aws-s3.py script` that may help you with this issue. Could you try it with this new version of the script and come here to see the result and study this in more detail if the problem persists?

I hope this could help you.
Best regards!

**Comment by jcruzlp** [comment]
I'll be closing this, if after trying it with the 4.2.2 version please notice us again and we'll open the issue again have a deeper look at it, thank you very much.
