### ISSUE TITLE
EventChannel log collection does not work after upgrading Windows agent to v4.2.0

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#9971]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|v4.2.0 | Installer | Agent | Packages (MSI) - Update | Vista or newer (VersionNT >= 600)|

## Description
Hi team!

After **upgrading** Windows Agent to v4.2.0, the EventChannel log collection feature was lost.

## Steps to reproduce

1. Install v4.1.5 agent using MSI installer. [Link](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.1.5-1.msi)
2. Upgrade agent to v4.2.0  using MSI installer. [Link](https://packages.wazuh.com/4.x/windows/wazuh-agent-4.2.0-1.msi)

## Expected result
- Agent collect EventChannel logs successfully and shows the next kind of messages in ossec.log: `(1951): Analyzing event log: `

## Current result
- Agent does not collect EventChannel logs shows the next kind of messages in ossec.log: `eventchannel not available on this version of Windows`

## Possible cause
- Wazuh installation MSI has two exe files : one with eventchannel support and other without it. Versions equal or newer than Vista are installed with the version without eventchannel support.

Regards,
Nico

**Comment by Dwordcito** [comment]
Fix, https://github.com/wazuh/wazuh/commit/a22553ecfbd599d351afdbec5cd79c43aa7af78a
