### ISSUE TITLE
Syscheck: Recursivity option

### ISSUE THREAD

**Issue by LegitMigue** [wazuh/wazuh#998]
Syscheck always makes a recursively search through the directories indicated in the `<syscheck>` configuration. It would be nice to have an option to choose what directories are indicated for a recursively search and which of them are not. Sometimes there are directories with too many subdirectories to be configured with an <ignore> configuration.
An example: 
```
<directories check_all="yes" realtime="yes" recursivity="no">/opt/directoryWith500SubdirectoriesWichIDONTWantToMonitor/</directories>
<directories check_all realtime="no" recursivity="yes">/opt/directoryWithJust5SubdirectoriesWichIWANTToMonitor/</directories>
```

**Comment by vikman90** [comment]
I would propose this option:

```xml
<directories check_all="yes" recursion_level="4">/home/user</directories>
```

## recursion_level

This option will be the directory depth that FIM should scan.
`0` means scanning only files contained in that folder, but do not scan subdirectories.
Maximum and default value: The value defined by the internal option `syscheck.max_depth`.
