### ISSUE TITLE
Update API endpoints to work with the new configuration block and the deprecated options in authd.

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9988]
|Wazuh version|Component|
|---|---|
| 4.3 | API |

As part of epic #9550 it is required to add new configuration options to the authd module to decide what actions should be taken during an agent replacement. With the new options, it is required to modify the following endpoints. 

- GET /manager/config/auth/auth
- GET /cluster/master-node/configuration/auth/auth
- GET /manager/configuration

The following configuration block is added in the authd section. 

```xml
   <force>                   
      <enabled>yes</enabled>          
      <key_mismatch>yes</key_mismatch>    
      <disconnected_time enabled="yes">1h</disconnected_time>
      <after_registration_time>1h</after_registration_time>
    </force>
```

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment]
We should also update GET /manager/config/auth/auth

**Comment by palaciosjeremias** [comment]
Originally, the insert command sent from the API to Authd had the following payload:
`{"function":"add", "arguments":{"name":"NAME","ip":"IP", "force":FORCE_VALUE}}`
where **force** is an optional value (always used by the API) that represents if the request should be processed with force option disabled (**-1**), always force (**0**), force the insert only when the agent has a last_keep_alive older than N (**N**). 
Other optional values of the payload were: groups, key_hash, key, id.
Regarding the force option, now with the changes of https://github.com/wazuh/wazuh/issues/9550, the payload should be modified to the following format:
`{"function":"add", "arguments":{"name":"NAME","ip":"IP", "force":{"enabled":true, "key_mismatch":true, "disconnected_time":{"enabled":true, "value":VALUE}, "after_registration_time":VALUE}}}`

With the change of this command, we should also define how these values are loaded from the API side.

**Comment by vicferpoy** [comment]
## Issue update

After discussing it with the team, we have decided to always send a full message to the `authd` socket from the API. This means that the user may not use all the `force` parameters, but the API will take the default configuration values to complete the message.

Another consideration is that `key_mismatch` will not be a permitted parameter from the API, but it must be added as well in a lower level (SDK).

### Pending tasks

- Adapt API models.
- Implement default values autocompletion.
- Fix `GET /manager/configuration` parsing algorithm.

The issue can resume now.
