### ISSUE TITLE
Add new unit tests for cluster python module

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#9995]
As we can observe in issue https://github.com/wazuh/wazuh/issues/9877 from the latest RC tests, the total coverage for the python modules is 76% for the `Framework` module, 19% for the `API` module, and 24% for the `Wodles` module.

Since these tests are going to be passed in every PR and in every RC testing protocol, it is very important that we increase our code coverage to guarantee the proper behaviour of every module. Therefore, we should design and add new tests to increase the total coverage for the `cluster` module. The current coverage for the module can be seen in the table below.

## Cluster
| | | | | |
|--|--|--|--|--|
| **Name** | **Stmts** | **Miss** | **Cover** | **Status** |
| framework/wazuh/core/cluster/__init__.py | 5 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/client.py | 145 | 92 | 37% | :orange_square: |
| framework/wazuh/core/cluster/cluster.py | 223 | 95 | 57% | :yellow_square: |
| framework/wazuh/core/cluster/common.py | 395 | 221 | 44% | :orange_square: |
| framework/wazuh/core/cluster/control.py | 69 | 1 | 99% | :green_square: |
| framework/wazuh/core/cluster/dapi/__init__.py | 0 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/dapi/dapi.py | 362 | 89 | 75% | :green_square: |
| framework/wazuh/core/cluster/local_client.py | 95 | 62 | 35% | :orange_square: |
| framework/wazuh/core/cluster/local_server.py | 146 | 146 | 0% | :red_square: |
| framework/wazuh/core/cluster/master.py | 381 | 381 | 0% | :red_square: |
| framework/wazuh/core/cluster/server.py | 146 | 146 | 0% | :red_square: |
| framework/wazuh/core/cluster/utils.py | 122 | 0 | 100% | :green_square: |
| framework/wazuh/core/cluster/worker.py | 419 | 165 | 61% | :yellow_square: |
| TOTAL | 2508 | 1398 | 55% | :red_square: |

## Working branch coverage

|                                               |           |          |           |                |
| --------------------------------------------- | --------- | -------- | --------- | -------------- |
| **Name**                                      | **Stmts** | **Miss** | **Cover** | **Status**     |
| framework/wazuh/core/cluster/__init__.py      | 5         | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/client.py        | 145       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/cluster.py       | 241       | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/common.py        | 430       | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/control.py       | 69        | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/dapi/__init__.py | 0         | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/dapi/dapi.py     | 388       | 22       | 94%       | :green_square: |
| framework/wazuh/core/cluster/local_client.py  | 95        | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/local_server.py  | 146       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/master.py        | 408       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/server.py        | 146       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/utils.py         | 132       | 0        | 92%       | :green_square: |
| framework/wazuh/core/cluster/worker.py        | 326       | 0        | 100%      | :green_square: | 
| TOTAL                                         | 2531      | 25       | 99%       | :green_square: |

**Comment by AdriiiPRodri** [comment]
## Status update

This is the final cluster code coverage:

|                                               |           |          |           |                |
| --------------------------------------------- | --------- | -------- | --------- | -------------- |
| **Name**                                      | **Stmts** | **Miss** | **Cover** | **Status**     |
| framework/wazuh/core/cluster/__init__.py      | 5         | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/client.py        | 145       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/cluster.py       | 241       | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/common.py        | 430       | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/control.py       | 69        | 1        | 99%       | :green_square: |
| framework/wazuh/core/cluster/dapi/__init__.py | 0         | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/dapi/dapi.py     | 388       | 22       | 94%       | :green_square: |
| framework/wazuh/core/cluster/local_client.py  | 95        | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/local_server.py  | 146       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/master.py        | 408       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/server.py        | 146       | 0        | 100%      | :green_square: |
| framework/wazuh/core/cluster/utils.py         | 132       | 0        | 92%       | :green_square: |
| framework/wazuh/core/cluster/worker.py        | 326       | 0        | 100%      | :green_square: | 
| TOTAL                                         | 2531      | 25       | 99%       | :green_square: |
